### PR TITLE
Added support for Alibaba Cloud OSS ECS role authentication (#4284)

### PR DESCRIPTION
**Pull request by aapelismith**
Signed-off-by: aapelismith <aapeli.nian@gmail.com>
fix [#4284](https://github.com/thanos-io/thanos/issues/4284)

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes
Provide ecs role authentication for Thanos, 
Use role name to get credentials(accessKeyId/accessKeySecret) through metadata server

### CODE REVIEW

**Comment by wiardvanrij** [comment]
Still relevant. Needs review

**Comment by wujinhu** [comment]
Hi @aapelismith @wiardvanrij I think this pr is very useful for Alibaba Cloud users, can we reopen it?

**Comment by wujinhu** [comment]
Hi @aapelismith @wiardvanrij I think this pr is very useful for Alibaba Cloud users, can we reopen it?

**Comment by wiardvanrij** [comment]
I'm sorry this fell through the cracks. Most likely requires a lot of rebasing and possibly moving of code (:

**Comment by wujinhu** [comment]
**objstore** has been moved out of thanos repo. https://github.com/thanos-io/objstore
@aapelismith do you have time to finish this pr?

**Pull request closed without merging**
