### PR TITLE
test/e2e: Make sure clean test files cleaned

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

As it pointed out, https://github.com/thanos-io/thanos/pull/2742#issuecomment-642172122,
cleaning up e2e test files.

Fixes `2587`.

* [x] Change is not relevant to the end user.

## Changes

* Introduce a new e2e test helper to clean up the files after scenario is done.

## Verification

* `make test-e2e`

### CODE REVIEW

**Comment by kakkoyun** [comment]
It seems github action doesn't allow us to touch those files. One workaround could be to specify where the temporary files are created. I will investigate more.

**Comment by bwplotka** [comment]
Thanks!

**Comment by kakkoyun** [comment]
Tests are green 🎉 And thanks for the idea @ranjithkumar007 🙇 🙏

**Comment by squat** [comment]
Looks cool! :) and no reason to run on privileged ports :+1:

**Comment by squat** [comment]
:ship:

**Pull request merged**
