### PR TITLE
Change Server TLS Min Version to 1.3

### PR DESCRIPTION
**Pull request by appit-online**
## Changes

Update TLS Min Version for Server - use TLS1.3 - better security support

### CODE REVIEW

**Comment by metalmatze** [comment]
Hey @appit-online, can you please sign off the DCO? That would be fantastic!

**Comment by appit-online** [comment]
@metalmatze can you restart the tests, they failed because of an issue while downloading dependencies

**Comment by squat** [comment]
Restarting the failed testttt

**Review by squat — APPROVED** [review]

**Comment by siavashs** [comment]
Few years too late to comment but I think this is bad for backwards compatibility for the sake of security on paper.
Most Thanos installations live in private networks and accessed through VPNs, etc. significantly reducing any risks of using older TLS version.

**Pull request merged**
