### PR TITLE
Add Softonic as adopter

### PR DESCRIPTION
**Pull request by bvis**
Want to add Softonic as Thanos adopter

### CODE REVIEW

**Comment by bwplotka** [comment]
ping (:

**Comment by bvis** [comment]
Sorry I was on holidays. Let's try again!

**Comment by bwplotka** [comment]
You need to still sign the commit (:

**Comment by bvis** [comment]
Sorry, now I have rebased my fork. Let's try again. ;)

**Comment by bwplotka** [comment]
Still signing not successful (:

Please follow info here: https://github.com/thanos-io/thanos/pull/1405/checks?check_run_id=208111592

**Comment by bvis** [comment]
Sorry I totally missed it up!

**Comment by bvis** [comment]
I've created a new PR with the same changes. Closed this.

**Pull request closed without merging**
