### PR TITLE
ui: replace go-bindata with embed

### PR DESCRIPTION
**Pull request by longngn**
Fixes https://github.com/thanos-io/thanos/issues/3782

* [x] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

- Replace go-bindata with embed

## Verification

- I open web UI of `thanos query` and `thanos tools bucket web` and saw no error

### CODE REVIEW

**Comment by longngn** [comment]
Why with go-bindata, we ignored `(.*\.map|bootstrap\.js|bootstrap-theme\.css|bootstrap\.css)`?

**Comment by longngn** [comment]
One check blocked by https://github.com/prometheus/golang-builder/pull/109

**Comment by GiedriusS** [comment]
> Why with go-bindata, we ignored `(.*\.map|bootstrap\.js|bootstrap-theme\.css|bootstrap\.css)`?

Source maps increase the binary's size by a lot and I don't remember about bootstrap. IIRC it's because we use the minified versions in the final build:
```
pkg/ui/templates/_base.html:        <script src="{{ pathPrefix }}/static/vendor/bootstrap-4.1.3/js/bootstrap.min.js?v={{ buildVersion }}"></script>
pkg/ui/templates/_base.html:        <link type="text/css" rel="stylesheet" href="{{ pathPrefix }}/static/vendor/bootstrap-4.1.3/css/bootstrap.min.css?v={{ buildVersion }}">
```

**Review by kakkoyun — CHANGES_REQUESTED** [review]
Looking good!!! Thanks @longngn 

However could you please extract to go upgrade part into another PR? And follow https://github.com/thanos-io/thanos/blob/master/docs/contributing/how-to-change-go-version.md

It makes life easier for us to track down the issues.

**Comment by kakkoyun** [comment]
@longngn Let's rebase and move forward with this as well.

**Comment by kakkoyun** [comment]
Hey @longngn 👋 We're going to cut a release candidate soon, is there any chance for you to push this to the finish line?

**Comment by longngn** [comment]
> Hey @longngn 👋 We're going to cut a release candidate soon, is there any chance for you to push this to the finish line?

I've rebased with the main branch. AFAIK there's no way to exclude certain pattern with go embed, so the resulting binary might be heavier. On my Mac the binary size is 67MB.

**Comment by kakkoyun** [comment]
@longngn Thanks for the heads up.
I think we need to discuss if we really want this?
cc @bwplotka @GiedriusS @onprem

**Comment by bwplotka** [comment]
Is this something we can tell the Go `goembed` community? Create some issue?

I don't think 67MB is considered big, but for safety I would release Thanos 0.20 without it. WDYT?

**Comment by brancz** [comment]
We still have a build process that produces the build artifacts of the react app, no? What's the problem with deleting everything except the resulting artifact for release binaries?

**Comment by onprem** [comment]
I think we are excluding the source-maps from the build artifacts currently which contributes to the size reduction. Since we are deleting these source-maps anyways, I vote for not even generating them (this can be done setting env variable `GENERATE_SOURCEMAP=false`).

**Comment by onprem** [comment]
I just did three builds locally, `thanos-bindata` is current main branch, `thanos-embed-sourcemap` is the build from this branch which contains the sourcemaps, and the third `thanos-embed` binary is with a patch on top of this branch to not generate sourcemaps (modified `scripts/build-react-app.sh` to have `PUBLIC_URL=. GENERATE_SOURCEMAP=false yarn build`).

```
-rwxr-xr-x  1 prem prem  56M Apr 21 14:51 thanos-bindata
-rwxr-xr-x  1 prem prem  61M Apr 21 15:02 thanos-embed
-rwxr-xr-x  1 prem prem  69M Apr 21 14:58 thanos-embed-sourcemap
```

There's about 5M of difference between bindata (without sourcemaps) and go-embed without sourcemaps which sounds acceptable to me.

**Comment by kakkoyun** [comment]
@longngn Could you please rebase?

**Comment by longngn** [comment]
> @longngn Could you please rebase?

Done. 
IMO we could delete the sourcemap and unnecessary files in release pre-build step.

**Pull request closed without merging**
