### PR TITLE
do not mark bug label as stale

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@thanos-io/thanos-maintainers
Need to discuss which label should be ignored, while i think "bug" should not be marked as stale.

**Comment by kakkoyun** [comment]
Maybe `pinned` as well? https://github.com/thanos-io/thanos/issues?q=is%3Aopen+is%3Aissue+label%3Apinned

**Comment by daixiang0** [comment]
Good find, wait for another input, then update.

**Comment by bwplotka** [comment]
Pinned and bug label sounds perfect for now (:

**Comment by daixiang0** [comment]
@bwplotka done.

**Pull request merged**
