### PR TITLE
query: add --grpc-compression for enabling compression

### PR DESCRIPTION
**Pull request by GiedriusS**
Add a new `--grpc-compression` option that enables gRPC compression.
Snappy works well - I've observed barely any increase in CPU/RAM usage
and the network throughput dropped.

I have also tried zstd with default settings but it increased the
99p quite a bit. Perhaps we could investigate zstd more in the future.

### CODE REVIEW

**Review by fpetkovski — APPROVED** [review]
Nice 👍 

Out of curiosity, how much was the throughput drop, and did you get a chance to observe any difference in query performance?

**Comment by yeya24** [comment]
This is a nice improvement! Can you update the changelog as well? Thanks!

**Comment by GiedriusS** [comment]
Added, PTAL @yeya24

**Review by yeya24 — APPROVED** [review]
LGTM

**Pull request merged**
