### PR TITLE
store & compact: For components that operates on blocks - expose the UI on /loaded-blocks

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by bwplotka** [comment]
Also fixed comments from https://github.com/thanos-io/thanos/pull/2354

**Comment by bwplotka** [comment]
All works (: 

image


PTAL @squat

**Comment by metalmatze** [comment]
The gist of this is: Store now has the Bucket UI for the blocks it has loaded, correct?

**Comment by bwplotka** [comment]
Yes, in more extended way:

* Store now has the Bucket UI for the blocks it has loaded in `/loaded`
* Compactor has two UIs:
   * `/loaded` for what Compactor is seeing (e.g based on sharding) 
   * `/global` for what overall we have in whatever form in the bucket (:

**Pull request merged**
