### PR TITLE
Fixed non-octal os.FileMode

### PR DESCRIPTION
**Pull request by iamrajiv**
## Description

[os.FileMode](https://golang.org/pkg/os/#FileMode) should be an octal number. For example 0700, 0644.

### CODE REVIEW

**Review by ianbillett — CHANGES_REQUESTED** [review]
@iamrajiv please take another look at this PR - I think you have borked a commit or something :)

**Comment by iamrajiv** [comment]
@ianbillett Please take a look now.

**Comment by Namanl2001** [comment]
`bindata.go` is an auto generated file and we've to regenerate it after every change in the UI using [make assets](https://github.com/thanos-io/thanos/blob/8d3ea521598cf8d37b6079eabe4e562939a3c66d/Makefile#L98). I guess the changes in this pr are temporary and would be reverted once the file is regenerated again in future. I wonder if we could have some permanent solution to this.

**Comment by yeya24** [comment]
@Namanl2001 is right. Close this pr now.

**Comment by ianbillett** [comment]
@Namanl2001 is right - our [Makefile](https://github.com/thanos-io/thanos/blob/e3b0baf7de9dde1887253b1bb19d78ae71a01bf8/Makefile#L104) generates `pkg/ui/bindata.go` so we don't want to make or maintain any modifications to that.

The changes you propose are valid, but they are resulting from the code generated by the upstream go-bindata project.

**Comment by bwplotka** [comment]
Let's close it and improve go-bindata then. Do you mind contributing there @iamrajiv? Thanks!

**Comment by iamrajiv** [comment]
Yeah sure @bwplotka will try to improve `bindata.go` will make PR soon. I am still going through the code structure of Thanos.

**Pull request closed without merging**
