### PR TITLE
Shortcut .+ and .* regex matchers

### PR DESCRIPTION
**Pull request by yeya24**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

`.*` and `.+` are commonly used in Grafana when querying Prometheus.

For `.*`, it will match empty so it fetches all values and exclude values that dont match `.*`: `!m.Matches(val)`. But from https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels, `.*` should match all the allowed label values so I think we can shortcut the posting group to a match all but doesn't have any keys. This saves the time of calling `LabelValues` and matching strings.

For `.+`, it doesn't match empty string. So it will fetch all values of the label name and add all values that matches `.+`. Value itself should be non empty in TSDB so `.+` should match all. Then we can exclude the matching part. This saves the time of matching strings.

## Verification

Tests should still pass. Will add benchmark update.

### CODE REVIEW

**Review by MichaHoffmann — APPROVED** [review]
lgtm

**Comment by MichaHoffmann** [comment]
i checked the behaviour briefly in prometheus by adding a couple unittests to `TestPostingsForMatchers` in prometheus/tsdb/querier_test.go:

```
	app := h.Appender(context.Background())
	app.Append(0, labels.FromStrings("n", "1"), 0, 0)
	app.Append(0, labels.FromStrings("n", "1", "i", "a"), 0, 0)
	app.Append(0, labels.FromStrings("n", "1", "i", "b"), 0, 0)
	app.Append(0, labels.FromStrings("n", "2"), 0, 0)
	app.Append(0, labels.FromStrings("n", "2.5"), 0, 0)
	require.NoError(t, app.Commit())
```

passes these tests:

```		
		{
			matchers: []*labels.Matcher{labels.MustNewMatcher(labels.MatchRegexp, "i", ".+")},
			exp: []labels.Labels{
				labels.FromStrings("n", "1", "i", "a"),
				labels.FromStrings("n", "1", "i", "b"),
			},
		},
		{
			matchers: []*labels.Matcher{labels.MustNewMatcher(labels.MatchEqual, "i", "")},
			exp: []labels.Labels{
				labels.FromStrings("n", "1"),
				labels.FromStrings("n", "2"),
				labels.FromStrings("n", "2.5"),
			},
		},
		{
			matchers: []*labels.Matcher{labels.MustNewMatcher(labels.MatchNotEqual, "i", "")},
			exp: []labels.Labels{
				labels.FromStrings("n", "1", "i", "a"),
				labels.FromStrings("n", "1", "i", "b"),
			},
		},
		{
			matchers: []*labels.Matcher{labels.MustNewMatcher(labels.MatchRegexp, "i", ".*")},
			exp: []labels.Labels{
				labels.FromStrings("n", "1"),
				labels.FromStrings("n", "2"),
				labels.FromStrings("n", "2.5"),
				labels.FromStrings("n", "1", "i", "a"),
				labels.FromStrings("n", "1", "i", "b"),
			},
		},
```

So the logic seems sound

**Review by GiedriusS — COMMENTED** [review]
I think this breaks compatibility. See https://github.com/prometheus/prometheus/issues/7859

**Comment by MichaHoffmann** [comment]
> I think this breaks compatibility. See [prometheus/prometheus#7859](https://github.com/prometheus/prometheus/issues/7859)

in PromQL it makes a difference when [computing labels for absent](https://github.com/thanos-io/promql-engine/blob/e1ae4275b96e876d9005ac3e817f1ec0ecc81cc0/execution/function/absent.go#L44) for example but in tsdb it makes no difference iiuc.

**Comment by yeya24** [comment]
I see just found that label value can have any Unicode char so it can contain new line.

I am not sure who really uses new line as part of the label value but yeah it is not safe anyway.

**Comment by yeya24** [comment]
I am wondering if we should allow this behavior under a feature flag.
If your label value doesn't have new line, then you can opt in turn on the optimization.

**Comment by yeya24** [comment]
I will close this pr for now. I think it is better to have the change in upstream Prometheus first

**Pull request closed without merging**
