### PR TITLE
docs: fix URLs preventing generation and unblock CI

### PR DESCRIPTION
**Pull request by squat**
This PR fixes the URLs for several links in the docs that are currently breaking CI.

I noticed that CI was failing [0] for PR
https://github.com/thanos-io/thanos/pull/5284 because Ian had changed
his GitHub handle from @ianbillett to @bill3tt. This PR  fixes this.

Currently, documentation generation is failing because mdox can't fetch
some GitHub documentation pages since the URLs for the help content has
changed. This commit updates the links to use the correct URLs.

[0] https://github.com/thanos-io/thanos/runs/6050355497?check_suite_focus=true#step:5:135

Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

### CODE REVIEW

**Comment by squat** [comment]
This PR is failing because the busybox SHAs are incorrect. This is fixed by: https://github.com/thanos-io/thanos/pull/5283.
That PR will likely also fail because of docs, which is fixed by this PR. We will need to override CI for one of them.

**Comment by squat** [comment]
Two of the pages are failing to fetch because GitHub doesn't like that we don't send a user-agent. This causes the GitHub documentation site to respond with a 403. If we send a very basic header like `User-Agent: Chrome`, the request works.

**Comment by saswatamcode** [comment]
Hmm, we do [send a `User-Agent: mdox` request header](https://github.com/bwplotka/mdox/blob/2dc35528ad58696de32ecb9ed1bddde644c5afd1/pkg/mdformatter/linktransformer/config.go#L134) in mdox as the GitHub API has [rules against](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#user-agent-required) that. I think this might be due to some sort of rate limit like https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits. A solution could be to just ignore docs.github.com links for now.

**Review by bill3tt — APPROVED** [review]
Yikes - I hadn't appreciated that this change would cause CI to break. Thanks @squat 🙌

**Comment by squat** [comment]
Hmm I'm not totally convinced about rate limits. If it were that, then GitHub should return a 429 Too Many Requests. In any case, retrying girl CI job several hours later results in the same errors, making me believe it's really a permissions error and not just a rate limit. We can definitely ignore failed checks for GitHub kinks, even though that's a shame :/

**Comment by saswatamcode** [comment]
I'll try to add a flag to `mdox` to allow showing the actual responses from failed requests. In the meantime maybe docs.github.com links can be ignored?

**Comment by squat** [comment]
Ack, I'll update this PR to ignore those URLs for now

**Comment by squat** [comment]
cc @thanos-io/thanos-maintainers 
Urgent to unblock CI
cc @saswatamcode

**Review by saswatamcode — APPROVED** [review]
Thanks! 🚀

**Pull request merged**
