### PR TITLE
[FIX] Documentation issue #6492

### PR DESCRIPTION
**Pull request by heliapb**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes
Fixes issue https://github.com/thanos-io/thanos/issues/6492
Signed-off-by: Hélia Barroso [helia_barroso@hotmail.com](mailto:helia_barroso@hotmail.com)

### CODE REVIEW

**Review by squat — APPROVED** [review]
Thanks :))

**Comment by heliapb** [comment]
hi @squat got error for the automatic merge so I disable it, could you check again

**Comment by squat** [comment]
@heliapb please sign the DCO so that that check passes (hint: `git commit --amend --signoff`). We can then re-run the other checks to get the PR merge-able.

**Comment by heliapb** [comment]
hi @squat thanks for the feedback, done

**Review by squat — APPROVED** [review]

**Pull request merged**
