### PR TITLE
Objstore: Bump Objstore for Azure Workload Identity support

### PR DESCRIPTION
**Pull request by rikhil-s**
* [x] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Bump `objstore`, adding support for authentication using Azure Workload Identity

## Verification

Testing performed as part of https://github.com/thanos-io/objstore/pull/82

### CODE REVIEW

**Review by MichaHoffmann — APPROVED** [review]
lgtm

**Comment by rikhil-s** [comment]
@yeya24 If you're happy with this, could it be reviewed/merged? Tagging you as you merged the PR in `objstore`.

**Review by yeya24 — COMMENTED** [review]
Can you help update the doc of https://thanos.io/tip/thanos/storage.md/#azure? @rikhil-s 
I think `Azure` client doc is outdated. `msi_resource` is deprecated and we need to mention that workload identity is used when `user_assigned_id` is not set (IIUC)

**Comment by rikhil-s** [comment]
> Can you help update the doc of https://thanos.io/tip/thanos/storage.md/#azure? @rikhil-s I think `Azure` client doc is outdated. `msi_resource` is deprecated and we need to mention that workload identity is used when `user_assigned_id` is not set (IIUC)

Ok, I will update the docs.

**Comment by rikhil-s** [comment]
> Can you help update the doc of https://thanos.io/tip/thanos/storage.md/#azure? @rikhil-s I think `Azure` client doc is outdated. `msi_resource` is deprecated and we need to mention that workload identity is used when `user_assigned_id` is not set (IIUC)

@yeya24 Have now updated the docs.

**Comment by yeya24** [comment]
Umm, I saw the changelog was moved to v0.33 release. Is it intended?
Let's keep it in master.

**Comment by rikhil-s** [comment]
> Umm, I saw the changelog was moved to v0.33 release. Is it intended? Let's keep it in master.

Can this change be in the `0.33` release?

**Comment by MichaHoffmann** [comment]
> > Umm, I saw the changelog was moved to v0.33 release. Is it intended? Let's keep it in master.
> 
> Can this change be in the `0.33` release?

yes ill cherry pick the commit into the 0.33 branch later

**Comment by rikhil-s** [comment]
> > > Umm, I saw the changelog was moved to v0.33 release. Is it intended? Let's keep it in master.
> > 
> > 
> > Can this change be in the `0.33` release?
> 
> yes ill cherry pick the commit into the 0.33 branch later

Ok thanks, I'll move the changelog entry back to the `Unreleased` section in this MR then.

**Review by yeya24 — APPROVED** [review]
Nice. Thanks for updating the doc!

**Pull request merged**
