### PR TITLE
CHANGELOG: Mark v0.32 as in progress

### PR DESCRIPTION
**Pull request by saswatamcode**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Mark `v0.32` as in progress and update `VERSION` on main. 
This is quite a large release so let me know if I've missed any changelog entries!

Waiting on https://github.com/thanos-io/thanos/pull/6582 to be merged for actual rc cc: @GiedriusS 🙂

### CODE REVIEW

**Comment by saswatamcode** [comment]
Docs check fails due to the release link.

**Review by fpetkovski — APPROVED** [review]

**Review by yeya24 — APPROVED** [review]

**Comment by fpetkovski** [comment]
Do we want to update dependencies like objstore and promql-engine?

**Comment by saswatamcode** [comment]
We can as we are waiting for #6582 , should I update both here, or are you waiting for a specific change?

**Comment by fpetkovski** [comment]
I was just thinking we should pull in latest versions from these dependencies. I wanted to make sure we get https://github.com/thanos-io/promql-engine/pull/298 in as well.

**Comment by saswatamcode** [comment]
Sure! Updating here: https://github.com/thanos-io/thanos/pull/6618

**Review by GiedriusS — APPROVED** [review]

**Pull request merged**
