### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by kaynAw**
Signed-off-by: kaynAw <kaynw@qq.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

typo fixed in err message of file `pkg/objstore/s3/s3.go`

### CODE REVIEW

**Review by squat — DISMISSED** [review]

**Comment by squat** [comment]
@kaynAw thanks :)) can you please sign the DCO? (git commit --amend --signoff)

**Comment by kaynAw** [comment]
> @kaynAw thanks :)) can you please sign the DCO? (git commit --amend --signoff)



> @kaynAw thanks :)) can you please sign the DCO? (git commit --amend --signoff)

ok, done :D

**Comment by kaynAw** [comment]
> @kaynAw thanks :)) can you please sign the DCO? (git commit --amend --signoff)

ok, done :D

**Review by squat — APPROVED** [review]

**Review by bwplotka — APPROVED** [review]
Thanks!

**Pull request merged**
