### PR TITLE
cmd/store: fix filtering order

### PR DESCRIPTION
**Pull request by GiedriusS**
We should process the deduplication filter first, before sharding to get better load distribution between different shards. Add a test to cover this case.

### CODE REVIEW

**Comment by bwplotka** [comment]
Hm, what is causing worse distribution? I guess the current situation (without you PR) is that dedup might not be working correctly - as is certain stores might still show and present old blocks (replaced already by other blocks that should force dedup). This is handled fine at the runtime dedup, but maybe not very efficient. 

However, the opposite situation (your PR) where dedup is first, then sharding is blocking cases when somebody would put relabel (sharding is just relabel at the end) to e.g. change deduplication logic (e.g they messed up labels). It also forces dedup to be more expensive and might not scale to the number of objects in the bucket... At least time limiting has to go first 🤔

**Comment by GiedriusS** [comment]
> Hm, what is causing worse distribution? I guess the current situation (without you PR) is that dedup might not be working correctly - as is certain stores might still show and present old blocks (replaced already by other blocks that should force dedup). This is handled fine at the runtime dedup, but maybe not very efficient.
> 
> However, the opposite situation (your PR) where dedup is first, then sharding is blocking cases when somebody would put relabel (sharding is just relabel at the end) to e.g. change deduplication logic (e.g they messed up labels). It also forces dedup to be more expensive and might not scale to the number of objects in the bucket... At least time limiting has to go first thinking

Yes, exactly, _a lot_ of data is downloaded just to be discarded later on. I agree about time limiting but disagree about your other point. Not sure if the use case of "let's relabel labels just to make the deduplication filter work" seems realistic. Deduplication only matters during compaction and old, uncompacted blocks are deleted very quickly.

**Comment by bwplotka** [comment]
Ok, what about deduplication being a bottleneck now for every sync for extremely large buckets where users would like to limit store to touch only blocks with certain label? 

It seems like ONLY hashmod blockID is affecting deduplication - as it would be nice to have deduplicate agnostic hashmod block ID instead of this change? 🤔

**Comment by bwplotka** [comment]
I feel this could be regression overall for some setup. Ideally we could add perhaps some flags to fine tune maybe label sharding BEFORE dedup and AFTER. Happy to merge this for now and see if there are actual perf issues of sync (not very hot path)

**Review by bwplotka — APPROVED** [review]
See my comments above as to be cautious with this change.

**Comment by fpetkovski** [comment]
So I would start off by saying that I do not recommend block sharding in store gateways since it break so many things. This is obviously one of them, but downsampling is also unusable since we need to fetch 3 times more blocks. I also think it is just inefficient a concept because series now get scattered in different stores and they need to get stitched together in queriers.

> Yes, exactly, a lot of data is downloaded just to be discarded later on

I am not entirely sure about this, each store needs to download each `meta.json` file in order to apply partitioning filters. So I don't think moving deduplication at the beginning would change anything in terms of bandwidth. 

I also see the point about deduplicating blocks at download time being more expensive now. We keep data for more than a year but only serve it for the last few months. So by moving this filter at the beginning we would apply block dedup to blocks which are not even served to users. 

But, I don't really know how impactful this change is and I am okay with with trying it out in production. I will report back if I see a significant performance regression.

**Review by fpetkovski — APPROVED** [review]

**Pull request closed without merging**
