### PR TITLE
layouts: small fixes to website index

### PR DESCRIPTION
**Pull request by squat**
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

* [x] Change is not relevant to the end user.

## Changes

Small grammar fixes to the website landing page.

### CODE REVIEW

**Review by thisisobate — APPROVED** [review]
LGTM!!

**Review by kakkoyun — APPROVED** [review]
LGTM. Needs a rebase before we merge.

**Comment by squat** [comment]
ack rebased :)

**Review by GiedriusS — APPROVED** [review]
Thank you!

**Pull request merged**
