### PR TITLE
Use `e2edb.NewMinio` to disable SSE-S3 in e2e tests

### PR DESCRIPTION
**Pull request by saswatamcode**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Seems like our minio-based e2e tests are failing recently due to https://play.min.io/ being unavailable. It is used as a KMS to enable [minio SSE-S3](https://min.io/docs/minio/linux/administration/server-side-encryption/server-side-encryption-sse-s3.html#minio-encryption-sse-s3-quickstart), but it is not actively used in any e2e test.

This PR switches to efficientgo/e2e's `e2edb.NewMinio` instead, which has SSE-S3 disabled by default and does not create a dependency on https://play.min.io/.

Added that functionality upstream: https://github.com/efficientgo/e2e/pull/62

## Verification

Tested locally.

### CODE REVIEW

**Comment by yeya24** [comment]
Is this good to go?

**Comment by saswatamcode** [comment]
Yup this is, just need to remove fork after efficientgo PR is merged: https://github.com/efficientgo/e2e/pull/62 🙂

**Comment by danielmellado** [comment]
lgtm! Let's get https://github.com/efficientgo/e2e/pull/62 merged first. It might be worth adding a note to the PR description mentioning that it depends on that.

**Review by matej-g — APPROVED** [review]
Pending green CI looks good 👍 , thanks @saswatamcode!

**Pull request merged**
