### PR TITLE
Ignore GCS in CI

### PR DESCRIPTION
**Pull request by squat**
We got booted from the GCS account, so skip this in CI for now.

Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

cc @thanos-io/thanos-maintainers

### CODE REVIEW

**Comment by bwplotka** [comment]
Can we just change Makefile in this pr? (:

**Comment by squat** [comment]
-_______- messed it up

**Comment by brancz** [comment]
Let's work with the CNCF to get a GCS account for these tests, I think this is really important.

**Comment by bwplotka** [comment]
We have already account, and all of us has permissions to set it up. Also, there is a ticket for this: https://github.com/thanos-io/thanos/issues/2367

**Pull request merged**
