### PR TITLE
Factor out the index cache implementation, add ristretto

### PR DESCRIPTION
**Pull request by GiedriusS**
SimpleLRU is a nice and simple algorithm for storing items in a cache. However, it is not the most efficient and it doesn't work well in our use-case under high-pressure situations since users tend to execute ad-hoc queries and, in addition, refresh Grafana dashboards quite often which leads to the same items being loaded over and over again.

I have factored out the index cache implementation into another file. This lets us change it to another one on a whim. In addition, I have added an implementation which uses the `ristretto` library, which uses TinyLFU underneath - a relatively new algorithm which espouses very good surprising performance (see the benchmarks here: https://github.com/dgraph-io/ristretto).

This current implementation kind of works.

Verification: `go test -v`.

### CODE REVIEW

**Comment by bwplotka** [comment]
Nice! I did not look at this much, but definitely huge area for improvments here. Can we think of / run some benchmarks to assess if this change is valuable? It makes sense in theory (:

**Comment by GiedriusS** [comment]
Yes, I will rework this into making it a (hidden) option and will make some automatic benchmarks, just like with the other ones that we have already.

**Comment by bwplotka** [comment]
@GiedriusS have you seen? https://blog.dgraph.io/post/caching-in-go/

**Comment by GiedriusS** [comment]
I haven't seen that article but I am aware of TinyLFU. It seems to me that it is the new best LRU cache policy. I started this PR with 2Q since there is a mature implementation of it. On the other hand, I have only seen one experimental implementation of it in Go however it lacks some very important features that are mentioned in that article as well. So I guess we should wait until they will implement it or I will try it if I will have the time. Or maybe someone else wants to do that (:

**Comment by GiedriusS** [comment]
https://github.com/dgraph-io/ristretto seems like that new library is here :) hopefully the implementation will come soon

**Comment by GiedriusS** [comment]
The library has been finally implemented so now we could resume the work on this! :tada:

**Comment by GiedriusS** [comment]
@bwplotka do you think we should make this configurable? Myself I would lean towards a one time switch since the performance should be miles ahead with this library :smiley:

**Comment by GiedriusS** [comment]
Unfortunately but ristretto has some problems:
* Potential collisions between keys
* Memory leaks https://github.com/dgraph-io/ristretto/issues/96

**Comment by karlmcguire** [comment]
@GiedriusS Collision checking [is being finalized](https://github.com/dgraph-io/ristretto/pull/98). We're investigating the memory leak issue; however, it appears to only occur under rare circumstances. Thanks for checking out Ristretto!

**Comment by GiedriusS** [comment]
@bwplotka how do you think the performance of this could be tested? WDYT about the PR in general?

**Comment by GiedriusS** [comment]
Indeed this is not relevant anymore since these things should probably be pushed to some outer provider like `memcached` which could have a flexible control of the admission policy

**Pull request closed without merging**
