### PR TITLE
MAINTAINERS.md: Update my company association

### PR DESCRIPTION
**Pull request by brancz**
Signed-off-by: Frederic Branczyk <fbranczyk@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

@thanos-io/thanos-maintainers

### CODE REVIEW

**Review by kakkoyun — APPROVED** [review]
💯 LGTM

**Review by yeya24 — APPROVED** [review]
LGTM

**Review by bwplotka — APPROVED** [review]

**Review by prmsrswt — COMMENTED** [review]
:rocket:

**Pull request merged**
