### PR TITLE
chore: Vendor Cortex dependency as an internal package

### PR DESCRIPTION
**Pull request by kakkoyun**
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

Introducing a cyclic dependency between Cortex and Thanos was not a good idea. It makes it really hard to upgrade dependencies for Thanos and Cortex (i.e. Prometheus). This solution is not the ideal one. It would be great to extract out `Query Frontend` packages from Cortex but as far as I can tell, it won't be easy. So ideally we should have our own.

Vendored version is the tip of the main as of 15.07.2022

Fixes https://github.com/thanos-io/thanos/issues/3832
Blocked by https://github.com/thanos-io/thanos/pull/5484
Related https://github.com/thanos-io/thanos/pull/5254

## Changes

* Vendor Cortex dependency as an internal package

## To Do

* [x] Rebase after Prometheus upgrade
* [x] Run formatter
* [x] Make sure linter is happy
* [x] Add licence headers to the vendored packages

## Verification

* `make build`
* `make test`

### CODE REVIEW

**Review by bwplotka — DISMISSED** [review]
Thanks a lot. It's ugly solution, but the best we have now! Will unblock us in short term.

Would be keen on merging. Lgtm!

**Review by pracucci — APPROVED** [review]
I agree this cycle dependency has always been a pain.

**Comment by squat** [comment]
haha wow according to sonatype we could contribute a lot of small enhancements to the cortex code :)

**Comment by kakkoyun** [comment]
@sonatype-lift ignoreall

**Comment by kakkoyun** [comment]
The CodeQL errors from the vendored packages will be ignored. I have added the necessary configuration. Yet the failure is there from previous runs.

**Review by douglascamata — APPROVED** [review]
LGTM :)

**Comment by alvinlin123** [comment]
> I agree this cycle dependency has always been a pain.

me too :)

**Pull request merged**
