### PR TITLE
UI: Fix react UI bug with series going on and off

### PR DESCRIPTION
**Pull request by Namanl2001**
Signed-off-by: Namanl2001 <namanlakhwani@gmail.com>

Fixes a subissue `Fix react UI bug with series going on and off` in #3541.

### CODE REVIEW

**Review by prmsrswt — APPROVED** [review]
The E2E test seems unrelated. LGTM, thanks!

**Comment by squat** [comment]
Thanks for this PR :) @Namanl2001 would you mind rebasing? With that done, we could merge

**Comment by Namanl2001** [comment]
@squat @prmsrswt I think if there is no problem in my this PR [#3729] (https://github.com/thanos-io/thanos/pull/3729) then it should be merged first. Otherwise after rebasing & merging of this PR I would have to rebase that PR too.

**Comment by squat** [comment]
@Namanl2001 This PR's pkg/ui/bindata.go is conflicting with master. You will need to rebase on top of master and then re-generate the bindata before we can merge the changes.

**Comment by Namanl2001** [comment]
Resolved all conflicts. Ready to Merge. Thanks

**Comment by onprem** [comment]
Ah sorry, looks like we still managed to get a conflict after all this. Can you rebase this once again, please?

**Review by onprem — DISMISSED** [review]

**Comment by Namanl2001** [comment]
> 
> 
> Ah sorry, looks like we still managed to get a conflict after all this. Can you rebase this once again, please?

Rebased this PR 3rd time. Let's see if it can be merged this time 😄 . @onprem

**Review by onprem — APPROVED** [review]
Let's do this!

**Pull request merged**
