### PR TITLE
docs - Update kms encryption context guidance

### PR DESCRIPTION
**Pull request by avestuk**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Updated documentation for S3 SSE-KMS, after reporting them in https://github.com/thanos-io/thanos/issues/4245 - the change serves to avoid anybody having these issues in the future. 
## Verification

I ran make check-docs and the second commit contains the changes that the automation made that were not directly related to my change.

### CODE REVIEW

**Comment by avestuk** [comment]
I'm unsure as to whether I should add a changelog entry for this

**Comment by avestuk** [comment]
https://github.com/thanos-io/thanos/pull/5089 would remove the need for this PR.

**Comment by wiardvanrij** [comment]
@avestuk  - As per your comment, can this be closed? :)

**Comment by avestuk** [comment]
@wiardvanrij Sorry I completely forgot about this. Yes it can be closed and I'll do so now!

**Pull request closed without merging**
