### PR TITLE
Cut 0.23.0-rc.1 and cherry picked 3 critical commits from main.

### PR DESCRIPTION
**Pull request by bwplotka**
Things I cherry picked:

* Query: Fix (*exemplarsStream).receive/(*metricMetadataStream).receive/(*targetsStreamStream).receive infinite loop when target response Unimplemented error (#4676) (#4681)
* pgrade Prometheus dependency version to v2.30.0 (#4669)
* Sidecar: Fix process external label on promethues v2.28+ use units.Bytes config type (#4657)
    
 
Also, let's make sure we merge this PR without squash.

Let's not try to add too many things in this release, we already waited long.

### CODE REVIEW

**Review by GiedriusS — APPROVED** [review]

**Review by matej-g — APPROVED** [review]

**Review by onprem — APPROVED** [review]
LGTM!

**Review by kakkoyun — APPROVED** [review]

**Comment by hanjm** [comment]
#4680 add `exemplar.partial-response` flag also critical for compatible with old version sidecar. if thanos-query query exemplar a old version sidecar which without exemplar api, it will response fail.

**Comment by bwplotka** [comment]
@hanjm It's just a flag addition, so I did not have enough context to merge this one... We can't postpone release forever, can we release without it, since mitigation is known and exemplars are not core functionality?

**Comment by hanjm** [comment]
> @hanjm It's just a flag addition, so I did not have enough context to merge this one... We can't postpone release forever, can we release without it, since mitigation is known and exemplars are not core functionality?

@bwplotka  more context is:  if without this flag. the exemplar-partial-response is always false. exemplar will response fail if many sidecar has one old version. https://github.com/thanos-io/thanos/blob/ef03a32276e12b760ae9a9b2442be1b0095346a3/pkg/api/query/v1.go#L802

i just upgrade from 0.22 to 0.23.0 and the useful exemplar api break，then i fixed :) ，since exemplar is not core function it will be ok to release.

**Comment by bwplotka** [comment]
Yes, especially for power users like you and @yeya24 using `main` is the best choice (we do that too 🤗 )

**Comment by John-Lin** [comment]
Hi, team 

I'm facing this errors after upgrade to v0.23.0 however I didn't use exemplar feature. As far as I know, it should not show error like this (I have no idea how to reproduce. I guess grafana enable exemplar feature by default cause this error)

```
level=error ts=2021-10-01T01:48:19.727416223Z caller=proxy.go:146 err="receiving exemplars from exemplars client &{0xc0162da000}: rpc error: code = Canceled desc = context canceled"
level=error ts=2021-10-01T01:48:23.383270697Z caller=proxy.go:146 err="fetching exemplars from exemplars client &{0xc0162da000}: rpc error: code = Canceled desc = context canceled"
level=error ts=2021-10-01T01:48:23.525155169Z caller=proxy.go:146 err="receiving exemplars from exemplars client &{0xc0000a4700}: rpc error: code = Canceled desc = context canceled"
level=error ts=2021-10-01T01:48:25.387262601Z caller=proxy.go:146 err="fetching exemplars from exemplars client &{0xc0162da000}: rpc error: code = Canceled desc = context canceled"
```
then I found these PRs #4680, #4681 might related. my question is will #4680, #4681 be merged in next release?
it seems like those PRs could fix this issue.

**Pull request merged**
