### PR TITLE
e2e: Add memcached as cache in store-gateway test

### PR DESCRIPTION
**Pull request by akanshat**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes
- Extended newStoreGW services to accept caching bucket config.
- Added Memcached in Store Gateway e2e test.
- Added a separate test for Store Gateway with Memcached.

## Verification
The tests passed after the changes.

### CODE REVIEW

**Review by GiedriusS — DISMISSED** [review]
:muscle: awesome! I guess we can remove `// TODO(bwplotka): Extend this test to have multiple stores and memcached.` now?

**Comment by akanshat** [comment]
> 💪 awesome! I guess we can remove `// TODO(bwplotka): Extend this test to have multiple stores and memcached.` now?

Done!

**Review by GiedriusS — APPROVED** [review]
Great work! :tada:

**Comment by akanshat** [comment]
Thank you!

**Pull request merged**
