### PR TITLE
Bump Prometheus to include new label regex optimization

### PR DESCRIPTION
**Pull request by yeya24**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Update Prometheus version to latest main to include https://github.com/prometheus/prometheus/pull/13461.

### CODE REVIEW

**Comment by yeya24** [comment]
This requires upgrading thanos promql engine first.

**Comment by yeya24** [comment]
Promql engine update done. Updated this pr.

**Comment by yeya24** [comment]
```
=== NAME  TestQueryFrontendExplain
    query_frontend_test.go:1170: 
        	Error Trace:	/home/runner/work/thanos/thanos/test/e2e/query_frontend_test.go:1170
        	Error:      	Not equal: 
        	            	expected: "{\"status\":\"success\",\"data\":{\"name\":\"[noArgFunction] time()\"}}"
        	            	actual  : "{\"status\":\"success\",\"data\":{\"name\":\"[duplicateLabelCheck]\",\"children\":[{\"name\":\"[noArgFunction]\"}]}}"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-{"status":"success","data":{"name":"[noArgFunction] time()"}}
        	            	+{"status":"success","data":{"name":"[duplicateLabelCheck]","children":[{"name":"[noArgFunction]"}]}}
        	Test:       	TestQueryFrontendExplain
```

This test failed. @GiedriusS Can you please help me figure out how I can fix it

**Comment by fpetkovski** [comment]
Looks like a feature that was added by @mhoffm-aiven to detect duplicate series from each operator output. I think it is safe to change the expected result unless we want to hide this from analysis.

**Comment by fpetkovski** [comment]
Looks like we cannot create OOO chunks in TSDB anymore.

**Comment by yeya24** [comment]
@fpetkovski PTAL again

**Review by fpetkovski — APPROVED** [review]
Nice work

**Pull request merged**
