### PR TITLE
Make hyperlinks work

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: clyang82 <chuyang@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

### CODE REVIEW

**Review by bwplotka — COMMENTED** [review]
This is by design, like this and it's done by our automation. IF some links does not work, it should be fixed within automation project. What is not working? From GH or from website?

cc @saswatamcode

**Comment by saswatamcode** [comment]
I think these links (plus any non-markdown resource links) are broken on the website but fine on GH. An automatic [solution](https://github.com/bwplotka/mdox/pull/76) for this was already implemented in mdox but the config wasn't updated here. 

It just involves adding the line below to [`.mdox.yaml`](https://github.com/thanos-io/thanos/blob/main/.mdox.yaml),
```yaml
linkPrefixForNonMarkdownResources: "https://github.com/thanos-io/thanos/blob/main"
```

Maybe it can be updated in this PR?  🙂  
@bwplotka @clyang82

**Comment by clyang82** [comment]
Thanks @bwplotka @saswatamcode for your comments.  Good to know we have automatic solution for this. Let me use this PR to update `.mdox.yaml`.

**Review by saswatamcode — APPROVED** [review]
Thank you! All the links that were broken seem to be fixed now! 💫

**Review by yeya24 — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
