### PR TITLE
UI: add dark theme

### LINKED ISSUE #3775: Implement a dark theme in UI
### Is your proposal related to a problem?

Similar to https://github.com/prometheus/prometheus/issues/7735
It would be great to have a dark theme toggle in Thanos. (This is coming from SREs who use the Thanos UI to do digging more frequently than Grafana Explore tab)

A common use case is that we would take screenshots and post them in slack during the day.

### Describe the solution you'd like

A dark mode toggle would be great, and make screenshots have less contrast when shared via Slack (in dark mode)

### Describe alternatives you've considered

We use Grafana explore tab from time to time, but the experience is not as good comparing to Prometheus based UI.

### Additional context

I am a monitoring SRE and often presents to team members who are new with Prometheus/Thanos/Grafana. 
Slack/Grafana/Slides already supports dark mode, so it is the most jarring when switching to the Prometheus UI.

Once we get used to it, it's not so bad. But it would make for better new comer UX if we have it!

Thanks

### PR DESCRIPTION
**Pull request by Aman-Codes**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Added dark theme
Closes #3775 

### Homepage
darkHomepage

lightHomepage

### Status page
darkStatus

lightStatus

### Store page
darkStore

lightStore

## Verification

```sh
cd pkg/ui/react-app/
yarn start
```

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
OMG we need this. 

Thanks! It looks good on outside, but we need @onprem blessing here 🙈

**Comment by roidelapluie** [comment]
This pull request seems to copy/paste code from Prometheus without the attribution required by the Apache-2 License.

**Comment by Aman-Codes** [comment]
> This pull request seems to copy/paste code from Prometheus without the attribution required by the Apache-2 License.

@roidelapluie  To maintain consistency in Thanos and Prometheus UI, I reused the Prometheus dark theme code. 
I have now added the License attribution. Let me know if anything more is required.

**Review by onprem — APPROVED** [review]
LGTM, Thanks!

**Review by kakkoyun — DISMISSED** [review]
LGTM 🚀 

Noob question: Is there a way to directly import the theme from Prometheus rather than copying over the code? It'll be hard to keep it in sync?

**Comment by onprem** [comment]
> Is there a way to directly import the theme from Prometheus rather than copying over the code? It'll be hard to keep it in sync?

Currently, no. We have to publish relevant bits on npm to do that.

**Comment by Aman-Codes** [comment]
I only fixed the merged conflict. The dismissed stale reviews is due to [saacs/github#1157](https://github.com/isaacs/github/issues/1157)

**Review by kakkoyun — APPROVED** [review]

**Pull request merged**
