### PR TITLE
Fix for mixin workflow actions rules check step failed cases

### PR DESCRIPTION
**Pull request by Preethivika**
* [x] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Issue
https://github.com/thanos-io/thanos/actions/runs/6308719737/job/17127340425#step:5:169
Mixin workflow in action is being failed internally all the time, because of the duplicate query names found in the rules.yaml

```
Checking examples/alerts/rules.yaml
  FAILED:
lint error 2 duplicate rule(s) found.
Metric: :grpc_server_failures_per_stream:sum_rate
Label(s):
Metric: :grpc_server_failures_per_unary:sum_rate
Label(s):
Might cause inconsistency while recording expressions

```
## Changes

Modified the receive and store rules with the added prefixes thanos_query_store & thanos_query_receive to differentiate the rules.

## Verification

Verified the mixin actions and it is working now without showing any failed statements.

```
Checking examples/alerts/rules.yaml
  SUCCESS: 16 rules found

```

### CODE REVIEW

**Comment by Preethivika** [comment]
@saswatamcode - Can you please review this PR. Thanks in advance.

**Review by saswatamcode — DISMISSED** [review]
Thanks @Preethivika! Could you add a changelog entry for this, with a `:warning:` label, as this might be a breaking change for dashboards. 🙂 

Also, while we're at it, maybe let's upgrade `promtool` to latest. You can do this by installing https://github.com/bwplotka/bingo and running `bingo get github.com/prometheus/prometheus/cmd/promtool@latest` and committing the result.

**Comment by Preethivika** [comment]
Hi @saswatamcode , Thank you for reviewing. I added the changelog for the mixin workflow fix. 
And also upgraded the **promtool** version to latest. Please review and let me know if something needs to be modified.

**Review by saswatamcode — APPROVED** [review]
LGTM!

**Pull request merged**
