### PR TITLE
go.mod: Bump Prometheus to current latest

### PR DESCRIPTION
**Pull request by brancz**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Bump TSDB.

## Verification

Tests.

@thanos-io/thanos-maintainers

### CODE REVIEW

**Comment by GiedriusS** [comment]
Does this contain some important fixes for our users?

**Comment by brancz** [comment]
Mainly performance improvements, without running it ourselves we don't know how significant those are though. We run latest Thanos in prod all the time, so we want to just get into the habit of bumping TSDB more often so we avoid making big jumps.

**Comment by brancz** [comment]
Oh and it includes https://github.com/prometheus/prometheus/pull/7472 which allows moving forward with https://github.com/thanos-io/thanos/blob/master/docs/proposals/202005_scalable-rule-storage.md

**Comment by bwplotka** [comment]
Looks like a valid test failure @brancz 

It's because in tests we are using label values which are not sorted now, we should use SortedLabelValues instead :hugs: 

Worth to check our TSDB method we use in StoreAPI for TSDB impl, we probably need to sort to be compliant. (if we want)

**Comment by brancz** [comment]
I'm not sure what the consequence of this is, I haven't followed those changes very closely on TSDB. From what I can tell sorted LabelValues is not exposed on the storage interfaces though so I'm not sure how to call them explicitly. Suggestions?

**Comment by brancz** [comment]
Couldn't figure out how to re-run netlify jobs, so re-triggered by amending last commit.

**Comment by bwplotka** [comment]
We can ignore netlify, they have some incident

**Pull request merged**
