### PR TITLE
CHANGELOG: Mark 0.35 as in progress

### PR DESCRIPTION
**Pull request by saswatamcode**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

### CODE REVIEW

**Review by MichaHoffmann — APPROVED** [review]
lgtm

**Comment by fpetkovski** [comment]
Do we want to get https://github.com/thanos-io/thanos/pull/7310 and some other PRs in?

**Comment by saswatamcode** [comment]
The release has been pending for a bit now, but we can wait for a couple more PRs

**Comment by fpetkovski** [comment]
I would like to add label names and values sharding as a follow up to https://github.com/thanos-io/thanos/pull/7200. I can raise a PR today for that.

**Comment by fpetkovski** [comment]
Looks like @MichaHoffmann already did this in https://github.com/thanos-io/thanos/pull/7309/files. So maybe we can just merge the draft PR about removing replica labels and then we'll be good to go.

**Comment by saswatamcode** [comment]
Ok those have been merged, so marking as in-progress

**Pull request merged**
