### PR TITLE
Docs: Remove link to a deleted resource from mixin docs

### PR DESCRIPTION
**Pull request by matej-g**
Signed-off-by: Matej Gera <matejgera@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [X] Change is not relevant to the end user.

## Changes

Deleting link to mixin design doc (https://docs.google.com/document/d/1A9xvzwqnFVSOZ5fD3blKODXfsat5fg6ZhnKu9LK3lB4/edit#) which apparently does not exist anymore and causes the doc check to fail.

## Verification

Local run of `make check-docs`

### CODE REVIEW

**Review by GiedriusS — APPROVED** [review]
Pity that the doc has been deleted for some reason :/ thanks for this! I was about to open up a PR for fixing this :smile:

**Comment by matej-g** [comment]
> Pity that the doc has been deleted for some reason :/ thanks for this! I was about to open up a PR for fixing this smile

Yeah, I quickly looked around if it has been moved, but no luck. Perhaps if we could reach @tomwilkie who seem to be the author (guessing from https://groups.google.com/g/prometheus-developers/c/ADgiqnaT1wo/m/BEY9sZfbAQAJ) maybe we could get an alternative link.

**Comment by tomwilkie** [comment]
Sorry about that, I don't know what happened there! Heres a PDF we cached a while back: https://github.com/monitoring-mixins/docs/blob/master/design.pdf, but I think that doc was written under the Kausal google account, which is long gone now.

**Comment by matej-g** [comment]
Awesome, thanks for providing the link @tomwilkie!

**Pull request merged**
