### PR TITLE
Build with Go 1.18

### PR DESCRIPTION
**Pull request by sylr**
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

- Upgrade to Go 1.18
- Upgrade golangci-lint to v1.45.2
- Upgrade go orb version in circleci config
- Upgrade docker version in circleci config

### CODE REVIEW

**Comment by GiedriusS** [comment]
CI failures seem related? :thinking:

**Comment by sylr** [comment]
@GiedriusS could you relaunch the CI to see if errors persist?

**Comment by GiedriusS** [comment]
Still the same after 2 more runs. This is some weird message :thinking: needs investigation.

**Comment by sylr** [comment]
If anyone wants to take over, be my guest.

**Comment by sylr** [comment]
@bwplotka I believe the problem in the tests is that the prometheus server used in the test use json-iterator/reflect2 versions that do not work with go1.18.

I tried to upgrade them with bingo but go nowhere. Could you take a look ?

**Comment by sylr** [comment]
All right I got it, everything is green 🎉

**Review by GiedriusS — APPROVED** [review]

**Pull request merged**
