### PR TITLE
Add Cartrade tech logo to adopters

### PR DESCRIPTION
**Pull request by naveadkazi**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Added CarTrade tech to the adopter list

## Verification

Followed the process defined [here](https://thanos.io/tip/contributing/how-to-contribute-to-docs.md/#adopters-logos)

### CODE REVIEW

**Comment by saswatamcode** [comment]
Thanks a lot! Could you please sign the commit with `git commit -s`? 🙂

**Comment by naveadkazi** [comment]
Thanks for the reply. Was not sure if sign-off was required for the adopter's commits too. Have amended the commit with sign off

**Review by GiedriusS — DISMISSED** [review]

**Comment by fpetkovski** [comment]
Looks like DCO verification is still failing in the CI.

**Comment by naveadkazi** [comment]
@fpetkovski DCO is succesful now

**Comment by fpetkovski** [comment]
@naveadkazi sorry I had to rebase against main through the UI and Github decided to force-push a new commit :/

**Comment by naveadkazi** [comment]
@fpetkovski should I force push again with new signed comments?

**Comment by fpetkovski** [comment]
I think that would be the simplest way to resolve this. Sorry for the hassle.

**Pull request closed without merging**
