### PR TITLE
*: Cut 0.25.0-rc.0

### PR DESCRIPTION
**Pull request by matej-g**
Signed-off-by: Matej Gera <matejgera@gmail.com>

## Changes

Cutting `0.25.0-rc.0`. Added some missing changes, formatting and also moved #4818 to `0.25.0` since it looks like it was accidentally added to `0.24.0` section, although it has not been release yet. 

## Verification

-

### CODE REVIEW

**Comment by GiedriusS** [comment]
Could we add this https://github.com/thanos-io/thanos/pull/5185 to the RC? :thinking:

**Comment by matej-g** [comment]
> Could we add this #5185 to the RC? thinking

Sure thing, I guess it does not really need a CHANGELOG change. Let's get it into `main` and I'll update the `release-0.25` branch to have it included in this RC.

**Comment by hanjm** [comment]
Could we add this #5166  to the RC? 🤣 as it is the continue of #5139.

**Comment by matej-g** [comment]
> Could we add this #5166 to the RC? rofl as it is the continue of #5139.

Sure, then let's try to get this quickly in :+1: and I'll update the release branch with both changes.

**Review by GiedriusS — APPROVED** [review]

**Review by bwplotka — APPROVED** [review]
Amazing, thanks! 💪🏽

**Comment by bwplotka** [comment]
Did you  update the commit with https://github.com/thanos-io/thanos/pull/5166 ? We can do this in various ways:

* Re-push release-0.25 branch from commit on top of #5166 and make sure we put in change log anything else that landed in mean time
* Cherry-pick https://github.com/thanos-io/thanos/pull/5166 commit to release-0.25 and update changelog here (: Probably safer thing.

**Comment by matej-g** [comment]
Hey @bwplotka,
I have already updated `release-0.25` to include changes from latest `main` - I checked, and besides https://github.com/thanos-io/thanos/pull/5185 and #5166 which we wanted to get in, there are no other user-facing changes.

**Review by bwplotka — APPROVED** [review]
Let's go!

**Pull request merged**
