### PR TITLE
changed grpc.ServerOption order to catch panic

### PR DESCRIPTION
**Pull request by Wander1024**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Verification

due to panic and recover atribute
we met the issue as #4080

### CODE REVIEW

**Comment by yashrsharma44** [comment]
Can you rebase and then push the your branch? Seems like there are some conflicting files

**Comment by Wander1024** [comment]
ok. will do it.

**Comment by Wander1024** [comment]
already fixed conflicts.

**Comment by yashrsharma44** [comment]
Can you sign the DCO? More Info - [link](https://github.com/thanos-io/thanos/blob/main/CONTRIBUTING.md#pull-request-process)

**Comment by yashrsharma44** [comment]
Seems like email associated with this github ID is wrong - 
```
Commit sha: 87e8626, Author: yaohua.wang, Committer: yaohua.wang; Expected "yaohua.wang yaohua.wang@shopee.com", but got "yaohua.wang yawhua1024@gmail.com".
``` - [link](https://github.com/thanos-io/thanos/pull/4087/checks?check_run_id=2397709038)

**Comment by kakkoyun** [comment]
Thanks for fixing the issues 👍 Let's fix the CI issues and have this in the upcoming release candidate (today).

**Comment by Wander1024** [comment]
Hi,can see this pr #4088 .this PR commit I used company info it's bad.

**Pull request closed without merging**
