### PR TITLE
upgrade Prometheus dependency version to v2.30.0

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <ben.ye@bytedance.com>

Fixes https://github.com/thanos-io/thanos/issues/4665

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Upgrade Prometheus version to the latest v2.30.0.
This brings in https://github.com/prometheus/prometheus/pull/9097 and some improvements on TSDB as well.

### CODE REVIEW

**Comment by GiedriusS** [comment]
Seems like the CI failure is related to your changes. Could you please take a look?

**Review by matej-g — COMMENTED** [review]
Looks like the test fail is legit, seems like it's coming from this change in Prometheus https://github.com/prometheus/prometheus/pull/9301

**Comment by yeya24** [comment]
> Looks like the test fail is legit, seems like it's coming from this change in Prometheus [prometheus/prometheus#9301](https://github.com/prometheus/prometheus/pull/9301)

Thanks. But why https://github.com/prometheus/prometheus/pull/9301 is related to the TOC offset change? IIUC 9301 is about TSDB head which is only related to memory?

**Comment by matej-g** [comment]
> Thanks. But why [prometheus/prometheus#9301](https://github.com/prometheus/prometheus/pull/9301) is related to the symbols offset change? IIUC 9301 is about TSDB head which is only related to memory?

I think we are using some of the code that has been touched in that PR in the [utility](https://github.com/thanos-io/thanos/blob/main/pkg/testutil/e2eutil/prometheus.go#L419) to create blocks (seems like it's within [leveled compactor](https://github.com/thanos-io/thanos/blob/main/pkg/testutil/e2eutil/prometheus.go#L483)). The specific cause seems to be [this change](https://github.com/prometheus/prometheus/pull/9301/files#diff-73c4d729472ae77b03b5d3a6d05f6a924eb1a53d5f248ae11194e8c8cd2ed284).

**Comment by yeya24** [comment]
Is it ready to go? @GiedriusS @matej-g

**Review by matej-g — APPROVED** [review]
From my side ready to go 🚀

**Pull request merged**
