### PR TITLE
Github link to v0.25.2

### PR DESCRIPTION
**Pull request by Vishvsalvi**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Changed the link of v0.25.2 that was directing to v.0.25 Github repository rather than v0.25.2

## Verification

Cross checked the link and it successfully redirected to v0.25.2 repository

### CODE REVIEW

**Review by yeya24 — COMMENTED** [review]
I think what we usually do is to link to the release branch rather than the specific tag.

**Comment by Vishvsalvi** [comment]
> 

The issue was open to the replace link of release branch to specific tag

**Comment by yeya24** [comment]
Then you need to change all the links rather than only for `v0.25.2`.
We should discuss first whether we wanna do it or not before making the change.

**Comment by Vishvsalvi** [comment]
> Sure, please have the discussion because it doesn't make sense to not direct to a specific tag if there exists a specific link for it

**Review by fpetkovski — APPROVED** [review]
Thanks

**Comment by Vishvsalvi** [comment]
Can I fix the other links as well ?

**Pull request merged**
