### PR TITLE
Enabled Navbar to automatically close on navigation

### PR DESCRIPTION
**Pull request by Vanshikav123**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes
Enabled hamburger menu to automatically close on Navigation to other endpoints in Thanos-query UI

### CODE REVIEW

**Comment by Vanshikav123** [comment]
Please Review

**Review by MichaHoffmann — COMMENTED** [review]
lgtm

**Comment by Vanshikav123** [comment]
Hello @yeya24 can you please approve this PR

**Review by saswatamcode — APPROVED** [review]
LGTM!

**Pull request merged**
