### PR TITLE
Arranged #Retrospective section In a proper line

### PR DESCRIPTION
**Pull request by Anosh21**
## Changes
- Added Spacing
- Made Content Readable.
- Made Doc Consice and Clear.

### CODE REVIEW

**Comment by matej-g** [comment]
Hey @Anosh21 thanks for opening this!

Have you tried running `make check-docs`? All `.md` docs across the repository should be automatically formmated.

**Comment by Anosh21** [comment]
Yes @matej-g , I have run and tested everything.

**Comment by matej-g** [comment]
@Anosh21 is there a specific issue you're trying to address with the formatting? The page looks good to me as it is here https://thanos.io/tip/contributing/mentorship.md/

I think also that CI target for documentation check will fail, since we have an automated script to take care of formatting, removing white space etc., which will conflict with changes you made manually to the doc.

**Comment by Anosh21** [comment]
@matej-g I have made the changes , as earlier try running the test now.

**Comment by matej-g** [comment]
@Anosh21 I think that spacing would be still formatted by our script, meaning this PR won't pass the doc check. Unless there is something wrong with formatting (which does not seem to be from looking at the website), I'd suggest to close this.

**Pull request closed without merging**
