### PR TITLE
Fix Typo in Recieve.md

### PR DESCRIPTION
**Pull request by rajivharlalka**
Signed-off-by: rajivharlalka <rajivharlalka009@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Fix some typos in docs in recieve.md , rest changes belong to linting fixes due to make check-docs.

### CODE REVIEW

**Comment by rajivharlalka** [comment]
Tried fixing the CI , but aint getting the issue. `make docs` locally is clean
```
└─> make docs
all modules verified
>> building Thanos binary in /home/vijard/go/bin
 >   thanos
rm -rf mixin/vendor
cd mixin && /home/vijard/go/bin/jb-v0.5.1 install
GET https://github.com/grafana/jsonnet-libs/archive/4d4b5b1ce01003547a110f93cc86b8b7afb282a6.tar.gz 200
GET https://github.com/grafana/grafonnet-lib/archive/daad85cf3fad3580e58029414630e29956aefe21.tar.gz 200
find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | \
        xargs -n 1 -- /home/vijard/go/bin/jsonnetfmt-v0.18.0 -n 2 --max-blank-lines 2 --string-style s --comment-style s -i
rm -rf examples/dashboards/*.json
/home/vijard/go/bin/jsonnet-v0.18.0 -J mixin/vendor -m examples/dashboards mixin/dashboards.jsonnet
examples/dashboards/bucket-replicate.json
examples/dashboards/compact.json
examples/dashboards/overview.json
examples/dashboards/query-frontend.json
examples/dashboards/query.json
examples/dashboards/receive.json
examples/dashboards/rule.json
examples/dashboards/sidecar.json
examples/dashboards/store.json
rm -rf examples/tmp/
mkdir -p examples/tmp/
/home/vijard/go/bin/jsonnet-v0.18.0 -J mixin/vendor -m examples/tmp/ mixin/separated-alerts.jsonnet | xargs -I{} sh -c 'cat {} | /home/vijard/go/bin/gojsontoyaml-v0.1.0 > {}.yaml; rm -f {}' -- {}
/home/vijard/go/bin/promdoc-v0.8.0 generate  examples/alerts/alerts.yaml -i mixin -o mixin/runbook.md
>> generating docs
PATH="/home/vijard/.yarn/bin:/home/vijard/.config/yarn/global/node_modules/.bin:/usr/share/zsh/scripts/zplug/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/vijard/bin:/usr/java/jdk-15.0.1/bin:/home/vijard/go/bin:/home/vijard/go/bin" /home/vijard/go/bin/mdox-v0.9.1-0.20220713110358-25b9abcf90a0 fmt --links.localize.address-regex="https://thanos.io/.*" docs/governance.md docs/sharding.md docs/tracing.md docs/README.md docs/operating/reverse-proxy.md docs/operating/README.md docs/operating/https.md docs/operating/compactor-backlog.md docs/operating/cross-cluster-tls-communication.md docs/operating/use-cases.md docs/operating/multi-tenancy.md docs/operating/troubleshooting.md docs/operating/modify-objstore-data.md docs/operating/binary-index-header.md docs/proposals-rejected/README.md docs/proposals-rejected/201807-store-instance-high-availability.md docs/proposals-rejected/201807-config.md docs/integrations.md docs/storage.md docs/logging.md docs/proposals-accepted/202108-more-granular-query-performance-metrics.md docs/proposals-accepted/202205-vertical-query-sharding.md docs/proposals-accepted/README.md docs/proposals-accepted/202106-automated-per-endpoint-mTLS.md docs/proposals-accepted/202012-deletions-object-storage.md docs/proposals-accepted/202012-receive-split.md docs/proposals-accepted/202107-protobuf-openapi-httpapi.md docs/proposals-accepted/202206-active-series-limiting-hashring.md docs/proposals-accepted/202101-endpoint-discovery.md docs/design.md docs/service-discovery.md docs/quick-tutorial.md docs/components/query-frontend.md docs/components/README.md docs/components/receive.md docs/components/sidecar.md docs/components/store.md docs/components/compact.md docs/components/tools.md docs/components/rule.md docs/components/query.md docs/proposals-done/202004-embedd-cortex-frontend.md docs/proposals-done/README.md docs/proposals-done/202005-query-logging.md docs/proposals-done/202003-thanos-rules-federation.md docs/proposals-done/201809-gossip-removal.md docs/proposals-done/202106-proposals-process.md docs/proposals-done/202005-scalable-rule-storage.md docs/proposals-done/202005-version-documentation.md docs/proposals-done/201909-thanos-sharding.md docs/proposals-done/201912-thanos-binary-index-header.md docs/proposals-done/202203-grpc-query-api.md docs/proposals-done/201901-read-write-operations-bucket.md docs/proposals-done/201812-thanos-remote-receive.md docs/proposals-done/202001-thanos-query-health-handling.md docs/getting-started.md docs/release-process.md docs/contributing/proposal-process.md docs/contributing/coding-style-guide.md docs/contributing/README.md docs/contributing/community.md docs/contributing/how-to-change-go-version.md docs/contributing/mentorship.md docs/contributing/how-to-contribute-to-docs.md examples/alerts/alerts.md examples/dashboards/dashboards.md mixin/README.md mixin/lib/thanos-grafana-builder/README.md CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md MAINTAINERS.md README.md SECURITY.md
⣯ Formatting: /home/vijard/Documents/projects/thanos/docs/proposals-rejected/201807-store-instance-high-availability.
⣷ Formatting: /home/vijard/Documents/projects/thanos/docs/proposals-accepted/202108-more-granular-query-performance-m
⣾ Formatting: /home/vijard/Documents/projects/thanos/docs/proposals-accepted/202206-active-series-limiting-hashring.m
make white-noise-cleanup
make[1]: Entering directory '/home/vijard/Documents/projects/thanos'
>> cleaning up white noise
make[1]: Leaving directory '/home/vijard/Documents/projects/thanos'
```

but in CI it shows that there are some un commited changes. 


Can anyone please help me out.

**Comment by matej-g** [comment]
Hey @rajivharlalka, looks you made some changes that introduced extra white noise (unnecessary spaces). 

What is your OS? This should work on all systems, but probably good idea to check the command behaves same everywhere. If you run `make docs` locally make sure you don't see any formatting changes in `git`.

**Comment by rajivharlalka** [comment]
Hi @matej-g , I use Arch Linux as my OS. 

After I ran `make docs` , therr were a lot of white space changes, ig the command needs some update. Would try to look at it.

**Comment by matej-g** [comment]
You should actually commit those changes, that's what should take care of removing extra whitespace etc.

**Comment by rajivharlalka** [comment]
I have committed them. My typo fixes were in `recieve.md` mainly, rest changes were through the make docs .

**Pull request closed without merging**
