### PR TITLE
*: merge release-0.28 branch to main

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <ben.ye@bytedance.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

### CODE REVIEW

**Review by GiedriusS — APPROVED** [review]

**Review by GiedriusS — COMMENTED** [review]
Do we need to update `VERSION`?

**Comment by yeya24** [comment]
> Do we need to update `VERSION`?

Thanks. Just updated the version. I think I missed this step when I started cutting the release on main.

**Review by GiedriusS — APPROVED** [review]

**Review by GiedriusS — COMMENTED** [review]
```
cannot 'run make docs and commit changes': you have unstaged changes.
M	docs/release-process.md
```

@yeya24 could you please take a look at what might be the problem? :thinking:

**Comment by yeya24** [comment]
@GiedriusS Can I get another approval?

**Review by GiedriusS — APPROVED** [review]

**Pull request merged**
