### PR TITLE
React-UI: Replace Alert components with UncontrolledAlert

### LINKED ISSUE #3168: Replace Alert components in the react-app with UncontrolledAlert (this makes the Alerts dismissable)
The UncontrolledAlert component has an 'x' button on it which can be used to close the rendered Alert component in the UI.

https://reactstrap.github.io/components/alerts/

### PR DESCRIPTION
**Pull request by daksh-sagar**
Replaces `reactstrap` Alert Component in the react-app with the UncontrolledAlert. This makes the alerts rendered on the UI dismissable, meaning the alerts now have an 'x' button which can be used to close the alerts.

Fixes #3168 

* [ ] I added CHANGELOG entry for this change.
## Changes
Thanos `package/ui/react-app`

Replaced the Alert component with UncontrolledAlert component in all the relevant files
Made relevant changes to the affected tests

## Verification

Ran the `yarn run test` command and all the test suites passed.

@prmsrswt

### CODE REVIEW

**Comment by prmsrswt** [comment]
Everything seems fine, but you need to update the generated assets as well. Run `make assets` locally to update `pkg/ui/bindata.go` file, and then push the changes.

**Comment by daksh-sagar** [comment]
@prmsrswt 

> Everything seems fine, but you need to update the generated assets as well. Run `make assets` locally to update `pkg/ui/bindata.go` file, and then push the changes.

Done !

**Review by prmsrswt — APPROVED** [review]
LGTM! Thanks!

**Review by bwplotka — APPROVED** [review]
Thanks! (:

**Pull request merged**
