### PR TITLE
WIP: Update to prometheus 2.18.0-rc0

### LINKED ISSUE #2531: Proposal: Upgrade vendor'ed Prometheus
Hi everyone 👋,

Loving the work done on Thanos!

In Cortex, we vendor Prometheus through Thanos. Right now, we're in need of a feature that 2.18.0.rc-0 offers. While I understand that upgrading to an RC might be something unfeasible. I'd like to test the waters on what is possible and what is not.

At a glance, I see we're currently on ~v2.15.2. Is upgrading to something like v2.17.2, something that Thanos maintainers see as a possibility?

My thinking here is that although upgrading to an RC might be a bit more cautious. we can start doing some of the work now (by upgrading to 2.17.2) and therefore have a simple upgrade to path when the RC settles.

I'd be happy to do the work as long as it is something desirable. The below list is a very short attempt to document what needs to be done, any help on context already done would be appreciated.

List of changes

- [ ] `tsdb` moved to its own package. No longer part of `storage/tsdb`

### PR DESCRIPTION
**Pull request by gotjosh**
This fixes #2531 

## Changes

So far, the changes are very broad. I'm going to try and group them based on the PR they're based on.

https://github.com/prometheus/prometheus/issues/7029, https://github.com/prometheus/prometheus/pull/7033

-  Removes the `fileutil.ReadDir` function in favour of `ioutil.ReadDir`

https://github.com/prometheus/prometheus/pull/6687

- Introduces a new (optional) `Compact` method on the Chunk interface to optimise unused space. I've copied a similar implementation to what was done in Prometheus but please do let me know if we have other ideas here. 

https://github.com/prometheus/prometheus/pull/6777

- Removal of `tsdb.Appender` interface in favour of `storage.Appender`
- Removal of `BlockRanges` in `tsdb.Options` in favour of min/max
- Removal of `SeriesIterator` in favour of `chunkenc.Iterator`
- The `Querier` method now supports a context
- The `Select` method now supports sorting and hints. Also returns warnings

https://github.com/prometheus/prometheus/pull/6644

- Makes the `stripSize` of tsdb a configurable parameter.

https://github.com/prometheus/prometheus/pull/6744

- Moves `promql/parser` to its own package. 

https://github.com/prometheus/prometheus/pull/6533

- Upgrades the alerting definition/validation via `promtool` to use the v1 of the golang YAML package. 

https://github.com/prometheus/prometheus/pull/6712

- Removes `MaxConcurrent` as a flag from TSDB options. It is now part of the `ActiveQueryTracker`

https://github.com/prometheus/prometheus/pull/6734

- The function `alertingRule.Duration` was duplicated as `alertingRule.HoldDuration`, Prometheus removed the former in preference of the latter.

https://github.com/prometheus/prometheus/pull/6745/

- Introduces a parameter struct/object as the argument for `rules.NewGroup`

## TODO

- [ ] Verify the `Compact` Implementation
- [ ] Figure out the rules breakage
- [ ] I added CHANGELOG entry for this change
- [ ] Understand the impact of `AddFast` method signature change.

## Verification

- TBD

### CODE REVIEW

**Comment by gotjosh** [comment]
I've been using `make test` as the base to investigate failures but seems like there's plenty more I missed (although related to the changes) in `make lint` - I'll pick those up.

**Comment by gotjosh** [comment]
This is stopping us: https://github.com/prometheus/prometheus/issues/7128

**Comment by kakkoyun** [comment]
@gotjosh I believe this PR is deprecated by https://github.com/thanos-io/thanos/pull/2658/
Should we close this? Do we miss anything?

**Comment by gotjosh** [comment]
Absolutely, seems like it has been updated since 👍

**Pull request closed without merging**
