### PR TITLE
add gofmt -s step to makefile and golangci

### PR DESCRIPTION
**Pull request by dvrkps**
Signed-off-by: Davor Kapsa <davor.kapsa@gmail.com>

### CODE REVIEW

**Comment by pracucci** [comment]
> This is nice, but until we change [`Makefile format`](https://github.com/thanos-io/thanos/blob/58458f1b0a652b6ba7f98cd72dbe9272af9c7982/Makefile#L198) command which is run by default, this might be violated in next PR....

As a corollary, we should also enforce it via `golangci-lint`, adding the `gofmt` linter to `.golangci.yml`. What's your take @bwplotka ?

**Comment by bwplotka** [comment]
Definitely!

**Comment by bwplotka** [comment]
Can you help with this @dvrkps ?

**Comment by dvrkps** [comment]
Sure, i will try.

**Pull request merged**
