### PR TITLE
*: Move objstore out of repo

### PR DESCRIPTION
**Pull request by brancz**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Closes https://github.com/thanos-io/thanos/issues/3701

For this to go green we first need Cortex to migrate to the new dep.

## Verification

Code and tests are unchanged, it's just moving code.

cc @onprem @kakkoyun @bwplotka @squat @pracucci @yeya24

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Amazing work, thanks!

**Comment by metalmatze** [comment]
Seems like there are a few more places that need their imports updated.

**Comment by phillebaba** [comment]
Do we have a plan when the switch is going to be made? Thinking where the best place to make changes is.

**Comment by yeya24** [comment]
I think it is confusing to still keep objstore in the THanos codebase. Especially we have changes like https://github.com/thanos-io/thanos/pull/5337.
Let's move forward this if possible...

**Comment by phillebaba** [comment]
I have a PR to update the Azure object store that I want to start testing in my environment.
https://github.com/thanos-io/objstore/pull/3

Is this going to be merged or is it a safe bet to create a new PR to the Thanos repo?

**Comment by bwplotka** [comment]
Yes, we want to merge this, but it requires more work to make it happen.

Also, https://github.com/thanos-io/objstore requires more work in terms of CI and documentation. Normally I would propose to @phillebaba to work on separate repo but we (and @phillebaba) won't be able to verify if the new code works. Thus I would say, unless @kakkoyun @brancz @yeya24 or anyone else has time to finalize this work within next 2 weeks - we should, unfortunately, stick to Thanos codebase. I am ultra busy with book for next weeks, will have more time after that ):

**Comment by kakkoyun** [comment]
> Yes, we want to merge this, but it requires more work to make it happen.
> 
> Also, https://github.com/thanos-io/objstore requires more work in terms of CI and documentation. Normally I would propose to @phillebaba to work on separate repo but we (and @phillebaba) won't be able to verify if the new code works. Thus I would say, unless @kakkoyun @brancz @yeya24 or anyone else has time to finalize this work within next 2 weeks - we should, unfortunately, stick to Thanos codebase. I am ultra busy with book for next weeks, will have more time after that ):

I'm happy to help with this issue and handle the CI work for the separate repo. Is anyone working on anything related to this?
Otherwise, I'll start planning my time for this.

**Comment by bwplotka** [comment]
Check with your CEO, otherwise I think you are good ((((:

**Pull request closed without merging**
