### PR TITLE
CHANGELOG: fix the 0.18.0 tag

### PR DESCRIPTION
**Pull request by GiedriusS**
0.18.0 has been released on Feb 1st so mark it accordingly.

Signed-off-by: Giedrius Statkevičius <giedriuswork@gmail.com>

### CODE REVIEW

**Review by squat — APPROVED** [review]
👍  we actually still need to merge the release-0.18 branch into master, which would also take care of this, but there are some conflicts. I'll try to tackle this asap

**Review by yeya24 — APPROVED** [review]

**Comment by bwplotka** [comment]
Let's maybe wait until @squat PR for consistent change 🤗

**Comment by bwplotka** [comment]
....to not add more conflicts, should be done today/tomorrow - I need to release 0.19 this week too 🤗

**Comment by squat** [comment]
I think we can close this in favor of #3809

**Comment by GiedriusS** [comment]
Yes, closing in favor of https://github.com/thanos-io/thanos/pull/3809. Thanks :+1:

**Pull request closed without merging**
