### PR TITLE
Use original file in rules loaded metric

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Use the original rule file name as the label in load rules metric

### CODE REVIEW

**Comment by yeya24** [comment]
There are still some wrong metrics exported by rule manager, but now I don't figure out how to fix them.
```
curl http://localhost:10908/metrics | grep data/.tmp

prometheus_rule_group_interval_seconds{rule_group="data/.tmp-rules/valid.yaml.96e6e93b5a37e1df396d2d69d8cdba3ec79dd212157123e6bcc2045f28033275.WARN;test-alert-group",strategy="warn"} 5
prometheus_rule_group_interval_seconds{rule_group="data/.tmp-rules/valid.yaml.96e6e93b5a37e1df396d2d69d8cdba3ec79dd212157123e6bcc2045f28033275.WARN;test-alert-group1",strategy="warn"} 5
prometheus_rule_group_last_duration_seconds{rule_group="data/.tmp-rules/valid.yaml.96e6e93b5a37e1df396d2d69d8cdba3ec79dd212157123e6bcc2045f28033275.WARN;test-alert-group",strategy="warn"} 0.001195467
prometheus_rule_group_last_duration_seconds{rule_group="data/.tmp-rules/valid.yaml.96e6e93b5a37e1df396d2d69d8cdba3ec79dd212157123e6bcc2045f28033275.WARN;test-alert-group1",strategy="warn"} 0.002537008
prometheus_rule_group_last_evaluation_timestamp_seconds{rule_group="data/.tmp-rules/valid.yaml.96e6e93b5a37e1df396d2d69d8cdba3ec79dd212157123e6bcc2045f28033275.WARN;test-alert-group",strategy="warn"} 1.575936400578541e+09
prometheus_rule_group_last_evaluation_timestamp_seconds{rule_group="data/.tmp-rules/valid.yaml.96e6e93b5a37e1df396d2d69d8cdba3ec79dd212157123e6bcc2045f28033275.WARN;test-alert-group1",strategy="warn"} 1.575936402443577e+09
prometheus_rule_group_rules{rule_group="data/.tmp-rules/valid.yaml.96e6e93b5a37e1df396d2d69d8cdba3ec79dd212157123e6bcc2045f28033275.WARN;test-alert-group",strategy="warn"} 1
prometheus_rule_group_rules{rule_group="data/.tmp-rules/valid.yaml.96e6e93b5a37e1df396d2d69d8cdba3ec79dd212157123e6bcc2045f28033275.WARN;test-alert-group1",strategy="warn"} 1
```

**Comment by bwplotka** [comment]
Thanks for noticing this. It's not perfect. 

What I will propose is to actually propose `PartialResponseStrategy` on Rules and Alerts in the upstream Prometheus. This might be as well needed as even Prometheus has something like `res.Warnings` in places like rule/alert evaluation: https://github.com/prometheus/prometheus/blob/06066a3619f0561a6e048b8c7cb874985c5a443b/rules/manager.go#L169

This will make native rule/alert being compatible with Thanos one, thus solving this. (: 

cc @simonpasquier if that makes sesne (:

**Comment by simonpasquier** [comment]
@bwplotka interesting idea indeed!

**Comment by yeya24** [comment]
This PR is still valid.

**Comment by yeya24** [comment]
Sorry about that. Just notice I need a rebase in this PR... Is it possible to make this open?

**Comment by bwplotka** [comment]
Of course. I think you have permission to do so, no?

**Comment by yeya24** [comment]
I don't have the permission to re-open it.

**Comment by bwplotka** [comment]
I cannot as well and this is why: 

image

**Pull request closed without merging**
