### PR TITLE
refactor: replicate write request in receive() if necessary

### PR DESCRIPTION
**Pull request by YaoZengzeng**
There is a race condition: the `h.hashring` could be set to nil in `Hashring(...)` without lock. So if a request pass the `testReady()` and then `h.hashring` be set to nil, the program would panic.

And if the request is not replicated yet, we should do it when we receive it instead of doing it in `parallelizeRequests` after some unnecessary calculation in `forward`. 

In addtion, the refactor make the locking of `h.hashring` more easy.

### CODE REVIEW

**Comment by YaoZengzeng** [comment]
@brancz PTAL

**Comment by brancz** [comment]
cc @squat

**Comment by squat** [comment]
@YaoZengzeng right now this PR introduces a sneaky bug.

Notice that the `replicate` func only looks for the hashring of the first timeseries of the write request parameter. This is done because the `replicate` func was only intended to be called AFTER all the individual timeseries in a write request were split off and forwarded to the correct nodes.

With this change set, `replicate` is called on the entire received write request, which can include time series meant for other nodes. Now when `parallelizeRequests` is called from `replicate` and the destination endpoint is the local node, the entire write request will be written locally, even timeseries that are not destined for the local node.

The race does indeed occur, but I don’t think this change is necessary. Let’s simply introduce an RW lock that locks only during the hashring access portions of the `replicate` and  `forward` funcs, ie the loops before `parallelizeRequests` is called.

**Comment by YaoZengzeng** [comment]
@squat You are right.

The code is awesome, after splitting the time series with same hash result will be grouped together, they all will be sent to same node group.  So in `receive()`, we could use `&wreq.Timeseries[0]` to represent all the series in the group.

And if needed, I'd like to help to do the RWLock stuff :)

**Comment by squat** [comment]
> So in receive(), we could use &wreq.Timeseries[0] to represent all the series in the group.

s/receive/replicate/, right?

**Comment by YaoZengzeng** [comment]
`receive()` -> `replicate()` 😂

**Comment by squat** [comment]
Agreed :) thanks for the enthusiasm and for taking a look close at the receive component! Let’s close this PR and start work on the race. If you are up for making an initial draft of the locking PR please go for it and I would be happy to review. We can also discuss and plan on the thanos channel of the cncf slack.

**Comment by YaoZengzeng** [comment]
Close this PR and make another for race condition.

**Pull request closed without merging**
