### PR TITLE
Fix parseStep bug introduced in PR #3740

### PR DESCRIPTION
**Pull request by hitanshu-mehta**
Signed-off-by: Hitanshu Mehta <hitanshu99amehta@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

Fixes: #3872 

## Changes

- Fixed parseStep function.
- Fixed typo from the previous PR.
- Changed related test.

## Verification
- New test case is able to simulate issue #3872. Now, this test case would fail without a fix introduced in this PR.

### CODE REVIEW

**Review by bwplotka — COMMENTED** [review]
wow! Thanks 🤗

**Comment by bwplotka** [comment]
You are super quick @hitanshu-mehta 💪🏽

**Review by bwplotka — APPROVED** [review]

**Comment by bwplotka** [comment]
The only problem is that we need to put PR against `release-0.19` to fix issue ther too

**Review by squat — COMMENTED** [review]
Great find!

**Comment by hitanshu-mehta** [comment]
Thank you 😊   @bwplotka @squat

**Comment by bwplotka** [comment]
https://github.com/thanos-io/thanos/pull/3889

**Pull request merged**
