### PR TITLE
block: Avoid IgnoreDeletionMarkFilter deadlock on many errors

### PR DESCRIPTION
**Pull request by zecke**
The go routine feeding work into the channel could get stuck when
there are more than 2*f.concurrency and more blocks left. Make sure
to completely drain the channel and report any error that occurred.

Signed-off-by: Holger Hans Peter Freyther <holger@freyther.de>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
Simply yet effective, the fix LGTM. Thanks! Have you checked if we can easily write a unit test to cover this regression?

**Review by bwplotka — APPROVED** [review]
Nice, thanks!

**Comment by bwplotka** [comment]
Regression test would be amazing, yes!

**Comment by kakkoyun** [comment]
Hey @zecke, friendly ping. We're going to cut a release candidate soon, is there any chance for you to push this to the finish line? I guess we are only missing some tests.

**Comment by zecke** [comment]
The only test I can think of is a change detector that produces more errors than the level of concurrency. Can you think of anything else?

**Comment by pracucci** [comment]
> The only test I can think of is a change detector that produces more errors than the level of concurrency. Can you think of anything else?

You could use a "fake" `objstore.Bucket` implementation which just returns errors and a number of blocks > concurrency. We expect the meta sync to deadlock (and so the test to timeout) in `main` branch while to return error in your PR. Does it make sense?

**Comment by kakkoyun** [comment]
Sorry for the persistent ping @zecke. This seems like an easy win to have in the release. Do you think you can spare some time on this today? No pressure though, I'm just asking.

**Comment by zecke** [comment]
Unfortunately I might not find time before Friday to add a testcase.

**Comment by kakkoyun** [comment]
👍 Thanks, @zecke for letting me know.

**Review by bwplotka — APPROVED** [review]
That's alright. Just by looking on it, it makes total sense - good to be merged and we can add test later.

**Pull request merged**
