### PR TITLE
querier: Actually use select Start,End params during select.

### PR DESCRIPTION
**Pull request by bwplotka**
This will definitely helps with offset queries.

Same was done on https://github.com/cortexproject/cortex/pull/1012

Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by squat** [comment]
nice catch! looks good, just need to update a test, it seems.

```
--- FAIL: TestEndpoints (0.02s)
    --- FAIL: TestEndpoints/end=-1&match%5B%5D=test_metric2&start=-2 (0.00s)
        v1_test.go:831: Response does not match, expected:
            []
            got:
            [{__name__="test_metric2", foo="boo"}]
FAIL
FAIL	github.com/thanos-io/thanos/pkg/query/api	0.033s
```

**Comment by bwplotka** [comment]
It was actually bug, so test helped. Should be fine now :+1:

**Comment by brian-brazil** [comment]
This is okay, as long as you're using a new enough version of Prometheus that actually sends these.

**Comment by bwplotka** [comment]
Good point, we plan to fetch latest Prometheus soon as well.

**Pull request merged**
