### PR TITLE
Fix button display when there is no panels

### PR DESCRIPTION
**Pull request by Namanl2001**
Signed-off-by: Namanl2001 <namanlakhwani@gmail.com>

Fixes a subissue `Fix button display when there is no panels` in #3541 .

### CODE REVIEW

**Review by Tushar3099 — APPROVED** [review]
LGTM

**Review by prmsrswt — APPROVED** [review]
Sorry for the late review. LGTM as well. Let's resolve the conflict first.

**Comment by kakkoyun** [comment]
@Namanl2001 I've set it to the auto-merge. We can merge it when you rebased and solve the conflicts.

**Comment by Namanl2001** [comment]
ready to merge! and failing test seems unrelated.

**Pull request merged**
