### PR TITLE
Add a point of suggestion for Mentorship Doc

### PR DESCRIPTION
**Pull request by yashrsharma44**
While I was part of the Community Bridge Mentorship, I found that working with an iterative process is really beneficial. Also having a small but working example helps in building up the project. I thought of adding this in the `mentorship` docs.

Suggestions are welcome :hugs:

### CODE REVIEW

**Comment by yashrsharma44** [comment]
large diff due to linting of markdown

**Comment by bwplotka** [comment]
Where is that point? Because all is changed =D

**Comment by yashrsharma44** [comment]
Last two points 😂

**Review by bwplotka — APPROVED** [review]
Perfect. Thanks!

**Pull request merged**
