### PR TITLE
mixin: Separate Read/Write path dashboards for receive

### PR DESCRIPTION
**Pull request by kakkoyun**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end-user.

## Changes

* Separate Read/Write path dashboards for Receiver.
* Remove detailed panels.
* Clean up.

## TODO

* Add screenshots.

## Verification

* `make examples` and import Grafana.

### CODE REVIEW

**Comment by kakkoyun** [comment]
@yeya24 What we observed from our use case, most of the times they are not used. I moved method based aggregations to the panels we have and removed the detailed panels. I'm happy to separate the PRs. 

I just want to reduce confusion and create a single path for troubleshooting through dashboards.
I'm open to discussions. What do you think? Do you see value having them around?

**Comment by kakkoyun** [comment]
@yeya24 Since you already imported them, I'd be glad if you could add some screenshots 😅

**Comment by yeya24** [comment]
> @yeya24 What we observed from our use case, most of the times they are not used. I moved method based aggregations to the panels we have and removed the detailed panels. I'm happy to separate the PRs.
> 
> I just want to reduce confusion and create a single path for troubleshooting through dashboards.
> I'm open to discussions. What do you think? Do you see value having them around?

Makes sense! 

> @yeya24 Since you already imported them, I'd be glad if you could add some screenshots

Will do.

**Comment by yeya24** [comment]
Screenshots for receive.

Screenshot from 2020-07-28 06-05-54
Screenshot from 2020-07-28 06-06-16

**Comment by kakkoyun** [comment]
@yeya24 Thanks for the screenshots.

**Comment by kakkoyun** [comment]
@brancz What do you think?

**Pull request merged**
