### PR TITLE
[5130] [.*:] Upgrade Minio used for local development and e2e tests

### PR DESCRIPTION
**Pull request by B0go**
* [x] Change is not relevant to the end-user.

## Changes

- Upgrade Minio used for local development and e2e tests to https://github.com/minio/minio/commit/91130e884b5df59d66a45a0aad4f48db88f5ca63 because this version upgrades `github.com/shirou/gopsutil` from version **v2.20.3** to **v2.20.9**, adding support for Apple Silicon

## Verification

If you try to run `make test` on a Apple Silicon based MacBook using main you get a few `undefined: KinfoProc` erros:

```
bogo@Bogos-MacBook-Pro ~/D/thanos (main)> make test
(re)installing /Users/bogo/Developer/Go/bin/alertmanager-v0.20.0
(re)installing /Users/bogo/Developer/Go/bin/minio-v0.0.0-20200527010300-cccf2de129da
# github.com/shirou/gopsutil/cpu
../../Go/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
# github.com/shirou/gopsutil/disk
disk_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/shirou/gopsutil/process
../../Go/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/process/process_darwin.go:576:34: undefined: KinfoProc
../../Go/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/process/process_darwin.go:577:8: undefined: KinfoProc
../../Go/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/process/process_darwin.go:590:32: undefined: KinfoProc
../../Go/pkg/mod/github.com/shirou/gopsutil@v2.20.3-0.20200314133625-53cec6b37e6a+incompatible/process/process_darwin.go:594:62: undefined: KinfoProc
make: *** [/Users/bogo/Developer/Go/bin/minio-v0.0.0-20200527010300-cccf2de129da] Error 2
```

After the upgrade, the errors stop happening:

```
bogo@Bogos-MacBook-Pro ~/D/thanos (upgrade-bingo-minio)> make test
(re)installing /Users/bogo/Developer/Go/bin/minio-v0.0.0-20201125204248-91130e884b5d
# github.com/shirou/gopsutil/cpu
../../Go/pkg/mod/github.com/shirou/gopsutil@v2.20.9+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/shirou/gopsutil/host
smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
(re)installing /Users/bogo/Developer/Go/bin/prometheus-v2.4.3+incompatible
go: finding module for package github.com/oklog/oklog/pkg/group
go: finding module for package github.com/go-kit/kit/log/level
go: finding module for package github.com/mwitkow/go-conntrack
go: finding module for package github.com/pkg/errors
go: finding module for package github.com/go-kit/kit/log
go: finding module for package gopkg.in/alecthomas/kingpin.v2
go: finding module for package gopkg.in/yaml.v2
go: finding module for package golang.org/x/net/context
go: finding module for package golang.org/x/net/context/ctxhttp
go: finding module for package github.com/opentracing/opentracing-go
go: finding module for package github.com/gogo/protobuf/proto
go: finding module for package github.com/golang/snappy
go: finding module for package golang.org/x/time/rate
go: finding module for package github.com/opentracing-contrib/go-stdlib/nethttp
go: finding module for package github.com/prometheus/client_model/go
go: finding module for package golang.org/x/net/netutil
go: downloading golang.org/x/net v0.0.0-20220526153639-5463443f8c37
go: finding module for package google.golang.org/grpc
go: finding module for package github.com/hashicorp/consul/api
go: finding module for package github.com/aws/aws-sdk-go/aws
go: finding module for package github.com/aws/aws-sdk-go/aws/credentials
go: finding module for package github.com/aws/aws-sdk-go/aws/credentials/stscreds
go: finding module for package github.com/aws/aws-sdk-go/aws/ec2metadata
go: finding module for package github.com/aws/aws-sdk-go/aws/session
go: finding module for package github.com/aws/aws-sdk-go/service/ec2
go: finding module for package gopkg.in/fsnotify/fsnotify.v1
go: downloading github.com/hashicorp/consul v1.12.1
go: finding module for package golang.org/x/oauth2
go: downloading github.com/aws/aws-sdk-go v1.44.24
...
```

# References

Issue https://github.com/thanos-io/thanos/issues/5130

### CODE REVIEW

**Comment by B0go** [comment]
@bwplotka this is my first time using https://github.com/bwplotka/bingo and I noticed that after I executed `bingo get github.com/minio/minio@91130e884b5df59d66a45a0aad4f48db88f5ca63` it changed the `.gitignore` and all this .sum files became untracked, so I committed all of them! Is this expected?

**Comment by wiardvanrij** [comment]
Good question, crossposted that on slack as well (#5394 thanos-dev)

**Comment by bwplotka** [comment]
Yes, it's ok to bring those .sum in (: we changed bingo to keep them as it's useful for security checksum reason

**Review by bwplotka — APPROVED** [review]
LGTM!

Thanks!

**Review by matej-g — APPROVED** [review]

**Comment by bwplotka** [comment]
Circle CI is flaky, do you mind repushing a commit? I cannot even restart it

**Comment by B0go** [comment]
@bwplotka done :)

**Comment by B0go** [comment]
Looks like something is pending but I am not sure what 🤔 
Screen Shot 2022-05-30 at 14 45 32

**Comment by matej-g** [comment]
Yeah, CircleCI is still pending :disappointed: Not sure what's up. Maybe trying closing / re-opening PR?

**Comment by B0go** [comment]
Hmm, I am guessing that the "create pull request" or some other webhook failed to be sent to CircleCI, causing this check to be pending forever... there is also no build related to this PR on CircleCI. I will try to open a new Pull Request using the same branch

**Comment by matej-g** [comment]
@thanos-io/thanos-maintainers any ideas what we could do here to unblock? Should someone else open a PR from this branch and see if this somehow related to a first-time contributor? I'm out of ideas.

**Comment by B0go** [comment]
I think I solved the problem by login into CircleCI using my Github user... not sure why this stopped the build from running before though

**Pull request merged**
