### PR TITLE
UI: Use native go:embed instead of go-bindata

### PR DESCRIPTION
**Pull request by jacobbaungard**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

- With this commit we migrate from the no longer actively maintained go-bindata project, to go:embed, for embedding the UI app into the go binary. Note that we now check in the static files in `pkg/ui/static` instead of the now deleted `bindata.go`. This is done in order to keep the same build process as before, where the react UI is only compiled on-demand.

## Verification

- Introduced an arbitrary test change in the typescript code, compiled, and tested that the new change is included in the UI of query, qfe, store, rule, compact, and that the UIs seems to load correctly.

### CODE REVIEW

**Review by yeya24 — APPROVED** [review]
Great that we get rid of one more binary to install

**Review by saswatamcode — APPROVED** [review]
Thanks for the awesome work on this, was pending for a long time! :)
We might also want to test this with path prefixes as well.

**Comment by jacobbaungard** [comment]
> We might also want to test this with path prefixes as well.

I've now tested this with `--web.external-prefix="test123"` and check that the query UI correctly loads on i.e `http://localhost:10904/test123/` and also that it redirects if leaving out the prefix.

**Review by philipgough — APPROVED** [review]

**Comment by saswatamcode** [comment]
Seems like this works well after I tested locally. Let's get this merged! Will also help us close https://github.com/thanos-io/thanos/issues/3782

**Pull request merged**
