### PR TITLE
docs: Fix broken links on 'Getting Started' and in page footer

### LINKED ISSUE #4364: [docs] Fix broken links in the Getting Started page
**What happened**:

While going through [Getting Started](https://thanos.io/tip/thanos/getting-started.md/) page of Thanos Doc website I found a list of broken links. Here they are:

| Hyperlinked Text     | URL |
| ----------- | ----------- |
| MAINTAINERS.md     | https://thanos.io/tip/MAINTAINERS.md       |
| CONTRIBUTING.md   | https://thanos.io/tip/CONTRIBUTING.md        |
| here   | https://thanos.io/tip/examples/dashboards/dashboards.md        |
| here   | https://thanos.io/tip/scripts/quickstart.sh        |
| alerts  | https://thanos.io/tip/examples/alerts/alerts.md       |
| on GitHub here   | https://github.com/thanos-io/thanos/edit/main/docs/thanos/getting-started.md        |

This is happening because the following markdown files are not available in the ```docs``` directory. 

**Proposed Solution**:

I can make a copy of the required markdown files and add them to the docs folder. So that they can be rendered successfully on the website.

### PR DESCRIPTION
**Pull request by matej-g**
* [ ] I added CHANGELOG entry for this change.
* [X] Change is not relevant to the end user.

## Changes

Fixes some links in `getting-started.md` which do not work on the thanos.io website, due to them being relative (works only when reading documentation on GitHub).

Also fixes broken links in page footer, inviting users to edit the docs on GitHub. This is achieved by adjusting the sub-string removal pattern in the `contentpreprocess.sh` script, to correct the path (right now it is resulting in `404` on all pages).

Resolves #4364 and #4353

## Verification

Build and deployed the web locally via `make web-serve` and confirmed the links are working.

### CODE REVIEW

**Review by Namanl2001 — APPROVED** [review]
Thanks for your contribution.

These changes will redirect the user to github from the website but we want to take them to respective sections on the website itself. The work for the same is going on the `mdox` project.
But we can consider this PR as a temporary change :)

**Comment by matej-g** [comment]
@Namanl2001 thanks for having a look so fast! 

> These changes will redirect the user to github from the website but we want to take them to respective sections on the website itself. The work for the same is going on the mdox project.

My understanding is these broken links specifically refer GitHub resources, e.g. I believe the links to examples for Grafana dashboards will / should lead the user to thanos-io GitHub repository. Am I wrong?

I could see this making sense for the maintainers or contributing links, but even those seem to refer specifically to the `.md` files in the current version of the page.

**Comment by Namanl2001** [comment]
> e.g. I believe the links to examples for Grafana dashboards will / should lead the user to thanos-io GitHub repository. Am I wrong?

Nope! you are right, as we don't have any example section in the thanos website (it has content provided in `thanos/docs`), the hyperlinks for `examples/...` should redirect to the github.

**Comment by matej-g** [comment]
Seems like this has been resolved in the meantime in other PRs, closing

**Pull request closed without merging**
