### PR TITLE
Query: Allow to ignore No StoreAPIs matched error

### PR DESCRIPTION
**Pull request by junotx**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Add `ignore_no_stores_matched` param to Query APIs to allow to ignore `No StoreAPIs matched error` (default to be specified by `--query.ignore-no-stores-matched` flag). The query param is also to added to grpc series request for ignoring the same error.

It may fix the issue https://github.com/thanos-io/thanos/issues/5862 .

### CODE REVIEW

**Comment by fpetkovski** [comment]
I am not sure if this is a good idea to apply by default. In rulers we usually want to catch errors like this one. However, having a flag to disable this warning might be something useful.

**Comment by GiedriusS** [comment]
Mhm, I wonder if this is not some issue introduced during the recent proxy.go refactoring. See https://github.com/thanos-io/thanos/issues/5862. It's probably better to investigate what behaviour has changed between versions instead of adding yet another option :/

**Comment by junotx** [comment]
> Mhm, I wonder if this is not some issue introduced during the recent proxy.go refactoring. See #5862. It's probably better to investigate what behaviour has changed between versions instead of adding yet another option :/

I reproduce the No StoresAPIs matched error by running receive with an ingester mode and a nonexistent datadir and then using querier to query it before it receives any remote write requests.  It has no stores (did not create a tsdb store for the default tenant id) and but still receive query requests and throw the error.

**Comment by junotx** [comment]
If the configured datadir [not exists](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/receive.go#L709), receive ingester will not create a default tenant data dir and not create tsdb store for the default tenant id when [open MultiTSDB](https://github.com/thanos-io/thanos/blob/main/pkg/receive/multitsdb.go#L192), so it have no any stores but has an [infinite TimeRange](https://github.com/thanos-io/thanos/blob/main/pkg/store/proxy.go#L220)(MinInt64->MaxInt64) and then can receive query requests from querier.  

This may be a special one of cases mentioned by [5862#issuecomment-1312296482](https://github.com/thanos-io/thanos/issues/5862#issuecomment-1312296482).

**Comment by SuperQ** [comment]
Ping, is this still being worked on?

**Comment by fpetkovski** [comment]
Possibly related issue: https://github.com/thanos-io/thanos/pull/5230#issuecomment-1385306458

**Comment by junotx** [comment]
conflicts resolved and changelog added

**Comment by SuperQ** [comment]
Do we actually need to plumb in a configuration option for this? Based on the discussion so far, this is a simple bug and we can just make the change.

**Comment by benjaminhuo** [comment]
> Do we actually need to plumb in a configuration option for this? Based on the discussion so far, this is a simple bug and we can just make the change.

@SuperQ You mean we can directly `return nil` by removing https://github.com/thanos-io/thanos/pull/5937/files#diff-fc53ebad7275ac8861ae5e9e4e937a7cb9c6b267812df9a61f661c842ed94800R284-R289 ?

**Comment by SuperQ** [comment]
I think so. I created https://github.com/thanos-io/thanos/pull/6082 as an alternate proposal.

**Comment by benjaminhuo** [comment]
> I think so. I created #6082 as an alternate proposal.

Make sense, no error should be return if no store matched

**Comment by bwplotka** [comment]
Fixed in https://github.com/thanos-io/thanos/pull/6082, hope that makes sense @junotx - if not let us know 🤗

**Pull request closed without merging**
