### PR TITLE
fix: Discrepancies in go.sum after setting up project

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: kushthedude <kushthedude@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

- There were discrepancies in the go.sum after setting up a project on macOS Catalina. I have pushed the changes for the same to fix it up.

### CODE REVIEW

**Comment by kushthedude** [comment]
@bwplotka Please review it !

**Comment by bwplotka** [comment]
@kushthedude can you stop pinging me personally? There are more maintainers than just me, plus I already have the notification from this PR, so don't worry - if I will have time I will take a look. (:

**Comment by bwplotka** [comment]
>  they are not checked by any osx vendor test

@squat How do you know those are for osx vendor test?

**Comment by bwplotka** [comment]
If that's true we need long term fix indeed.

**Comment by daixiang0** [comment]
I think it is better to update go.sum and go.mod in container, since it is a clean env.

**Comment by kushthedude** [comment]
> If that's true we need long term fix indeed.

What can be the possible way to handle the following ?

**Comment by squat** [comment]
I suspect they are macos deps somehow because our vendor test is passing in ci and the op wrote that this happens on macos Catalina. But it could also be simply due to a Golang version mismatch. @kushthedude, what golang version are you running locally?

**Comment by kushthedude** [comment]
> I suspect they are macos deps somehow because our vendor test is passing in ci and the op wrote that this happens on macos Catalina. But it could also be simply due to a Golang version mismatch. @kushthedude, what golang version are you running locally?


go1.13.7 darwin/amd64

**Pull request closed without merging**
