### PR TITLE
Compactor: Support disable block viewer UI

### PR DESCRIPTION
**Pull request by wanjunlei**
Signed-off-by: wanjunlei <wanjunlei@kubesphere.io>

* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Add a new flag `--web.disable` for compactor, users can disable the block viewer UI of compactor using this flag

## Verification

Run the compactor without `--web.disable` and access the URL `localhost:19092`, the bucket UI works.
Run the compactor with `--web.disable` and access the URL `localhost:19092`, it returns `404 page not found`.

### CODE REVIEW

**Comment by yeya24** [comment]
Thanks for the pr. @wanjunlei What's the goal of this change? Do you want to disable the UI only?
I see you disable both the UI and the API now. Probably we can keep the API.

**Comment by wanjunlei** [comment]
> Thanks for the pr. @wanjunlei What's the goal of this change? Do you want to disable the UI only? I see you disable both the UI and the API now. Probably we can keep the API.

The goal of this change is to reduce resource consumption, so I disable both the UI and the API.

**Review by yeya24 — APPROVED** [review]
LGTM

**Comment by matej-g** [comment]
I'm not against this change in principle, but I'm wondering how many resources does turning it off saves :thinking:. Do we have any numbers?

**Comment by yeya24** [comment]
Right now we don't have a way to change the interval of fetching metadata and it is hardcoded to 1m, which might be a little bit short. Considering a lot of users actually don't need a UI.

Another use case I can think of is about the delete and no compact marker on the UI. For security purpose I guess some users don't want to expose it.

**Comment by matej-g** [comment]
Thanks @yeya24 for the explanation, then it makes sense to add this :+1:

**Review by matej-g — APPROVED** [review]

**Pull request merged**
