### PR TITLE
mixin: Add runbook_url into alerts

### PR DESCRIPTION
**Pull request by nlamirault**
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>

Add `runbook_url` into Prometheus alerts. Like into kubernetes-mixin (According to [monitoring-mixins guidelines](https://monitoring.mixins.dev/#guidelines-for-alert-names-labels-and-annotations)) 

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Add `runbook_url` to each alert to have a link for a runbook.
See : https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/master/runbook.md

## Verification

Generated a runbook example using [promdoc](https://github.com/plexsystems/promdoc/) : https://github.com/nlamirault/thanos/blob/feature/runbook/mixin/runbook.md
like that : 

Create alerts file : 

```
$ make examples/alerts/rules.yaml
```

create a file kube-alerts.yaml using like that : 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-thanos-mixin
spec:
  groups:
  - name: thanos-compact.rules
    rules:
    - alert: ThanosCompactMultipleRunning
   ...
```

Generate documentation : 

```
$ promdoc generate examples/alerts/kube-alerts.yaml -o mixin/runbook.md
```

### CODE REVIEW

**Review by kakkoyun — COMMENTED** [review]
@nlamirault Amazing work! Great contribution.

It would be great to add additional runbook descriptions as in kubernetes-mixin.
Also CI fails you need to run `make examples`

**Comment by kakkoyun** [comment]
cc @metalmatze

**Review by kakkoyun — COMMENTED** [review]
On the second thought our `alerts.md` is very similar to `runbook.md`.
Should merge? The idea of `alerts.md` to give an overview and index of the alerts we have which `runbook.md` also could serve the same purpose.

**Comment by nlamirault** [comment]
@kakkoyun i generated runbook.md file just to create a runbook example. I could remove it from my MR.

**Comment by kakkoyun** [comment]
@nlamirault If It's sole purpose it to be a placeholder, it's ok to have it. Let's explicitly mentioned that this is a mere example, a placeholder in the `runbook.md`. We don't want to cause any confusion. 

And it would be great to actually create runbook content for each of these alert in the long run.

**Comment by nlamirault** [comment]
@kabakaev do I have to add something?

**Comment by nlamirault** [comment]
I put a runbook example : https://github.com/nlamirault/node_exporter/blob/feature/customization/docs/node-mixin/runbook.md

**Review by kakkoyun — APPROVED** [review]
👍

**Pull request merged**
