### PR TITLE
Tests: unique docker env name for tenant tests

### PR DESCRIPTION
**Pull request by jacobbaungard**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

* The e2e tests would occasionally fail due to non-unqiue docker environment names. With this commit the tests are environments are given unique names to avoid these failures.

### CODE REVIEW

**Review by saswatamcode — APPROVED** [review]
LGTM!

**Review by GiedriusS — APPROVED** [review]
I have fixed multiple cases like this in the past. Maybe if you have some time maybe you could contribute a fix to `e2e.NewDockerEnvironment` to catch these problems? There could be a simple `map[string]struct{}` where we could mark created environments and if there is a duplicate -> error out.

**Comment by jacobbaungard** [comment]
> I have fixed multiple cases like this in the past. Maybe if you have some time maybe you could contribute a fix to `e2e.NewDockerEnvironment` to catch these problems? There could be a simple `map[string]struct{}` where we could mark created environments and if there is a duplicate -> error out.

Yes that would be nice. It would only catch tests that are running in the same batch though, so there could still be some issues flying under the radar.

**Comment by MichaHoffmann** [comment]
> > I have fixed multiple cases like this in the past. Maybe if you have some time maybe you could contribute a fix to `e2e.NewDockerEnvironment` to catch these problems? There could be a simple `map[string]struct{}` where we could mark created environments and if there is a duplicate -> error out.
> 
> Yes that would be nice. It would only catch tests that are running in the same batch though, so there could still be some issues flying under the radar.

Can we reduce the chances by just adding random suffixes?

**Comment by jacobbaungard** [comment]
> Can we reduce the chances by just adding random suffixes?

There's a 16char limit (imposed by efficientgo/e2e) on network names, so could be hard to add suffixes in all cases, unless this limit can be removed.

There's a way to let the framework generate a random name instead of setting it manually, perhaps this makes sense?  https://github.com/efficientgo/e2e/blob/6d823e2b60848203d0bcb72b9b2bbbd536a6b86f/env_docker.go#L98

**Pull request merged**
