### PR TITLE
Upgraded react dep to resolve security issue.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

As per https://github.com/thanos-io/thanos/security/dependabot/pkg/ui/react-app/yarn.lock/immer/open

### CODE REVIEW

**Comment by prmsrswt** [comment]
Take a look at this comment https://github.com/thanos-io/thanos/pull/3770#discussion_r570243354

TLDR: Updating the dependency directly will not change anything, as it is an indirect dependency, we will still be using the older version in the build. We need to update the **direct** dependency due to which it got installed.

**Comment by prmsrswt** [comment]
I think it might be a good idea to update all dependencies to the latest non-breaking version. WDYT?

**Comment by kakkoyun** [comment]
@prmsrswt Do you want to create a PR for the #3811 ?

**Comment by bwplotka** [comment]
Ack, I am stupid then. thanks for being here Prem (: Let me close my broken attempt (:

**Pull request closed without merging**
