### PR TITLE
Query-frontend: Fix connection to Redis cluster with TLS.

### PR DESCRIPTION
**Pull request by didukh86**
Issue: https://github.com/thanos-io/thanos/issues/7672

Signed-off-by: didukh86 <didukh86@gmail.com>

## Changes

Added EnableTLS and InsecureSkipVerify to Redis config

## Verification

After build I was able to connect to Redis cluster with TLS enabled

### CODE REVIEW

**Review by pedro-stanaka — APPROVED** [review]
LG - remember to add changelog

**Review by saswatamcode — DISMISSED** [review]
Thanks, could you add a changelog?

**Comment by didukh86** [comment]
Added

**Comment by saswatamcode** [comment]
@didukh86 you would need to sign the changelog commit as well. Could you do that, happy to merge then 🙂

**Comment by didukh86** [comment]
Done

**Comment by didukh86** [comment]
@saswatamcode all commits are signed and all looks fine now. Thank you for reviewing.

**Comment by kaiohenricunha** [comment]
Is there anything else missing for this PR to be merged?

**Comment by didukh86** [comment]
@saswatamcode is there something else blocking this PR from approval?

**Comment by elvishsu66** [comment]
It would be great if we could release this patch soon, please 🙇🏻‍♂️ We desperately need this fixed

**Comment by EhsanLunar** [comment]
@saswatamcode 
Would really like to see this merged if possible

**Review by fpetkovski — APPROVED** [review]

**Pull request merged**
