### PR TITLE
docs: Fix must have Ruler alerts definition

### PR DESCRIPTION
**Pull request by m-messiah**
ThanosRuler missing rule intervals metric used the wrong comparator sign, confusing users trying to create the rule.

* [x] Change is not relevant to the end user.

### CODE REVIEW

**Review by saswatamcode — DISMISSED** [review]
Thanks! LGTM!

Small suggestion

**Comment by m-messiah** [comment]
Thanks @saswatamcode I applied the suggested changes. Would you mind re-approve, please?

**Comment by m-messiah** [comment]
go build failed without access to repo - is it possible to re-run the test?

**Comment by saswatamcode** [comment]
Taking a look: https://cloud-native.slack.com/archives/CL25937SP/p1675415241429889

**Review by saswatamcode — APPROVED** [review]

**Pull request merged**
