### PR TITLE
Removed typos from coding-style-guide.md

### PR DESCRIPTION
**Pull request by Rahulkumar2002**
* [ ] I added CHANGELOG entry for this change.
* [X] Change is not relevant to the end user.

## Changes
There were some typed errors in examples inside [coding-style-guide.md](https://github.com/thanos-io/thanos/blob/main/docs/contributing/coding-style-guide.md) doc.

### CODE REVIEW

**Review by Akshit42-hue — COMMENTED** [review]
Thanks for the PR @Rahulkumar2002 

Can you run `make docs ` to fix CI :)

**Comment by Rahulkumar2002** [comment]
Hello Akshit , I am trying to fix this issue for past 2 days , but couldn't understand the main problem. 

Where should I run make docs ? Like after committing and before pushing to my repo ?

**Comment by Akshit42-hue** [comment]
> Hello Akshit , I am trying to fix this issue for past 2 days , but couldn't understand the main problem.
> 
> Where should I run make docs ? Like after committing and before pushing to my repo ?

Yes, after committing run `make docs` and then push to git

**Comment by Akshit42-hue** [comment]
There are some intermittent failures sometimes. Push an empty commit. Create an empty commit with `git commit -s --allow-empty -m "Retrigger CI"`

**Comment by Rahulkumar2002** [comment]
Ok let me try

**Comment by Rahulkumar2002** [comment]
**make docs** running completely fine in my system but here it showing unstaged changes.Any other solution ? 

> There are some intermittent failures sometimes. Push an empty commit. Create an empty commit with `git commit -s --allow-empty -m "Retrigger CI"`

**Pull request closed without merging**
