### PR TITLE
Merge release 0.30 into main

### PR DESCRIPTION
**Pull request by GiedriusS**
Cherry-pick fixes from release branches into `main`. Put https://github.com/thanos-io/thanos/commit/95256a72956f037d5ed25a125b3a16331b748f5b under "unreleased" because technically that change was never released.

### CODE REVIEW

**Comment by yeya24** [comment]
Do we still plan to merge release branch 0.29 to main? There is another commit that we didn't include in this pr.

**Comment by GiedriusS** [comment]
Which commit that is? I'd prefer to merge everything back into `main` to avoid confusion. It's really confusing to accumulate commits in release branches if those releases never come out :smile:

**Comment by yeya24** [comment]
@GiedriusS This is not currently included https://github.com/thanos-io/thanos/commit/dda0c258613db2544c3c3c97acbb6500652d3210.

**Comment by yeya24** [comment]
I agree it is confusing. Then can we just release 0.29.2 first then merge the fix commits back to main. Then release 0.30.1?

**Comment by GiedriusS** [comment]
We already use a newer minio-go so maybe we can skip that commit?

**Comment by yeya24** [comment]
Yeah that makes sense. Then I think we are good to go. Maybe we can mention that fix in the changelog?

**Comment by GiedriusS** [comment]
It has been mentioned [here](https://github.com/thanos-io/objstore/commit/f82cab737b22bc8817a52221a19b74941205b480) and then [here](https://github.com/thanos-io/thanos/pull/5940/files) :smile: perhaps we should list all updates in `objstore` module updates in our CHANGELOG.md but perhaps let's discuss that in Slack?

**Comment by yeya24** [comment]
I am good. Let's fix the conflict and release the fixes. Thanks!

**Comment by GiedriusS** [comment]
Updated, hopefully I haven't missed anything :smile:

**Review by saswatamcode — APPROVED** [review]
Thanks! LGTM!

**Review by douglascamata — APPROVED** [review]
Thanks a lot, @GiedriusS! 🙇

**Comment by GiedriusS** [comment]
@saswatamcode I think you've squashed this? :smile: https://github.com/thanos-io/thanos/blob/main/docs/release-process.md#completing-the-release some time ago we agreed not to use squash commits so that it would be easier for external users that import thanos as a Go module :smile: not a problem, just something to keep in mind

**Comment by saswatamcode** [comment]
Ah, I missed that! Really sorry @GiedriusS, will keep that in mind from next time! 😓

**Comment by yeya24** [comment]
Are we going to release v0.29.1 and v0.30.2 soon?

**Comment by saswatamcode** [comment]
+1 would love to have those releases, cc: @douglascamata! 🙂

**Comment by yeya24** [comment]
If no one is going to release it today, I will do it tomorrow my time. 
Shall we also cherry pick https://github.com/thanos-io/thanos/pull/6066?

**Comment by fpetkovski** [comment]
Will 30.2 be released from main or do we cherry pick bugfixes only?

**Comment by douglascamata** [comment]
In theory, 0.30.2 should include only bugbixes, so will have to cherry pick #6066, otherwise we would be including huge features that might be better off waiting for 0.31 (like the native histogram support in many components).

**Comment by fpetkovski** [comment]
Makes sense 👍 We should maybe just bump the thanos engine version since we have some bugfixes there that we haven't released yet. One such issue came up in https://github.com/thanos-io/thanos/issues/6073.

**Pull request merged**
