### PR TITLE
Store: Document --chunk-pool-size better

### LINKED ISSUE #2042: Store: Document --chunk-pool-size better
It's not immediately apparent if the chunk pool size is a in-memory cache of the chunks, or if it's an on disk cache. The index cache option was updated and clearly states it's an in-memory cache whereas chunk pool is ambiguous.

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>
Fix #2042

### CODE REVIEW

**Comment by daixiang0** [comment]
@squat how about `Maximum size of concurrently allocatable bytes for chunks in memory, not cache.`?

**Comment by GiedriusS** [comment]
> @squat how about `Maximum size of concurrently allocatable bytes for chunks in memory, not cache.`?

Not sure about the `, not cache.` part because I can imagine there will be a question about what kind of cache are we exactly talking about but otherwise sounds good. It seems to me like the goal here is to put emphasis on the fact that we are talking about the memory in general. Let's see what @squat and others think.

**Comment by squat** [comment]
I agree with @GiedriusS :+1:

**Comment by daixiang0** [comment]
I think it means some fixed memory during thanos running, not the cache memory.

**Comment by bwplotka** [comment]
That's the problem @daixiang0. It's not a fixed memory. It does not allocate that much as you put, it's only use a maximum of configured memory for reusable bytes pool. And if it will go beyond that for chunks it will fail the request. In theory. In practice, I really could not see our:

```
// ErrPoolExhausted is returned if a pool cannot provide the request bytes.
var ErrPoolExhausted = errors.New("pool exhausted")
```

But that's another story (:

**Comment by daixiang0** [comment]
@bwplotka does it mean that memory leak or the speed of system clean cache memory is faster than thanos consumes?

**Comment by bwplotka** [comment]
No, it means opposite: garbage collection (cleaning) is slower than our allocations, even though we don't need some memory. That's why we pool memory.

**Pull request merged**
