### PR TITLE
Show warnings in query frontend

### PR DESCRIPTION
**Pull request by fpetkovski**
QFE currently does not parse warnings from downstream queriers. This commit fixes that by adding the field to proto messages and modifies the merge function to take warnings into account.

* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

* Show query warnings in query frontend. 

## Verification

Manual testing and unit tests.

### CODE REVIEW

**Review by pedro-stanaka — APPROVED** [review]
nice fix

**Review by GiedriusS — APPROVED** [review]

**Review by MichaHoffmann — COMMENTED** [review]
Good catch!

**Review by MichaHoffmann — DISMISSED** [review]

**Comment by fpetkovski** [comment]
I had to modify the cache middleware to also store warnings. This means cached responses will also return the warns produced when the original query was run.

**Review by MichaHoffmann — APPROVED** [review]
lgtm

**Pull request merged**
