### PR TITLE
UI: Fix infinite redirection loop on /

### LINKED ISSUE #4128: Block Viewer: --web.route-prefix flag inconsistent/unexpected redirects
**Thanos, Prometheus and Golang version used**:

Thanos v0.20.0

**Object Storage Provider**:
Not relevant

**What happened**:
Trying to reach the bucketweb tool from a reverse proxy. Setup as following (which works fine with the query component):
- `--web.external-prefix=thanos/bucketweb/`
- `--web.route-prefix=/`

while the reverse proxy (Ambassador) is using:
```
      prefix: /thanos/bucketweb/
      rewrite: /
```

If I hit:
- `/thanos/bucketweb/blocks` works fine
- `/thanos/bucketweb/api/v1/blocks` works fine
- `/thanos/bucketweb/` redirects to `/thanos/bucketweb` and it breaks

Other combination of those parameters create a whole lot of funky behaviors.

**What you expected to happen**:

Hitting `/thanos/bucketweb/` redirects to `/thanos/bucketweb/blocks`.

**How to reproduce it (as minimally and precisely as possible)**:

See before.

**Full logs to relevant components**:

**Anything else we need to know**:

Looks like the redirect is just missing `/blocks` [here](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/tools_bucket.go#L364), comparing that with [Query](https://github.com/thanos-io/thanos/blob/main/cmd/thanos/query.go#L548)

This behavior was introduced by https://github.com/thanos-io/thanos/pull/3690

### PR DESCRIPTION
**Pull request by onprem**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes
- Server React UI index page on request to `/` instead of figuring out the path to redirect to. This fixes #4128 
- Append `/` prefix to other redirects. Without this the location is interpreted as relative and we end up doing weird redirections like `/prefix/new/prefix/...`.

## Verification
Tested Querier, Ruler, and Block Viewer UI locally with and without external prefixes

### CODE REVIEW

**Comment by onprem** [comment]
As this bug was introduced during v0.20.0, does it makes sense to release 0.20.2 with this fix included? cc @kakkoyun

**Comment by kakkoyun** [comment]
Yes, I'd say let's release a minor version with the patch.

**Comment by onprem** [comment]
I think I need to create a PR to the `release-0.20` branch for that, right?

**Comment by onprem** [comment]
Finally managed to change the base correctly :dizzy_face:

**Comment by onprem** [comment]
The e2e tests are failing because of the busybox SHA pinning issue (which is fixed on main).

**Comment by bwplotka** [comment]
Right, however to release the version we need to pull those in too.

**Comment by onprem** [comment]
I see two PRs related to this, do we need both of them here? I was thinking of cherry-picking those two commits from `main`.

https://github.com/thanos-io/thanos/pull/4171 and https://github.com/thanos-io/thanos/pull/4202

**Comment by GiedriusS** [comment]
Are there any tests we could add? I remember how we've had lots of different fixes for the prefix stuff and the issue wasn't completely solved until tests were added that actually programmatically check whether everything works correctly :sweat:

**Comment by kakkoyun** [comment]
As @GiedriusS suggested it'd be great to have tests.

About #4171 and #4202, do we need them for the end artifact or just for CI to pass? I don't have enough context on this.

**Comment by onprem** [comment]
> About #4171 and #4202, do we need them for the end artifact or just for CI to pass? I don't have enough context on this.

I am sorry for the delay on this. I don't have enough context either, but I think we need them for both CI and the end artifact as we won't be able to create docker images to push. I am not even sure if both of them are required or if we can only use one of them.

But since the next release is very soon (first RC in 6 days I think), can we just merge this to main and go ahead.

**Comment by onprem** [comment]
> Are there any tests we could add? I remember how we've had lots of different fixes for the prefix stuff and the issue wasn't completely solved until tests were added that actually programmatically check whether everything works correctly :sweat:

@GiedriusS  Yes, we do have tests for that, but I am not sure how can we add tests for these type of scenarios. There are a lot of places where things can go wrong :sweat_smile: 

The E2E tests for routePrefix etc would have caught this but, but they access the `/graph` page directly and this bug only occurred when you tried to access `/`.

**Comment by onprem** [comment]
Depandabot CI is saying that the config file is wrong and it doesn't have anything like `vendor` in it's schema, but [the documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#vendor) says otherwise :shrug:

**Review by kakkoyun — APPROVED** [review]
LGTM 🚀

**Pull request merged**
