### PR TITLE
Updated liche.

### PR DESCRIPTION
**Pull request by bwplotka**
Hopefully improves https://github.com/thanos-io/thanos/issues/3060

### CODE REVIEW

**Comment by bwplotka** [comment]
Wow, so many links are broken now cc @thisisobate 

I think it's worth to spend some time in adjusting our script for creating links ):

**Comment by thisisobate** [comment]
> Wow, so many links are broken now cc @thisisobate
> 
> I think it's worth to spend some time in adjusting our script for creating links ):

wow...would look into this now

**Comment by bwplotka** [comment]
The problem is that probably our liche script should check if the links will work on master website, not on master :thinking:

**Comment by thisisobate** [comment]
okay...looking into this

**Comment by squat** [comment]
but was it at least faster?

**Comment by bwplotka** [comment]
Yup

**Comment by bwplotka** [comment]
Will be part of https://github.com/thanos-io/thanos/pull/3067/

**Pull request closed without merging**
