### PR TITLE
*: Update busybox versions and cron

### PR DESCRIPTION
**Pull request by matej-g**
* [ ] I added CHANGELOG entry for this change.
* [X] Change is not relevant to the end user.

## Changes

Manually update busybox versions.

Also make the cronjob more frequent (every hour), since in case of change we might have to wait up to a day before we catch the change, causing CI failures etc.

### CODE REVIEW

**Comment by douglascamata** [comment]
@matej-g I would like to challenge this "automated manual" update of the https://quay.io/prometheus/busybox image tags. I did [some quick investigation in the Prometheus repo](https://github.com/search?q=repo%3Aprometheus%2Fprometheus%20busybox&type=code) and they don't have a similar flow. 

Do we have a good reason for doing this in Thanos? Was there ever an issue which this flow solved?

**Comment by jacobbaungard** [comment]
> @matej-g I would like to challenge this "automated manual" update of the https://quay.io/prometheus/busybox image tags. I did [some quick investigation in the Prometheus repo](https://github.com/search?q=repo%3Aprometheus%2Fprometheus%20busybox&type=code) and they don't have a similar flow.
> 
> Do we have a good reason for doing this in Thanos? Was there ever an issue which this flow solved?

It breaks e2e tests as the old images tags seems to be removed, see for example the failures here: https://github.com/thanos-io/thanos/pull/6228

**Comment by douglascamata** [comment]
@jacobbaungard if we used the `latest` tag, like Prometheus uses in their own repo, we wouldn't have this issue. My point is: why aren't we using `latest` to avoid the need for this automation and the temporary problems it causes?

**Comment by fpetkovski** [comment]
Hm seems like we're blocked on https://github.com/thanos-io/thanos/pull/6236 as well.

**Comment by douglascamata** [comment]
@matej-g @fpetkovski shall we merge this? 🙏

**Comment by fpetkovski** [comment]
And so it shall be merged 🚢

**Comment by douglascamata** [comment]
Thanks, everyone! 🙇

**Pull request merged**
