### PR TITLE
querier: per-endpoint configuration

### PR DESCRIPTION
**Pull request by bwplotka**
Suggested changes to https://github.com/thanos-io/thanos/pull/4389 (could not somehow create PR for a PR).

cc @Namanl2001 

This needs more work, tests, lint etc, but shows a direction hopefully

### CODE REVIEW

**Comment by Namanl2001** [comment]
Hi @matej-g @bwplotka @GiedriusS - are these changes still relevant? How can we take this PR further?

PS: https://github.com/thanos-io/thanos/issues/2600#issuecomment-980514167

**Comment by matej-g** [comment]
> Hi @matej-g @bwplotka @GiedriusS - are these changes still relevant? How can we take this PR further?

Hey @Namanl2001, I'm pretty sure we still need this! I wanted to take a look, but alas didn't have a time. You mentioned you struggle with implementing certain function? What is the issue specifically? Are there other things on which are you blocked beside that function?

**Comment by yeya24** [comment]
@Namanl2001 Can you help fix the conflicts? Would be really nice to have this next release.

**Comment by Namanl2001** [comment]
> @Namanl2001 Can you help fix the conflicts? Would be really nice to have this next release.

actually, I'm away from this for a long time now and there are many merge conflicts that need to be resolved, will try to proceed once I get time :)

> You mentioned you struggle with implementing certain function? What is the issue specifically? 

yes @matej-g - earlier I tried to implement that function but was not able to do so, due to lack of understanding

**Comment by matej-g** [comment]
Hey @Namanl2001, I'll have time next week to look into this, would you want to pair up on this feature? Alternatively, if you're busy, I'm happy to try and take over.

**Comment by Namanl2001** [comment]
That would be great @matej-g , let's pair up and get this work done.

**Comment by matej-g** [comment]
This is still sorely needed :cry:

**Comment by bwplotka** [comment]
Yes. Help wanted, I personally won't be able to touch it before mid-June

**Comment by bwplotka** [comment]
Let's close it, for now, @saswatamcode is creating issue summarizing this - we will propose this as mentorship topic.

**Pull request closed without merging**
