### PR TITLE
Block viewer: Reduce vertical whitespacing

### PR DESCRIPTION
**Pull request by daksh-sagar**
Signed-off-by: Daksh Sagar <daksh.sagar@yahoo.com>

Related to #3112 

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes
Edit blocks.moudle.css to reduce vertical whitespace.

## Verification
Verified it in the browser.

### CODE REVIEW

**Comment by squat** [comment]
I think you need to re-bundle the assets so they can actually be built into the binary, no?

**Comment by daksh-sagar** [comment]
Yes absolutely, doing that. Thanks for pointing it out!

**Comment by prmsrswt** [comment]
Can you add a screenshot here as well? Will make it easier to review quickly.

**Comment by daksh-sagar** [comment]
blocks_new

Reduced margin b/w the rows, removed the padding and reduced the height of the blocks

**Review by prmsrswt — APPROVED** [review]
Looks good. @bwplotka do you have any inputs? Otherwise LGTM.

**Review by squat — APPROVED** [review]

**Pull request merged**
