### PR TITLE
Website: add NOS as adopter

### PR DESCRIPTION
**Pull request by calexandre**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

We are using Thanos to federate all Prometheus instances running in our organization so that we can start storing metrics for long-term analysis. 
We already presented the project internally and it was well received! We believe the time has come to announce that we are using Thanos.

### CODE REVIEW

**Review by GiedriusS — APPROVED** [review]
:clap: thank you!

**Comment by GiedriusS** [comment]
@calexandre oh, our website's background color is white and your logo is white hence it doesn't appear. Do you have any version of the logo with colors? :smile:

**Comment by calexandre** [comment]
hey @GiedriusS our logo os monochromatic...but I have a black version! Will update the PR.

**Review by GiedriusS — APPROVED** [review]

**Comment by bwplotka** [comment]
🎉

**Pull request merged**
