### PR TITLE
add go vet to lint

### LINKED ISSUE #1783: pkg: go vet issues due to Seek signature
Hello! `io.Seeker` is one of the more core Go interfaces that should be followed for any method named `Seek`. For examle, go vet currently returns:

```
$ go vet ./...
# github.com/thanos-io/thanos/pkg/compact/downsample
pkg/compact/downsample/downsample.go:620:34: method Seek(x int64) bool should have signature Seek(int64, int) (int64, error)
pkg/compact/downsample/downsample_test.go:495:27: method Seek(int64) bool should have signature Seek(int64, int) (int64, error)
# github.com/thanos-io/thanos/pkg/query
pkg/query/iter.go:221:26: method Seek(int64) bool should have signature Seek(int64, int) (int64, error)
pkg/query/iter.go:237:34: method Seek(t int64) (ok bool) should have signature Seek(int64, int) (int64, error)
pkg/query/iter.go:288:32: method Seek(t int64) (ok bool) should have signature Seek(int64, int) (int64, error)
pkg/query/iter.go:519:32: method Seek(t int64) bool should have signature Seek(int64, int) (int64, error)
pkg/query/querier_test.go:688:26: method Seek(t int64) bool should have signature Seek(int64, int) (int64, error)
```

I don't know what your API compatibility rules and such are, but I would encourage giving this Seek either a different name or following the io.Seeker interface. Alternatively, you could consider whitelisting this and running vet in CI, but I would encourage complying with it to avoid unexpected surprises.

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

* [x] Change is not relevant to the end user.

## Changes

Fix #1783

### CODE REVIEW

**Comment by daixiang0** [comment]
I do not find docs about how to ignore vendor dir with flag or it would check vendor dir, and i test at local as first commit, all are fine.

**Comment by daixiang0** [comment]
And if i specify all go files using FILES_TO_FMT, it would fail:
```
>> examining all of the Go files
named files must all be in one directory; have ./cmd/thanos/ and ./scripts/cfggen/
```

**Comment by squat** [comment]
That’s because go vet takes a list of packages, not files

**Comment by daixiang0** [comment]
I test a repo with vendor dir existed, no issue reported from vendor dir.

**Comment by bwplotka** [comment]
yes, but we have to exclude `vendor` - we don't want to block dep update only because there is some vet issue inside dep.

**Comment by bwplotka** [comment]
> I test a repo with vendor dir existed, no issue reported from vendor dir.

Not sure if that proves that we are safe though (: I would expect some deps actually having some vet issues, so maybe (:

**Comment by daixiang0** [comment]
For now, we have only one vendor dir `./pkg/ui/static/vendor` where no go files exist.

**Comment by squat** [comment]
the golang vendor directory is not checked into the repo but it is created whenever the binary is compiled. the directory will be expected to be there. in fact it's present in my local checkout of the repo pretty much always :)

**Comment by daixiang0** [comment]
@bwplotka @squat i specify dir to skip vendor.

**Pull request merged**
