### PR TITLE
Expose Endpoint Info timeout parameter

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <ben.ye@bytedance.com>

* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Fixes https://github.com/thanos-io/thanos/issues/5450

Expose info timeout param so that users can configure it based on their use case use.

For our use case, we have Thanos Query at cloud control plane and Thanos Sidecars at edge across the world (like Asia, Africa, etc). Due to the physical location distance and network issues, 5 seconds timeout is not sufficient for all cases.

### CODE REVIEW

**Review by fpetkovski — APPROVED** [review]

**Review by matej-g — COMMENTED** [review]
It makes sense to introduce this parameter, but I'm a bit wary of introducing new separate flags in face of work being done in https://github.com/thanos-io/thanos/issues/5340. I assume one of the results will be that we will have a comprehensive endpoint configuration, instead of having individual flags. I'm just wondering if this would not mean we introduce a new flag only to deprecate it couple of releases later, when the `endpoint.config` will potentially supersede it. Maybe having this as a hidden flag first would make sense and then move it to the endpoint config. But maybe @bwplotka, @saswatamcode or @SrushtiSapkale can give us more qualified answer!

**Comment by yeya24** [comment]
Good to know we have WIP work on that. If that's the case yeah definitely better than adding this new flag separately.

**Review by GiedriusS — COMMENTED** [review]
Yeah... maybe let's make it hidden for now? :thinking:

**Review by GiedriusS — APPROVED** [review]

**Review by matej-g — APPROVED** [review]

**Review by matej-g — COMMENTED** [review]
Looks like one more conflict, should be good to go afterwards!

**Review by GiedriusS — DISMISSED** [review]

**Review by GiedriusS — APPROVED** [review]

**Pull request merged**
