### PR TITLE
[chore] Updating Query Engine and Prometheus

### PR DESCRIPTION
**Pull request by alanprot**
* Update the new query engine with the right references after https://github.com/thanos-io/promql-engine/pull/274

* Update prometheus from https://github.com/prometheus/prometheus/tree/v2.44.0-rc.0 to https://github.com/prometheus/prometheus/commit/905a0bd63a12fa328eac4b7f2674356c283bacac
  * Seems that the only relevant change is: https://github.com/prometheus/prometheus/pull/12336

cc @fpetkovski @yeya24

### CODE REVIEW

**Review by yeya24 — APPROVED** [review]
Thanks! I will merge on green

**Comment by fpetkovski** [comment]
Hm looks like docs failure is legit

**Comment by alanprot** [comment]
This is also updating prometheus! I will take a look.

**Review by fpetkovski — APPROVED** [review]
lgtm on green

**Review by yeya24 — APPROVED** [review]

**Comment by yeya24** [comment]
Merge on green

**Pull request merged**
