### PR TITLE
[WIP] compactor: Sets block size compaction limit

### LINKED ISSUE #3068: Limit size of blocks to X bytes on compaction.
This is to ensure the scalability of the compactor.

Tricky part: How to shard block, what label to put, or maybe vertical compaction?

### PR DESCRIPTION
**Pull request by someshkoli**
Currently WIP and aims to resolve #3068 
Partially solves #3221 as block size is required here too. 

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Comment by bwplotka** [comment]
Amazing, thanks for helping on this - we need help here.

Wonder what's the plan here? Detecting size is important, but how we ensure proper sharding of block? (:

**Comment by someshkoli** [comment]
@bwplotka ,As for now I'm done limiting compaction acc to the block index size. 
For sharding I'm planning to do the following, would improvise on this, also let me know if the implementation is wrong 
-  compact a blocks 
-  check final block size (newly generated)
  - if greater than x(64 gib for now)
    - partition it in two roughly equal parts ( do this recursively till all the block sizes are < x )
    - write new blocks and move forward
 - if less than 64 move forward as usual

This way our blocks are compacted to its maximum and also we prevent it from exceeding the limit

**Comment by roidelapluie** [comment]
Note that recently Prometheus BlockReader gained Size() function.

**Comment by someshkoli** [comment]
> Note that recently Prometheus BlockReader gained Size() function.

yeah I did pick that up (disscussed here: #3254) but having some trouble in testing the changes on the same.

**Comment by bwplotka** [comment]
I am moving with https://github.com/thanos-io/thanos/issues/3068 and will probably use the code from this PR if you don't mind :hugs:

**Comment by someshkoli** [comment]
> I am moving with https://github.com/thanos-io/thanos/issues/3068 and will probably use the code from this PR if you don't mind :hugs: 

Yes sure ✌️

**Comment by bwplotka** [comment]
Awesome, closing for now then, but will use your code (:

**Pull request closed without merging**
