### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amye**
Adding actual slack link

* [] CHANGELOG entry if change is relevant to the end user.

### CODE REVIEW

**Comment by FUSAKLA** [comment]
Hi, thanks for updating the link! 

Could you please sign the DCO? Otherwise LGTM :+1:

**Comment by squat** [comment]
ping @amye :) we'd like to get your contribution merged

**Comment by bwplotka** [comment]
I think we should this commit on our own as Amy might be busy.

**Comment by amye** [comment]
Odd, I did just re-run this with a signed-off-by.

**Pull request closed without merging**
