### PR TITLE
*: match naming convention in metrics and documentation

### PR DESCRIPTION
**Pull request by Sayrus**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.
:warning: This is a breaking change

## Changes
Rename metrics not following the components naming convention:
- `thanos_compact_*` (from `thanos_compactor_*`)
- `thanos_rule_*` (from `thanos_ruler_*`)
- `thanos_query_*` (from `thanos_querier_*`)

Also match the naming convention in the documentation and code comments

https://thanos.io/tip/contributing/contributing.md/#components-naming

## Verification

Has yet to be tested.

## Note
I feel like removing the metrics directly before any deprecation cycle has been done is a bit harsh. But before working on duplicating the two metrics, I'd like to have your opinion on this.

### CODE REVIEW

**Review by bwplotka — COMMENTED** [review]
I think this is a fair change, but let's commit this right before 0.17.0 and announce it properly. cc @metalmatze next release shepherd. Also worth to change other components to have one breaking release changing metrics not man (:

**Comment by Sayrus** [comment]
Makes sense.

So I guess it's time to fix references to `thanos_ruler` and `thanos_querier`.
I did not find any `thanos_gateway`. There might be some in the documentation, I'll check later.

Also, we need to add Thanos Query Frontend to the component naming!  (`query_frontend` and `Query Frontend`?)

**Comment by bwplotka** [comment]
correct! (:

**Comment by Sayrus** [comment]
Shall we also update the `CHANGELOG.md` to retroactively reflect those changes?

**Review by kakkoyun — COMMENTED** [review]
LGTM. Thanks for doing this.

You just need to rebase and update the PR description to match recent changes.
Then we can merge this.

And also it'd be nice to add the link to the PR for record keeping purposes https://thanos.io/tip/contributing/contributing.md/#components-naming

**Comment by Sayrus** [comment]
Hello @kakkoyun ,

This should be good now!

I'm not sure how to link this PR in the CONTRIBUTING.md page. Simply linking it without context or anything would be annoying for users simply reading the page.
Can I let you add it without your own words?

**Review by kakkoyun — APPROVED** [review]
LGTM. Thanks a lot for this.

Let's give a chance to @bwplotka for having a final look and then we can merge it.

**Review by bwplotka — APPROVED** [review]
Thanks, LGTM, but metric changes scares me a lot :scream: If someone has alerts or dashboards they don't want to change too often, they will kill us :cry:

**Comment by Sayrus** [comment]
> Thanks, LGTM, but metric changes scares me a lot scream If someone has alerts or dashboards they don't want to change too often, they will kill us cry

That's why I said:
> I feel like removing the metrics directly before any deprecation cycle has been done is a bit harsh. But before working on duplicating the two metrics, I'd like to have your opinion on this.

We could duplicate the metrics for one version as a deprecation cycle. However, it will still break the metric history :disappointed:

**Comment by Sayrus** [comment]
Rebased on master as one metric name was changed

**Review by bwplotka — APPROVED** [review]
I would say let's go with this. @metalmatze is it fine to get into release?

**Review by metalmatze — APPROVED** [review]
Seems good to me. Let's get this into v0.17 then

**Pull request merged**
