### PR TITLE
query-frontend: support forward-header to downstream querier

### PR DESCRIPTION
**Pull request by lcasi**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes
Add `--query-frontend.forward-header` flag to  support headers forward from  query-frontend  to downstream querier 

## Verification

Tested it locally

### CODE REVIEW

**Review by GiedriusS — COMMENTED** [review]
Please update the docs :smile: (https://github.com/thanos-io/thanos/runs/5461075913?check_suite_focus=true). Also, maybe we could add to the documentation a sentence or two about this? For example, where this could be useful or what is your use case

**Comment by lcasi** [comment]
> Please update the docs smile (https://github.com/thanos-io/thanos/runs/5461075913?check_suite_focus=true). Also, maybe we could add to the documentation a sentence or two about this? For example, where this could be useful or what is your use case



> Please update the docs smile (https://github.com/thanos-io/thanos/runs/5461075913?check_suite_focus=true). Also, maybe we could add to the documentation a sentence or two about this? For example, where this could be useful or what is your use case

I have updated the docs.

**Comment by lcasi** [comment]
Hey @GiedriusS, I didn't update docs/release-process.md and maintainers.md, but doc check failed, could you please help me?

**Review by yeya24 — APPROVED** [review]
LGTM. Thanks for the contribution @lcasi

**Pull request merged**
