### PR TITLE
storetestutil: Added shared series helpers on BucketSeries; added ProxySeries and MultiTSDB Series benchmarks.  

### PR DESCRIPTION
**Pull request by bwplotka**
Similar to store GW Series but for proxy.

Also: * Fixed minTime for TSDB and Receiver. Now checks head block min Time as well. 

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by bwplotka** [comment]
Yup will finish.. at some point (:

**Comment by bwplotka** [comment]
This should be ready for review. Benchmarking Receive Series now.

**Comment by bwplotka** [comment]
Baseline on my machine.

```
Running BenchmarkMultiTSDBSeries run 0-receiveseries
Creating 250000 1-sample series in /tmp/testorbench-multitsdbseries443287264/0
Creating 250000 1-sample series in /tmp/testorbench-multitsdbseries443287264/1
Creating 250000 1-sample series in /tmp/testorbench-multitsdbseries443287264/2
Creating 250000 1-sample series in /tmp/testorbench-multitsdbseries443287264/3
goos: linux
goarch: amd64
pkg: github.com/thanos-io/thanos/pkg/store
BenchmarkMultiTSDBSeries/1000000SeriesWith1Samples/headOnly/4_TSDBs_with_1_samples,_250000_series_each-12         	       6	6405328704 ns/op	4077894794 B/op	44868668 allocs/op
Creating 250000 1-sample series in /tmp/testorbench-multitsdbseries458997439/0
Creating 250000 1-sample series in /tmp/testorbench-multitsdbseries458997439/1
Creating 250000 1-sample series in /tmp/testorbench-multitsdbseries458997439/2
Creating 250000 1-sample series in /tmp/testorbench-multitsdbseries458997439/3
BenchmarkMultiTSDBSeries/1000000SeriesWith1Samples/blocksOnly/4_TSDBs_with_1_samples,_250000_series_each-12       	       6	5773966111 ns/op	4076671805 B/op	44868444 allocs/op
Creating 25000 25-sample series in /tmp/testorbench-multitsdbseries842640658/0
Creating 25000 25-sample series in /tmp/testorbench-multitsdbseries842640658/1
Creating 25000 25-sample series in /tmp/testorbench-multitsdbseries842640658/2
Creating 25000 25-sample series in /tmp/testorbench-multitsdbseries842640658/3
BenchmarkMultiTSDBSeries/100000SeriesWith100Samples/headOnly/4_TSDBs_with_25_samples,_25000_series_each-12        	       9	3684722410 ns/op	1728735155 B/op	27126350 allocs/op
Creating 25000 25-sample series in /tmp/testorbench-multitsdbseries244242761/0
Creating 25000 25-sample series in /tmp/testorbench-multitsdbseries244242761/1
Creating 25000 25-sample series in /tmp/testorbench-multitsdbseries244242761/2
Creating 25000 25-sample series in /tmp/testorbench-multitsdbseries244242761/3
BenchmarkMultiTSDBSeries/100000SeriesWith100Samples/blocksOnly/4_TSDBs_with_25_samples,_25000_series_each-12      	       9	4040282723 ns/op	1664831863 B/op	27121975 allocs/op
Creating 1 2500000-sample series in /tmp/testorbench-multitsdbseries145321492/0
Creating 1 2500000-sample series in /tmp/testorbench-multitsdbseries145321492/1
Creating 1 2500000-sample series in /tmp/testorbench-multitsdbseries145321492/2
Creating 1 2500000-sample series in /tmp/testorbench-multitsdbseries145321492/3
BenchmarkMultiTSDBSeries/1SeriesWith10000000Samples/headOnly/4_TSDBs_with_2500000_samples,_1_series_each-12       	      24	1533123931 ns/op	2708868740 B/op	 1022712 allocs/op
Creating 1 2500000-sample series in /tmp/testorbench-multitsdbseries755299939/0
Creating 1 2500000-sample series in /tmp/testorbench-multitsdbseries755299939/1
Creating 1 2500000-sample series in /tmp/testorbench-multitsdbseries755299939/2
Creating 1 2500000-sample series in /tmp/testorbench-multitsdbseries755299939/3
BenchmarkMultiTSDBSeries/1SeriesWith10000000Samples/blocksOnly/4_TSDBs_with_2500000_samples,_1_series_each-12     	      20	1674253837 ns/op	2682663242 B/op	 1020595 allocs/op
```

**Comment by brancz** [comment]
re-kicked the CI job it seems like it was a flake in the reloader tests

**Pull request merged**
