### PR TITLE
ruler: fixes issue 4302, adds display of alert duration time in Alerts UI

### PR DESCRIPTION
**Pull request by rackeric**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user. (reasoning: cosmetic)

## Changes

Closes #4303.

- adds display of alert duration time in Alerts UI
- new function formatDuration() as used in Prometheus project
- also displays all labels and all annotations, not just severity and summary

## Verification

Tested locally with `make Quickstart` and `yarn start` for the React UI portion. Screenshot added below.

Screen Shot 2021-06-12 at 12 46 32 PM

Original:
Screen Shot 2021-06-12 at 1 02 41 PM

yarn test, since added new func and tests:
```
  PASS  src/pages/graph/DataTable.test.tsx
 PASS  src/utils/utils.test.ts
 PASS  src/App.test.tsx
 PASS  src/pages/targets/ScrapePoolPanel.test.tsx
 PASS  src/thanos/pages/blocks/Blocks.test.tsx
 PASS  src/pages/targets/ScrapePoolList.test.tsx
 PASS  src/pages/graph/TimeInput.test.tsx
 PASS  src/pages/graph/ExpressionInput.test.tsx
 PASS  src/thanos/pages/stores/StorePoolPanel.test.tsx
 PASS  src/pages/graph/GraphControls.test.tsx
 PASS  src/thanos/pages/blocks/BlockDetails.test.tsx
 PASS  src/pages/graph/Panel.test.tsx
 PASS  src/thanos/pages/stores/Stores.test.tsx
 PASS  src/pages/graph/Graph.test.tsx
 PASS  src/pages/graph/PanelList.test.tsx
 PASS  src/pages/graph/CMExpressionInput.test.tsx
 PASS  src/pages/tsdbStatus/TSDBStatus.test.tsx
 PASS  src/thanos/pages/blocks/helpers.test.tsx
 PASS  src/pages/targets/Targets.test.tsx
 PASS  src/pages/targets/Filter.test.tsx
 PASS  src/pages/flags/Flags.test.tsx
 PASS  src/pages/graph/GraphHelpers.test.ts
 PASS  src/pages/status/Status.test.tsx
 PASS  src/Navbar.test.tsx
 PASS  src/hooks/useLocalStorage.test.tsx
 PASS  src/pages/graph/SeriesName.test.tsx
 PASS  src/pages/graph/GraphTabContent.test.tsx
 PASS  src/components/Checkbox.test.tsx
 PASS  src/pages/targets/EndpointLink.test.tsx
 PASS  src/pages/targets/TargetLabels.test.tsx
 PASS  src/thanos/pages/blocks/SourceView.test.tsx
 PASS  src/components/ToggleMoreLess.test.tsx
 PASS  src/thanos/pages/stores/StoreLabels.test.tsx
 PASS  src/pages/targets/target.test.ts
 PASS  src/pages/graph/QueryStatsView.test.tsx

Test Suites: 35 passed, 35 total
Tests:       268 passed, 268 total
Snapshots:   4 passed, 4 total
Time:        11.354s, estimated 15s
```

### CODE REVIEW

**Comment by yeya24** [comment]
Thanks for your contribution. Please sign off DCO.

For the code change, would you mind just using the same upstream code as Prometheus? https://github.com/prometheus/prometheus/blob/main/web/ui/react-app/src/pages/alerts/CollapsibleAlertPanel.tsx#L38-L64

**Comment by rackeric** [comment]
good call @yeya24, doing this managed to now show all annotations also, instead of just "summary". This was something I had not noticed.

also needed to add this function "formatDuration()" as used in the Prometheus project since did not exist in Thanos.

**Comment by yeya24** [comment]
Thanks. Can you please fix your DCO so that we can review and merge your pr later? https://github.com/thanos-io/thanos/pull/4340/checks?check_run_id=2810556064

**Comment by rackeric** [comment]
@yeya24 should be ok now, thanks!

**Comment by rackeric** [comment]
test this please

**Review by GiedriusS — COMMENTED** [review]
LGTM, just one thing: could we also please import the tests from here https://github.com/prometheus/prometheus/blob/f0fe189d20b78a85fd24b038557e5149e49abe86/web/ui/react-app/src/utils/utils.test.ts#L70 into https://github.com/thanos-io/thanos/blob/a255b49ec408b0c7996fca9202c37e77e96cc53b/pkg/ui/react-app/src/utils/utils.test.ts? AFAICT we don't have the `parseDuration` function in our codebase. If that's the case then maybe we could modify the original tests somehow to at least have something similar in Thanos?

cc @onprem

**Comment by onprem** [comment]
There is a PR open for introducing the `parseDuration` fn to our codebase. But the PR is sitting stale from quite a while tho, I'll find and link it.

**Comment by rackeric** [comment]
@GiedriusS thanks, I've added test cases specific to formatDuration() for now.

**Comment by GiedriusS** [comment]
Thanks for your pull request! We've just merged an earlier pull request that was rebased by @onprem. It has the missing function + fixes the problem that your pull request tries to address. I hope there are no hard feelings about this, thank you a lot for your effort! We're trying hard to have more or less the same code-base for the UI so that it would be easy to pull changes on Prometheus side to Thanos so that PR is preferred more because it avoids discrepancies. 

The fix is here https://github.com/thanos-io/thanos/pull/3678/files#diff-50298ee275ead9b6ba3dcc1a556430c41d6ba48a8a4b12e26c83cece720f9bdbR89-R94 and landed in `main`. Thank you again!

**Comment by onprem** [comment]
Umm, I don't think those are the same fixes @GiedriusS, the files changed are different. I can see why you thought this is fixed though haha, but this `for:` is there at two places, and I decided to not touch the other file as this PR was open.

**Comment by rackeric** [comment]
no worries @GiedriusS, just happy to help. thanks @onprem for leaving this bit open for me. I've updated accordingly.

**Review by GiedriusS — APPROVED** [review]
Sorry for the pre-emptive close! LGTM. Could you please do `make assets` and commit the results before merging?

**Comment by rackeric** [comment]
Just updated with output from `make assets`. thanks.

**Review by GiedriusS — APPROVED** [review]
Thank you! LGTM :muscle:

**Pull request merged**
