### PR TITLE
making the tsdb.too-far-in-future.time-window flag stable

### PR DESCRIPTION
**Pull request by Avigdorrr**
## Changes

 changed the docs to support the stability of the tsdb.too-far-in-future.time-window flag

### CODE REVIEW

**Review by yeya24 — COMMENTED** [review]
Looks good. Need to fix doc and DCO

**Comment by Avigdorrr** [comment]
I am not sure what's the problem in the docs.
could you help @yeya24 ?

**Comment by yeya24** [comment]
Have you tried `make docs` or `make doc`?

**Comment by MichaHoffmann** [comment]
Continued here: https://github.com/thanos-io/thanos/pull/7707

**Pull request closed without merging**
