### PR TITLE
store: S3 object store via AWS SDK

### PR DESCRIPTION
**Pull request by cyrus-mc**
This PR allows supporting of the following setup:

* AWS Account A
    * A S3 bucket with a policy allowing Account B to PutObject
* AWS Account B/C/D/...
   * An IAM Role with the policy PutObject on bucket in Account A

Various Prometheus + Thanos clusters are running in Account B/C/D/.. and writing their storage to S3 bucket in Account A. In Account A I have Thanos Querier, Compact, etc running.

In the above scenario the default ACL assigned to an object only allows the owner access (Account B). Account A has no permissions to that object thus the Thanos components can't read the contents uploaded by the sub-accounts.

The current S3 implementation coded against Minio doesn't support setting ACL (as Minio server doesn't support ACL). The other option would be to use an assume role but the Minio client doesn't support this either. 

This implementation of the S3 storage allows setting an ACL on PutObject.

## Changes

* Added object storage for S3 utilizing the AWS SDK

## Verification

Currently only manual.

### CODE REVIEW

**Comment by cyrus-mc** [comment]
This PR is not complete. I am new to golang so figured I would open the PR to elicit feedback.

**Comment by bwplotka** [comment]
I totally see the reasoning, but this needs some discussion before allowing separate AWS SDK implementation. Mainly because it's not the best to have two things solving the same problem (minio client and AWS SDK client for S3 backend). 

However, given some timeout issues we seen with minio client:https://github.com/thanos-io/thanos/issues/1830.. maybe it's worth considering.

**Comment by cyrus-mc** [comment]
@bwplotka 

I know the minio client will add assume role capabilities in the coming weeks. But (reading other GitHub issues) they have shot down adding ACL since the server will never support ACL. 

I will continue to develop this implementation as the discussion continues.

**Comment by cyrus-mc** [comment]
@bwplotka 

I have completed development of this implementation. I believe it to be feature compatible with the minio implementation.

**Comment by bwplotka** [comment]
Cool. There was one good question done by @kakkoyun 

Why not using just https://github.com/google/go-cloud? It uses SDK and it will allow us to remove also GCS, Azure implemetations (: Would that work?

**Comment by cyrus-mc** [comment]
> Cool. There was one good question done by @kakkoyun
> 
> Why not using just https://github.com/google/go-cloud? It uses SDK and it will allow us to remove also GCS, Azure implemetations (: Would that work?

Not familiar with go-cloud.

**Comment by cyrus-mc** [comment]
@bwplotka Two question.

First, the failed build. This seems to be something with the build pipeline in general and not related to any code changes I made (I see other PR suffer this same error).

Second, I have been running this in production for a week or so now. Ran into a few issues which I have fixed. Was the idea of using minio due to the fact you could then use Minio as an S3 backend? Or other S3 compatible backends? 

I believe my implementation will still work in those situations.

**Comment by povilasv** [comment]
In general I agree with @bwplotka we should look for alternatives for minio client and trying them before actually adding this, as this will cause confusion (which S3 to use?), this will add more dependencies we need to take care of etc. 

Let's try go-cloud first if there are no better alternatives which seem to do the job, we can consider this as a viable option, but then maybe deprecate the old one?

**Comment by bwplotka** [comment]
Sad we could merge this ): But we really need to have a proper solution with go-cloud instead I believe.

Thanks for your work @cyrus-mc anyway!

**Comment by jtweaver** [comment]
Was a solution for this ever implemented? We have essentially the same scenario as OP and are just realizing the account with the bucket (bucket owner, not object owner) cannot access the objects pushed by the other accounts.

**Pull request closed without merging**
