### PR TITLE
Cut 0.28.1

### PR DESCRIPTION
**Pull request by yeya24**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

It is a little bit late now but the goal of this pr is to cut `v0.28.1-rc.0` to mainly brings in https://github.com/thanos-io/thanos/pull/5702/files to fix panic due to minio.

### CODE REVIEW

**Comment by yeya24** [comment]
Umm, I am not sure how should I fix the DCO issue.

```
Commit sha: [5b5cdc9](https://github.com/thanos-io/thanos/pull/5757/commits/5b5cdc9cab9c8dfaaa1e2b1b6e0a214f6a93eaf0), Author: Sotiris Nanopoulos, Committer: Ben Ye; Can not find "Sotiris Nanopoulos [sonanopo@microsoft.com](mailto:sonanopo@microsoft.com)", in ["Sotiris Nanopoulos [sotiris.nanopoulos@reddit.com](mailto:sotiris.nanopoulos@reddit.com)", "Sotiris Nanopoulos [sotiris.nanopoulos@reddit.com](mailto:sotiris.nanopoulos@reddit.com)", "Sotiris Nanopoulos [sotiris.nanopoulos@reddit.com](mailto:sotiris.nanopoulos@reddit.com)"].
```

Should I signed off for`sonanopo@microsoft.com`?

**Comment by squat** [comment]
Can't we just force it to pass?

**Comment by SuperQ** [comment]
This change is small enough, I don't really see a need to cut a release candidate. Maybe just directly release 0.28.1.

**Comment by davinci26** [comment]
Hmmm seems like there is a residual email from my previous company that is messing things up. Added the reddit email to DCO maybe this will fix things?

**Comment by squat** [comment]
Ah makes sense, because it's not the same as the original commit that was merged into main

**Comment by yeya24** [comment]
Thanks @douglascamata, this works!
Anyone would like to take a look? If it is good I will merge.

**Comment by yeya24** [comment]
@SuperQ Thanks, mind taking another look?

**Review by SuperQ — APPROVED** [review]
LGTM

**Pull request merged**
