### PR TITLE
Capnp: Use segment from existing message

### PR DESCRIPTION
**Pull request by fpetkovski**
There seems to be an occasional issue with the latest capnproto version where segments are not properly attached to the message arena. 

Downgrading the version solves the problem.

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Review by MichaHoffmann — DISMISSED** [review]

**Review by pedro-stanaka — APPROVED** [review]

**Review by saswatamcode — APPROVED** [review]
Thanks! Might be worth a 0.37.1 @fpetkovski?

**Comment by fpetkovski** [comment]
Yes, we should cut 0.37.1 👍

**Comment by EhsanLunar** [comment]
> Yes, we should cut 0.37.1 👍

@fpetkovski Really excited about getting capnproto, is there anything I can do to initiate a new patch release? We'de prefer to run official releases in our production environment 😄

**Comment by saswatamcode** [comment]
Cutting here https://github.com/thanos-io/thanos/pull/7952

**Pull request merged**
