### PR TITLE
UI: Update vulnerable dependencies

### PR DESCRIPTION
**Pull request by jgbernalp**
Update react-scripts to bump vulnerable dependencies

Signed-off-by: Gabriel Bernal gbernal@redhat.com

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

- Upgrade `react-scripts` version to deal with: https://github.com/advisories/GHSA-qrpm-p2h7-hrv2 and https://github.com/advisories/GHSA-c36v-fmgq-m8hx
- Upgrade TypeScript and made small refactors to make TypeScript happy
- Upgrade `url-parse` to deal with: https://github.com/advisories/GHSA-rqff-837h-mm52

## Verification

- Manual testing by connecting to a local thanos

### CODE REVIEW

**Review by saswatamcode — DISMISSED** [review]
This looks good to me! Thanks! 💫

**Review by metalmatze — APPROVED** [review]
LGTM cc @onprem

**Comment by GiedriusS** [comment]
Could you rebase on `main`? We've removed the old UI so this needs to be updated.

**Comment by jgbernalp** [comment]
It's rebased now
cc @GiedriusS @onprem

**Comment by squat** [comment]
Thanks @jgbernalp

**Pull request merged**
