### PR TITLE
docs: Add SoundCloud to adopters list

### PR DESCRIPTION
**Pull request by marctc**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Add SoundCloud to list of adopters.

### CODE REVIEW

**Comment by yeya24** [comment]
Hi @marctc, thanks for the contribution!
I found that the logo is a bit overflowing. Can you please help take a look?
image

**Review by bwplotka — APPROVED** [review]
Thanks! 

Amazing to hear 🤗

**Comment by marctc** [comment]
> Hi @marctc, thanks for the contribution! I found that the logo is a bit overflowing. Can you resize the image a little bit? image

Done. Is it better now?

**Review by yeya24 — APPROVED** [review]
Thanks!

**Pull request merged**
