### PR TITLE
Cut release 0.23.0-rc.0

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Review by wiardvanrij — APPROVED** [review]

**Comment by GiedriusS** [comment]
https://github.com/thanos-io/thanos/pull/4586#discussion_r700735487 I suppose this needs fixing before the release :(

**Comment by bwplotka** [comment]
Yup, that's a small blocker: https://github.com/thanos-io/thanos/pull/4586#discussion_r701162085

**Comment by bwplotka** [comment]
rebased release branch on fixed main 💪🏽 Let's go!

**Comment by GiedriusS** [comment]
Do we need to mention https://github.com/thanos-io/thanos/pull/4421? With that PR we now pick up all of the APIs that a node exposes automatically, right?

**Comment by bwplotka** [comment]
You are absolutely right I missed this. Just checked the code it does not matter indeed 💪🏽

**Comment by bwplotka** [comment]
Double checking now if this will work will old Rule/Metadata etc APIs?

**Comment by bwplotka** [comment]
cc @hitanshu-mehta

**Comment by bwplotka** [comment]
I think there is regression here - if someone points to old Ruler API (e.g Thanos Ruler) in `--rule` - we will assume it's store API

**Comment by hitanshu-mehta** [comment]
@bwplotka Yes, currently we are assuming it exposes both rule and store APIs (see [here](https://github.com/thanos-io/thanos/blob/bd134d7a823708fa135e7a6931e76f581be5f879/pkg/query/endpointset.go#L107)), because previously we were keeping `rule`, `metadata`, `target` and `exemplar` APIs only if we have store API at those endpoints. (see [here](https://github.com/thanos-io/thanos/blob/ff363498fc95cfe17de894d7237bcf38bdd0bc36/pkg/query/storeset.go#L541)).

**Comment by bwplotka** [comment]
I understand, but I  think we can't assume that. One can roll querier without rolling other components. Adding test case and potential fix here:  https://github.com/thanos-io/thanos/pull/4645

**Comment by bwplotka** [comment]
I might wrong, all might be good thanks to `fillExpectedAPIs` 🤔

**Comment by bwplotka** [comment]
Addressed comment, @GiedriusS @hitanshu-mehta and confirmed all is good, no regression is there ([spent ~2h on assuring that = worth it XD!]( https://github.com/thanos-io/thanos/pull/4645)). Thanks for amazing work (:

**Review by GiedriusS — APPROVED** [review]

**Review by yeya24 — APPROVED** [review]

**Pull request merged**
