### PR TITLE
MAINTAINERS.md: add myself as maintainer

### PR DESCRIPTION
**Pull request by MichaHoffmann**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Added myself to MAINTAINERS.md

## Verification

:tada:

### CODE REVIEW

**Review by squat — APPROVED** [review]
🏄‍♀️

**Review by fpetkovski — APPROVED** [review]
Congrats and thanks for all the great work 🎉

**Review by saswatamcode — APPROVED** [review]
Congrats! ❤️ 🚀

**Review by bwplotka — APPROVED** [review]
💪🏽

**Pull request merged**
