### PR TITLE
Query Frontend: fix downsampled middleware returning duplicate samples

### PR DESCRIPTION
**Pull request by krya-kryak**
Downsampled middleware incorrectly determined minimum response timestamp
using only one data point, which sometimes resulted in superflous requests
and duplicate samples in response. Those duplicate samples in turn broke
graph rendering in grafana in Thanos UI.

Signed-off-by: Vladimir Kononov <krya-kryak@users.noreply.github.com>

* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Verification

Unit tests added for minResponseTime

### CODE REVIEW

**Comment by krya-kryak** [comment]
I wonder if this calls for 0.19.1.

**Review by yeya24 — APPROVED** [review]
LGTM. CC @bwplotka

**Comment by krya-kryak** [comment]
For the record: this is how broken graphs looked like in thanos UI:
image

The response contained duplicate points for label `status="error"` up to and including `1617264240`:
```
        "result": [
            {
                "metric": {
                    "status": "error"
                },
                "values": [
                    [1617264270, "0.05340622092250431"],
                    [1617264300, "0.042536326980866526"]
                ]
            },
            {
                "metric": {
                    "status": "timeout"
                },
                "values": [
                    [1617264180, "0.31111111111111106"],
                    [1617264210, "0.37779284253030704"],
                    [1617264240, "0.38888888888888884"],
                    [1617264180, "0.31111111111111106"],
                    [1617264210, "0.37779284253030704"],
                    [1617264240, "0.38888888888888884"],
                    [1617264270, "0.811111111111111"],
                    [1617264300, "0.6666522236665222"]
                ]
            }
        ]
    }
}
```

**Review by bwplotka — APPROVED** [review]
Thank you! Solid work, LGTM 🤗

**Pull request merged**
