### PR TITLE
Mixin: make timezone dynamic

### PR DESCRIPTION
**Pull request by wiardvanrij**
Signed-off-by: Wiard van Rij <wiard@outlook.com>

## Changes

This keeps the default timezone for dashboards to 'UTC' but allows to override it in an easier way.

### CODE REVIEW

**Review by onprem — APPROVED** [review]
Thanks for the PR. This looks good to me but I am not much familiar with mixins so let's wait for someone else to review this as well.

**Review by kakkoyun — APPROVED** [review]
LGTM 🚀 Thanks.

**Comment by yashrsharma44** [comment]
Lets get this merged, if all the changes make sense?

**Comment by onprem** [comment]
The auto-merge was stuck somehow so merged it manually.

**Pull request merged**
