### PR TITLE
Update Twitter logo

### PR DESCRIPTION
**Pull request by prabhashj07**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

- Updated the Twitter logo in HTML files to use the new FontAwesome class.

## Verification

I tested the changes by following these steps:

1. Made the necessary changes to the HTML files as described in the issue #6624.
2. Opened the HTML files in Visual Studio Code.
3. Used the Live Server extension in Visual Studio Code to preview the changes in a local development environment.
4. Confirmed that the new Twitter logo is displayed correctly in the browser when using the Live Server.
5. Inspected the HTML elements to ensure that the updated FontAwesome class is applied.

The changes are working as expected, and the new Twitter logo is displayed correctly when using the Live Server for testing.

If you have any further questions or need more information, please let me know!

### CODE REVIEW

**Comment by yeya24** [comment]
Can you please fix DCO?

**Comment by yeya24** [comment]
Can you check https://deploy-preview-6627--thanos-io.netlify.app/ and see if it is working as expected? I think some logos are still the old one

**Comment by squat** [comment]
now that you added a new commit, can you please sign the DCO again for your latest commit?

**Comment by prabhashj07** [comment]
Fixed

**Comment by prabhashj07** [comment]
I have tried everything possible but dont know whats happening. Let me create another branch and create another pull request.

**Pull request closed without merging**
