### PR TITLE
Dependency - Update minio-go to v7.0.70

### PR DESCRIPTION
**Pull request by eqfarhad**
fix issue: #7157

Bumping the Minio-go dependency version to the v7.0.70 as it contains support for EKS Pod Identity
+ https://github.com/minio/minio-go/releases/tag/v7.0.70

* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Bump the minio-go version to v7.0.70

### CODE REVIEW

**Review by yeya24 — COMMENTED** [review]
Thanks for the contribution.
However, I think it is still unclear to me how to use the EKS Pod Identity feature. Do we need to update docs somewhere for instructions?

**Comment by eqfarhad** [comment]
> I think it is still unclear to me how to use the EKS Pod Identity feature. 

IMO it's more on AWS side; the [docs are available on their side and well explained](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) how it works or how to use Pod Identity feature instead of IAM Roles for service accounts (IRSA) in EKS. 

in case of Thanos IIUC based on the [s3 pkg](https://github.com/thanos-io/objstore/blob/main/providers/s3/s3.go) and your comment [we are relying on Minio-go](https://github.com/thanos-io/thanos/issues/7157#issuecomment-1958857342), hence they had to push the update first to support it;
Which they did and here in the update for minio-go, we can see that now beside the other env variables it also checks the `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE ` that's a new env var provided by [Pod Identity](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-how-it-works.html#pod-id-agent-pod) feature

+ https://github.com/minio/minio-go/pull/1944

> Do we need to update docs somewhere for instructions?

I did a quick search in the docs, and maybe [we can add it here](https://github.com/thanos-io/thanos/blob/main/docs/storage.md?plain=1#L109), wdyt?

**Comment by yeya24** [comment]
Cool, thanks for the comment. I think I am ok to proceed with this pr without updating docs. We don't have doc for `AWS_CONTAINER_AUTHORIZATION_TOKEN_FILE` as well

**Review by yeya24 — DISMISSED** [review]
Thanks

**Comment by yeya24** [comment]
There is a conflict in changelog

**Comment by eqfarhad** [comment]
> There is a conflict in changelog

I just rebased my branch so it should be fine now

**Review by yeya24 — COMMENTED** [review]
Just noticed that the changelog entry seems wrong. It shouldn't be under `Fixed`. Should be `Added` instead as it is a feature/enhancement.

**Comment by eqfarhad** [comment]
> Just noticed that the changelog entry seems wrong. It shouldn't be under `Fixed`. Should be `Added` instead as it is a feature/enhancement.

I've opened a new PR to fix the changelog position;
+ https://github.com/thanos-io/thanos/pull/7423

**Pull request merged**
