### PR TITLE
Add Table of Contents for the Operating Page

### PR DESCRIPTION
**Pull request by yashrsharma44**
Signed-off-by: Yash <yashrsharma44@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

* Added Table of Contents
* Fixed some spelling mistakes and Grammar
* Fixed markdown order

## Verification
Tested locally

### CODE REVIEW

**Comment by povilasv** [comment]
Looks like linkings in TOC are not working. You can test in  https://deploy-preview-2656--thanos-io.netlify.app/operating/troubleshooting.md/

**Comment by yashrsharma44** [comment]
Weird, I tested in my vscode and it seems to be working, let me fix that up!

**Comment by bwplotka** [comment]
Can we instead aim for automatic tool as per https://github.com/thanos-io/thanos/pull/2689 ? (: 

@yashrsharma44 @povilasv @soniasingla

**Comment by soniasingla** [comment]
@yashrsharma44 @bwplotka @povilasv 

As I'm working on the automation already, I believe we can avoid adding toc manually, wdyt? :)

**Comment by yashrsharma44** [comment]
Great! If we can automate the process, that would certainly remove the manual work involved. +1 for this!

**Pull request closed without merging**
