### PR TITLE
[docs] Update blogs and talks section

### PR DESCRIPTION
**Pull request by matej-g**
* [ ] I added CHANGELOG entry for this change.
* [X] Change is not relevant to the end user.

## Changes

Updating the blogs and talks section with more talks.

Reorganizes the talks section to have same formatting as blogs.

### CODE REVIEW

**Review by saswatamcode — DISMISSED** [review]
LGTM! Thanks for updating! ❤️

**Comment by fpetkovski** [comment]
Do we want to add talks from the latest PromCon?

**Comment by matej-g** [comment]
> Do we want to add talks from the latest PromCon?

Sure thing, which ones do you mean? The one on new PromQL engine? For now I have looked only for "strictly Thanos" talks, but it would make sense to add related talks as well.

**Comment by fpetkovski** [comment]
I was actually thinking the one about MaaS for the masses  ):

**Comment by matej-g** [comment]
@fpetkovski hm yes, that talk was intentionally a bit broader to include other projects as well, but it does talks about Thanos quite a bit. What do you think @saswatamcode @moadz?

**Comment by saswatamcode** [comment]
Let's add it, gives people an idea about usage! 🙂

**Pull request merged**
