### PR TITLE
gate: allow disabling max concurrent

### PR DESCRIPTION
**Pull request by GiedriusS**
Allow disabling max concurrency limit by setting limit to <= 0. Previously it was impossible to disable this limit.

Signed-off-by: Giedrius Statkevičius <giedrius.statkevicius@vinted.com>

### CODE REVIEW

**Review by fpetkovski — COMMENTED** [review]
I like this change, but I wonder if we should use `0` as the no-limit value? Or would it change the existing behavior in an incompatible way?

**Comment by GiedriusS** [comment]
I doubt it makes much sense to set the limit to 0 as it is because it effectively disables everything :smile: what would be the use-case for that? :shrug:

**Comment by fpetkovski** [comment]
In Golang the zero value is usually used to indicate no limit, e.g. setting a timeout of 0 would mean no timeout etc.. Also as you pointed out, making the semantics of `0` equal to "don't allow any request" makes no sense. This is why I thought we can use `0` to disable the limit my instantiating a noop gate.

**Review by fpetkovski — COMMENTED** [review]
Ok nevermind, I just noticed that this is already covered because the condition is `<=` :) 

LGTM

**Review by fpetkovski — APPROVED** [review]

**Review by matej-g — APPROVED** [review]

**Pull request merged**
