### PR TITLE
Fix query frontend regression on release v0.17.0

### PR DESCRIPTION
**Pull request by yeya24**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Fixes https://github.com/thanos-io/thanos/issues/3465

Changes:
1. Cherry pick https://github.com/thanos-io/thanos/pull/3444
2. Fix series ordering when merging multiple series
3. Add more unit tests and update E2E for this regression

### CODE REVIEW

**Comment by yeya24** [comment]
Umm, I don't know how can I update the changelog since there is no section for v0.17.0. Do I need to add the change to the unreleased part?

**Comment by trynity** [comment]
Just hit this today, anything I can help with to ensure this gets merged and a hotfix is released?

**Comment by bwplotka** [comment]
Correct @yeya24 - we will create v0.17.1 section from it. cc @metalmatze

**Review by bwplotka — APPROVED** [review]
LGTM! Thanks :muscle:

**Pull request merged**
