### PR TITLE
packaging alertmanager sets and add a tests.

### PR DESCRIPTION
**Pull request by johncming**
packaging alertmanager sets and add a tests.

### CODE REVIEW

**Comment by bwplotka** [comment]
Hi, 

Thanks for looking into this and please be aware of this work: https://github.com/thanos-io/thanos/pull/1838 which changes a lot and adds tests as well (:

**Comment by bwplotka** [comment]
Can you rebase? (:

**Comment by johncming** [comment]
> Can you rebase? (:

Yes.

**Comment by simonpasquier** [comment]
@johncming the code has evolved a lot on the `master` branch. I'm not sure this PR is relevant anymore.

**Pull request closed without merging**
