### PR TITLE
port codebase to adapt to new thanos errors pkg replacing github.com/pkg/errors

### LINKED ISSUE #5176: Find replacement for https://github.com/pkg/errors
https://github.com/pkg/errors is now archived since `errors` package has a way to wrap errors AND the main maintainer is stepping down from the maintainer team. Here are details https://github.com/pkg/errors/issues/245

Unfortunately, default library `errors` wrapping is not the best. Personally, I don't like three facts: 

* It requires doing `fmt.Errors("something: %w", err)` with `%w` which is ultra-easy to forgot and do %v instead. There are linters for that, but add extra lint when our language is compiled... feels weird. Plus it is prone to inconsistent wrapping.
* Doing `errors.New` sometimes then relying on `fmt` to wrap errors does not look clean. Swapping between `fmt` and `errors` in return looks like unnecessary complexity for the reader.
* There is no stack trace functionality which we use heavily https://github.com/thanos-io/thanos/blob/main/cmd/thanos/main.go#L131

Options:

A. We could write our own wrapper over `errors` to accomplish this, borrowing some code from pkg/errors, but it is (especially stack tracing) a bit of complexity to the maintainer.
B. We could use other drop-in replacements https://github.com/emperror/errors - it was not touched lately but seems like not many issues are on it. The API is a bit large though.
C. We could live without stack trace functionality. This is what the majority of projects are doing lately.

I am not a fan of standard library flow as mentioned before, and I don't think we mind setting a new standards in the ecosystem (e.g with https://github.com/efficientgo/tools/tree/main/core). But for time being, maybe it makes sense to start with B and check how it goes first? 🤔 

Thoughts?

### PR DESCRIPTION
**Pull request by bisakhmondal**
In continuation of #5239 

Related Issue: closes #5176 

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

- Replace old github.com/pkg/errors import
- Update New,Errorf -> `Newf` and Wrap -> `Wrapf`
- Pr #5239, depends on `github.com/thanos-io/thanos/pkg/testutil` internal pkg leading to give rise of cyclic dependency - Fixed

Used the following snippet to automate the replacement and then a `make format` with manual imports ordering
```bash
for file in $(git grep -l "github.com/pkg/errors" | grep ".go"); do
  sed -i 's/errors\.Wrap(/errors\.Wrapf(/g' $file
  sed -i 's/errors\.Errorf(/errors\.Newf(/g' $file
  sed -i 's/errors\.New(/errors\.Newf(/g' $file
  sed -i 's/github\.com\/pkg\/errors/github\.com\/thanos-io\/thanos\/pkg\/errors/g'  $file
  echo "$file processing done"
done
```

## Verification
`make lint && make build` works successfully

### CODE REVIEW

**Comment by saswatamcode** [comment]
Thanks a lot for this effort! I wonder if we should do this port in one go, or split it component-wise somehow. 🙂 
Also, test failures seem related!

**Review by matej-g — COMMENTED** [review]
Looks good! I'm impartial as to whether we do this in one go or split by components or so. Since it's mechanical change, I'm fine with having it all here. However I'm also wondering if those failures are related :thinking:.

**Comment by saswatamcode** [comment]
Would you like to push this forward @bisakhmondal? 🙂

**Comment by matej-g** [comment]
What's the status of this?

**Comment by bisakhmondal** [comment]
the code has been ported to https://github.com/efficientgo/core
I think once @bwplotka finalizes the APIs there (had some double thoughts), I can clean it up with the new imports.
That's the plan, right? @bwplotka

**Comment by matej-g** [comment]
Still needed

**Pull request closed without merging**
