### PR TITLE
fixed grpc.ServerOption order to catch panic

### PR DESCRIPTION
**Pull request by Wander1024**
Signed-off-by: wander1024 <yawhua1024@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Verification
due to panic and recover atribute
we met the issue as #4080

### CODE REVIEW

**Comment by kakkoyun** [comment]
This seems pretty close to the finish line. Looking forward to it.

**Comment by yashrsharma44** [comment]
Seems like the linting tests are failing, can you run ` make lint` and `make docs`? Else the tests won't pass 😅

**Comment by Wander1024** [comment]
it's too strange.
I only modified 2 lines. just changed the positions.why docs and lint test failed.
I did `make lint` and `make docs`
`make docs` is passed.
but `make lint` get js error
```
/usr/local/lib/node_modules/yarn/lib/cli.js:46100
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
Makefile:91: recipe for target 'pkg/ui/react-app/node_modules' failed
```

**Review by bwplotka — APPROVED** [review]

**Comment by bwplotka** [comment]
Looks like it's passing on CI though?

**Comment by onprem** [comment]
I re-ran the tests and they passed :slightly_smiling_face:

**Pull request merged**
