### PR TITLE
Incorrect URL in step 1 katacode LTS

### PR DESCRIPTION
**Pull request by shaheedebrahim**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Modify URL so it points to the correct place!

## Verification

Tested by running the katacode myself and removing the URL and making sure that fixed the 404 I was receiving before!

### CODE REVIEW

**Review by squat — APPROVED** [review]
Looks great! Thank you :) we just need you to sign the DCO when commiting and then we can merge

Hint: `git commit --amend --signoff`

**Review by soniasingla — CHANGES_REQUESTED** [review]
@shaheedebrahim thanks for the PR, kindly take a look [here](https://github.com/thanos-io/thanos/pull/3687/checks?check_run_id=1632911172], this is how we sign DCO :) 
Let me know if you have any questions!

**Comment by soniasingla** [comment]
Also, can you please change the title of the PR, it's `katacoda` not `kata code`

**Comment by shaheedebrahim** [comment]
> Also, can you please change the title of the PR, it's `katacoda` not `kata code`

Yes! Sorry about that, and hopefully I signed it properly now. Although I noticed I signed the merge which might not be exactly what you wanted. Can rebase and force push so the commits are cleaner if necessary thanks 👍

**Comment by soniasingla** [comment]
Seems the last commit was not signed off, check [this](https://github.com/thanos-io/thanos/pull/3687/checks?check_run_id=1640532017) out and push again!

**Comment by bwplotka** [comment]
Any chances for fixing DCO? 🤗

**Pull request closed without merging**
