### PR TITLE
query: pass queryURL along to the UI

### PR DESCRIPTION
**Pull request by GiedriusS**
## Changes

Pass `queryURL` to the UI to have proper URLs in the React UI. Without
this, all URLs are set to `http://localhost:10902` i.e. the default
value set in `config.ts`.

* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Verification

Started Thanos via the quickstart script and checked that http://localhost:10904/rules, for example, has proper, clickable URLs.

### CODE REVIEW

**Comment by GiedriusS** [comment]
@squat this is needed for the next version to avoid broken links in targets/rules pages because the link is `http://localhost:10902` everywhere because `queryURL` is not set ;P

**Review by squat — DISMISSED** [review]

**Comment by squat** [comment]
@GiedriusS can you rebase and we can merge?

**Comment by GiedriusS** [comment]
> @GiedriusS can you rebase and we can merge?

Done :+1:

**Review by yeya24 — APPROVED** [review]
LGTM

**Comment by yeya24** [comment]
Not sure why but after merging this, the changelog for https://github.com/thanos-io/thanos/pull/4848 is missing.

**Pull request merged**
