### PR TITLE
Send sorted series from Receiver

### PR DESCRIPTION
**Pull request by fpetkovski**
Thanos Receivers currently send series in unsorted order, which the store proxy from sorting on the fly using the k-way merge heap. As a result, the querier has to do an explicit global sort before deduplication.

This commit changes the series select call in the Receiver and Ruler to request series in sorted order. It also adds a field to the info message of each store which indicates whether the store sends series in sorted order.

This field can be used for backwards compatibility once the global sort is removed in the querier. We also have external stores which might not send data in sorted order, for which this field will be set to false.

Signed-off-by: Filip Petkovski <filip.petkovsky@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

* Send series in sorted order from Receivers.

## Verification

* Relying on unit tests from here: https://github.com/thanos-io/thanos/pull/5692#discussion_r975499390.

### CODE REVIEW

**Review by GiedriusS — APPROVED** [review]
LGTM, just need to fix CI

**Comment by fpetkovski** [comment]
Thanks, CI should be green now.

**Review by GiedriusS — APPROVED** [review]
:+1: I think we should remove this field in 1.0

**Comment by fpetkovski** [comment]
My only concern is stores like https://github.com/G-Research/geras which might return unsorted series. Other than that, I agree that none of our stores should return unsorted data in the future.

**Pull request merged**
