### PR TITLE
Bump azure-storage-blob-go to v0.13.0

### PR DESCRIPTION
**Pull request by jesusvazquez**
Supersedes https://github.com/thanos-io/thanos/pull/4502

I'm trying to update `azure-pipeline-go` and `azure-storage-blob-go` in `grafana/loki` which vendors Thanos. Because of this I'll also try to update those two dependencies in Thanos. 

Since this PR is only updating dependencies, I figured it would not require filling out the usual sections. If otherwise please just let me know.

* [x] Change is not relevant to the end user.

## Changes

- Bumps `azure-pipeline-go` dependency form v0.2.2 to v0.2.3
- Bumps `azure-storage-blob-go` dependency from v.0.8.0 to v0.13.0
- Addresses library changes under `pkg/objstore/azure/azure.go`

## Verification

- Run repository tests

### CODE REVIEW

**Comment by jesusvazquez** [comment]
@GiedriusS could I take a look at this one? :pray: 

Not sure what to do about the CVEs that came up with the dependencies of the library that is being updated here.

**Comment by bwplotka** [comment]
Can you rebase? We merged https://github.com/thanos-io/thanos/pull/4397

**Review by bwplotka — APPROVED** [review]
LGTM, thanks!

**Comment by jesusvazquez** [comment]
Thank you!

**Pull request merged**
