### PR TITLE
fix bug: reloading rule files with empty group doesn't take effect

### PR DESCRIPTION
**Pull request by 00arthur00**
Signed-off-by: yapo.yang <yang_yapo@126.com>

reloading rule with empty group keep the orignal rules.
Steps to reproduce:
1. initialize rules with below yaml:
``` yaml
groups:
  - name: test-alert-group
    partial_response_strategy: "warn"
    interval: 2m
    rules:
      - alert: TestAlert
        expr: 1
        labels:
          key: value
        annotations:
          key: value

  - name: test-rule-group
    partial_response_strategy: "warn"
    interval: 2m
    rules:
      - record: test_metric
        expr: 1
```
2. change yaml to empty group:
``` yaml
groups: []
```
3. run http reload
``` bash
curl -X POST http://127.0.0.1:10902/-/reload
```
4. view rules in browser, thanos keeps the initial one instead of emty rule.

### CODE REVIEW

**Comment by 00arthur00** [comment]
Any update?

**Comment by 00arthur00** [comment]
@bwplotka ping

**Comment by simonpasquier** [comment]
FWIW this is fixing the same issue than https://github.com/thanos-io/thanos/pull/1439.

**Comment by 00arthur00** [comment]
> FWIW this is fixing the same issue than #1439 
#1439 doesn't fix the issue I metioned.  I verified just now with commit 9b17ba18f8bb2d3ad9bd8ce2ac00e18430665655. 

@simonpasquier

**Comment by simonpasquier** [comment]
@00arthur00 The PR I linked (#1439) isn't merged yet so if you've tested with `master`, yes the bug is still there.

**Comment by 00arthur00** [comment]
> @00arthur00 The PR I linked (#1439) isn't merged yet so if you've tested with `master`, yes the bug is still there.

@simonpasquier Thanks. Since the issue is being fixed. I will close the issue.

**Pull request closed without merging**
