### PR TITLE
store: fix missing flush when handling pushed down queries

### PR DESCRIPTION
**Pull request by MichaHoffmann**
In the case that we have pushed down queries and internal labels that are overriden by external labels we are not flushing the sorted response.

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Added the missing flush to the prometheus proxy store.

## Verification

Added a unittest for conflicting internal and external labels to hit the code path that is missing the flush.

### CODE REVIEW

**Comment by MichaHoffmann** [comment]
Without the flush: 

```
$ go test . -run TestPrometheusStore_Series_e2e -v
=== RUN   TestPrometheusStore_Series_e2e
    testutil.go:91: prometheus_test.go:169: ""

        	exp: 1

        	got: 0

--- FAIL: TestPrometheusStore_Series_e2e (2.52s)
FAIL
FAIL	github.com/thanos-io/thanos/pkg/store	2.559s
FAIL
```

**Review by fpetkovski — APPROVED** [review]
Thanks for the fix 👍

**Review by yeya24 — APPROVED** [review]

**Review by GiedriusS — APPROVED** [review]

**Comment by saswatamcode** [comment]
This should probably go in with v0.32!

**Review by saswatamcode — APPROVED** [review]
Will cherry-pick this in another rc!

**Pull request merged**
