### PR TITLE
Added thanos logo in react-app navbar

### LINKED ISSUE #5121: UI: Add Thanos Logo in the navbar
It would be cool to have the Thanos logo in the top navbar of the UI.
It doesn't look like the logo is somewhere in the UI and displaying in the top navbar is pretty common.

### PR DESCRIPTION
**Pull request by hackeramitkumar**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

Fixes #5121
## Changes
Added thanos logo in react-app navbar

## Verification
Tested on localhost

Screenshot from 2023-04-05 19-11-24

### CODE REVIEW

**Review by Akshit42-hue — COMMENTED** [review]
Hey @hackeramitkumar, Thanks for the PR. Can you please sign the DCO

**Comment by hackeramitkumar** [comment]
> Hey @hackeramitkumar, Thanks for the PR. Can you please sign the DCO

@Akshit42-hue thanks, 
I did that now.

**Review by fpetkovski — APPROVED** [review]
Nice, thanks.

**Review by yeya24 — APPROVED** [review]
Thanks!

**Pull request merged**
