### PR TITLE
Upgrade golang to 1.17

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: clyang82 <chuyang@redhat.com>

* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Golang 1.15 is now at end of life - https://endoflife.date/go

### CODE REVIEW

**Comment by saswatamcode** [comment]
I think lint fails due to: https://github.com/fatih/faillint/issues/24.

**Comment by saswatamcode** [comment]
@clyang82 you can now pull the latest version of `faillint` as the fix has been merged with: `bingo get github.com/fatih/faillint@v1.8.0` 🙂

**Comment by clyang82** [comment]
> @clyang82 you can now pull the latest version of `faillint` as the fix has been merged with: `bingo get github.com/fatih/faillint@v1.8.0` 🙂

 Updated. Thanks @saswatamcode for your help.

**Review by GiedriusS — APPROVED** [review]
Thx :heart:

**Pull request merged**
