### PR TITLE
Updaing README with drawing fixes and minor wording clarification

### PR DESCRIPTION
**Pull request by jkowall**
Signed-off-by: Jonah Kowall <jkowall@kowall.net>

I did not add a changelog for this simple update, but I can if you wish, just leave a comment. 

Feedback appreciated.

## Changes

This PR fixes up the readme and the diagrams to be more clear and consise on the deployment models with and without Kubernetes. Also fixes up the remote write side of things. Source drawings with full edit are here for the images embedded:

https://docs.google.com/drawings/d/1AiMc1qAjASMbtqL6PNs0r9-ynGoZ9LIAtf0b9PjILxw/edit?usp=sharing
https://docs.google.com/drawings/d/1iimTbcicKXqz0FYtSfz04JmmVFLVO9BjAjEzBm5538w/edit?usp=sharing

## Verification

View the Readme.md.

Context/discussion: https://cloud-native.slack.com/archives/CK5RSSC10/p1674215527890249?thread_ts=1674069893.558779&cid=CK5RSSC10

### CODE REVIEW

**Review by bwplotka — DISMISSED** [review]
This is solid. Thanks! 💪🏽

**Comment by bwplotka** [comment]
Some nits we could do this PR:
* Modify https://github.com/thanos-io/thanos/blob/main/docs/quick-tutorial.md as well.
* We can add links to actual source of images in the markdown/HTML comment just in case too (: 

WDYT @jkowall ?

**Comment by jkowall** [comment]
> Some nits we could do this PR:
> 
> * Modify https://github.com/thanos-io/thanos/blob/main/docs/quick-tutorial.md as well.
> * We can add links to actual source of images in the markdown/HTML comment just in case too (:
> 
> WDYT @jkowall ?

Should be updated, good ideas!

**Comment by bwplotka** [comment]
Please run `make docs` and commit changes and we are good to go!

**Review by bwplotka — APPROVED** [review]
Thanks ❤️

**Pull request merged**
