### PR TITLE
Lizhewei: add ks3 objstore driver

### PR DESCRIPTION
**Pull request by lizw91**
## Changes
-  add ks3 objstore driver

## Verification
TestObjStore_AcceptanceTest_e2e Pass

### CODE REVIEW

**Comment by bwplotka** [comment]
When user should choose what?

**Comment by lizw91** [comment]
> Hi, can we hear some motivation behind this change? Is this alternative to S3 plugin we have? What's the advantage here?

ks3 is an object storage product developed by Beijing Kingsoft Cloud Network Co., Ltd. The original intention of submitting the code is not to replace s3, but to facilitate users who need to interface with ks3 storage.

**Comment by lizw91** [comment]
> When user should choose what?

Used in the case where the user is using thanos to interface to ks3 object storage

**Comment by bwplotka** [comment]
Ah, great, thanks! 

1. Do you mind adding documentation too on how to get access to this storage? Link official docs?
2. Are we sure that the existing S3 client does not work with Ks3? if not, why? 🤗 

Thanks!

**Comment by lizw91** [comment]
> * Do you mind adding documentation too on how to get access to this storage? Link official docs?
> * Are we sure that the existing S3 client does not work with Ks3? if not, why?

This is the official document address for KS3 storage：https://docs.ksyun.com/documents/38731

**Comment by lizw91** [comment]
> Ah, great, thanks!
> 
> 1. Do you mind adding documentation too on how to get access to this storage? Link official docs?
> 2. Are we sure that the existing S3 client does not work with Ks3? if not, why? 🤗
> 
> Thanks!

I made another pull request, [](https://github.com/thanos-io/thanos/pull/4635) , please close this request

**Pull request closed without merging**
