### PR TITLE
cacheutil: upgrade rueidis to 0.0.93 to fix https://github.com/rueian/rueidis/pull/170

### PR DESCRIPTION
**Pull request by rueian**
Hi @GiedriusS, @douglascamata, @yeya24,

A user reported a panic bug when using Thanos v0.30.1 with an old Redis here https://github.com/rueian/rueidis/issues/55#issuecomment-1407397484.

The bug is only possible to be triggered when the client-side caching is disabled and the first request to a Redis connection is timed out. So, if the client-side caching is enabled, then the bug will not be triggered.

A fix has been addressed in https://github.com/rueian/rueidis/pull/170 and this PR upgrades rueidis to v0.0.93 to apply it.

### CODE REVIEW

**Review by douglascamata — APPROVED** [review]
LGTM and thanks again for being so helpful, @rueian!

**Review by douglascamata — CHANGES_REQUESTED** [review]
Could you add a changelog entry, please? 🙏

**Review by yeya24 — COMMENTED** [review]
Yeah as mentioned by @douglascamata let's have a changelog entry! Otherwise LGTM.

**Comment by rueian** [comment]
Thanks @douglascamata, @yeya24! I have updated the CHANGELOG.md.

**Review by yeya24 — APPROVED** [review]

**Pull request merged**
