### PR TITLE
query: Add flag for specifying engine optimizers

### PR DESCRIPTION
**Pull request by saswatamcode**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

This PR adds a repeatable `--query.promql-engine.optimizers` flag which allows selecting the exact query plan optimizers to pass to new promql engine options. 

Also, bumps github.com/thanos-community/promql-engine to latest.

## Verification

Built/ran locally.

### CODE REVIEW

**Comment by fpetkovski** [comment]
I think this can be a slippery slope because some optimizers depend on others. For example, merge selectors depends on sort matchers. We also don't have proper documentation for optimizers so exposing the raw internals to the user can be confusing.

Maybe we want a boolean flag to disable default optimizers instead?

**Comment by saswatamcode** [comment]
That could work, but in that case what about optimizers like propagate matchers or any new ones which get added, that are not a default? In the future, I'd also like to explore the possibility of some custom pluggable optimizer that can be used with Thanos.
Maybe we should document the optimizers and have this flag point to the docs? Wdyt?

**Comment by fpetkovski** [comment]
Good question, ideally we want all optimizers in which we are confident in to be enabled by default. PropagateSelectors is not battle tested yet, so I wouldn't rush with enabling it right now.

So maybe we want a hidden flag to enable an optimizer?

**Comment by saswatamcode** [comment]
> So maybe we want a hidden flag to enable an optimizer?

Yeah this seems good let me try to modify the semantics a bit to fit this

**Pull request closed without merging**
