### PR TITLE
[Website] Fixed community button spacing for smaller devices

### PR DESCRIPTION
**Pull request by NikhilSharma03**
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Before Changes
Screenshot from 2021-12-25 19-40-36

## After Changes
Screenshot from 2021-12-25 19-40-39

### CODE REVIEW

**Review by saswatamcode — DISMISSED** [review]
Thanks for this! LGTM! 💫
Docs check is failing and fixed by #5000.

**Comment by squat** [comment]
Hi @NikhilSharma03, now that we've fixed the docs, can you rebase on main so that all checks pass for your PR?

**Comment by NikhilSharma03** [comment]
@squat I tried pulling the latest changes and then rebased it to main. Still, it's not fixed :thinking: . Could you please help if the steps are wrong? Thank you.

**Review by squat — APPROVED** [review]

**Comment by squat** [comment]
Thanks!!

**Pull request merged**
