### PR TITLE
Merge release 0.18

### PR DESCRIPTION
**Pull request by squat**
This merges the v0.18.0 release branch back into master. It needed to be merged on the CLI vs just in a PR due to merge conflicts.

cc @thanos-io/thanos-maintainers

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Amazing, thanks for this. 👍🏽  LGTM.

Especially changelog is quite hard to craft, we need some automation asap.

**Comment by bwplotka** [comment]
https://twitter.com/bwplotka/status/1362018963262210048

**Comment by squat** [comment]
> Especially changelog is quite hard to craft, we need some automation asap.

Yes, big time, this is definitely not scaling well. I think there are some existing github apps/bots that can kind of manage this. Otherwise, we definitely should invest some time ourselves in developing a solution

**Comment by bwplotka** [comment]
Thanks!

**Pull request merged**
