### PR TITLE
TraceID : Fetching TraceID

### PR DESCRIPTION
**Pull request by Vanshikav123**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

In continuation with the issue #6774  and #6797 PR
Screenshot from 2023-12-11 18-26-08

### CODE REVIEW

**Comment by yeya24** [comment]
Hi @Vanshikav123, overall code change looks to me. Thanks!
Please run `make assets` or `make asset` to regenerate the static files.

**Comment by Vanshikav123** [comment]
> Hi @Vanshikav123, overall code change looks to me. Thanks! Please run `make assets` or `make asset` to regenerate the static files.

I don't know what is the issue , I have generated the static file earlier but now when i try to run it , it shows `make: *** No rule to make target 'assets'.  Stop.`  I also tried to run `make react-app`  to  to update `pkg/ui/static/`

**Comment by yeya24** [comment]
@Vanshikav123 sorry mb. Indeed there is no need to do `make asset` anymore as the command was removed recently.

**Comment by yeya24** [comment]
FYI unit tests failed. Not sure if it is flaky or it catched bug of the code

**Comment by Vanshikav123** [comment]
> FYI unit tests failed. Not sure if it is flaky or it catched bug of the code

I will recheck the error once again

**Comment by Vanshikav123** [comment]
Hello @yeya24  resolved the error can review now !

**Review by yeya24 — APPROVED** [review]
Thanks! Lgtm

**Pull request merged**
