### PR TITLE
UI: Add toggle to enable/disable metric autocomplete

### PR DESCRIPTION
**Pull request by ipstatic**
This change adds a toggle to enable or disable the metric autocomplete
functionality. By default it is enabled.

Signed-off-by: Jarod Watkins <jarod@42lines.net>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Added toggle to enable/disable metric autocomplete functionality in the new UI.

## Verification

Tested locally against production data.

### CODE REVIEW

**Review by GiedriusS — COMMENTED** [review]
Could you please do `make assets` and commit the result? We really need to fix the CI part here :(

**Comment by ipstatic** [comment]
> Could you please do `make assets` and commit the result? We really need to fix the CI part here :(

Done. No worries.

**Comment by ipstatic** [comment]
I also implemented this change "upstream" in [Prometheus](https://github.com/prometheus/prometheus/pull/8134)

**Review by bwplotka — APPROVED** [review]
LGTM! Can we have quick screenshot how this checkbox looks like? (: 

Thanks!

**Review by prmsrswt — APPROVED** [review]
Looks great. LGTM.
Thanks!

**Comment by ipstatic** [comment]
Oh I forgot to add a changelog entry! How should I correct?

**Comment by bwplotka** [comment]
That's fine, we can add later during release (:

Kind Regards,
Bartek Płotka (@bwplotka)

**Comment by ipstatic** [comment]
FYI I have created another PR to bring in changes suggested by Prometheus developers: #3391

**Pull request merged**
