### PR TITLE
Cut 0.23.2-rc.1

### PR DESCRIPTION
**Pull request by GiedriusS**
Cut 0.23.2-rc.1 :tada:

### CODE REVIEW

**Comment by squat** [comment]
Does this need to be rc.1?

**Comment by squat** [comment]
Since it's puking in another patch

**Comment by hanjm** [comment]
💪

**Comment by GiedriusS** [comment]
@squat @thanos-io/thanos-maintainers updated to be 0.23.2-rc.1

**Review by squat — APPROVED** [review]

**Pull request merged**
