### PR TITLE
Adds myself as triage member

### PR DESCRIPTION
**Pull request by wiardvanrij**
Signed-off-by: Wiard van Rij <wiard@outlook.com>

Adds myself to the triage list. 🎉 🎉

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Welcome! 💜

**Review by onprem — APPROVED** [review]
:tada:

**Review by kakkoyun — APPROVED** [review]
💜  🎉

**Comment by yashrsharma44** [comment]
🥳🥳

**Pull request merged**
