### PR TITLE
adding Toss to adopters

### PR DESCRIPTION
**Pull request by JacksChoco**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Comment by squat** [comment]
Hi @JacksChoco, looks good! can you please sign off the commit and then we can merge (:

**Comment by JacksChoco** [comment]
@squat Is this right?

**Comment by squat** [comment]
Hint: `git commit --amend --signoff`
(:

**Comment by JacksChoco** [comment]
Thanks!

**Pull request merged**
