### PR TITLE
ui: Add status page to other components

### LINKED ISSUE #3297: ui: Enable Status pages on the React UI for All components
There are two pages `Runtime and Build Information` and `CLI Flags` in the React UI which makes sense for all Thanos components. Currently, they are only shown in the navigation bar for Thanos Querier. We want to show links to these pages in the Navbar for all components.

### PR DESCRIPTION
**Pull request by Oghenebrume50**
Signed-off-by: Oghenebrume50 <raphlbrume@gmail.com>

Fixes #3297 
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes
Added the status dropdown with link to `Runtime and Build Information` and `CLI Flags` in other components

### CODE REVIEW

**Review by kakkoyun — APPROVED** [review]
LGTM. @prmsrswt Do we miss anything in here? Shall we merge it?

**Comment by prmsrswt** [comment]
@kakkoyun I was wondering the same. I am not sure why I haven't reviewed it yet, haha.

I'll take a look at it in some time but it's mostly looking good.

**Review by prmsrswt — COMMENTED** [review]
LGTM. This needs a rebase and then a run of `make assets`. Sorry for the delay on this.

**Comment by kakkoyun** [comment]
@Oghenebrume50 Let us know. If you need a hand on this.

**Review by onprem — APPROVED** [review]
LGTM!

**Comment by kakkoyun** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 
🌮 🌮 🌮 🌮

**Pull request merged**
