### PR TITLE
deps: bump minio-go to v6.0.44

### PR DESCRIPTION
**Pull request by ribbybibby**
This version includes https://github.com/minio/minio-go/commit/d18cd1c3fde63effb2eb789120abdc73da4a5610, which adds functionality I would like to use with Thanos.

### CODE REVIEW

**Comment by ribbybibby** [comment]
Ha, I guess it depends on your definition of interesting. 

This adds support for the environment variable `AWS_CONTAINER_CREDENTIALS_FULL_URI` which allows you to retrieve credentials from a generic local endpoint.

**Comment by ribbybibby** [comment]
Pushed an item to the CHANGELOG :+1:

**Comment by ribbybibby** [comment]
CHANGELOG'd

**Comment by bwplotka** [comment]
Yup, seen, just waited on CI (: Thanks.

**Comment by george-angel** [comment]
Not enough horn touted I'm afraid.

This change allows Thanos to hot reload AWS credentials.

We are running Vault deployment and a side-car helper with our AWS applications. Side-car uses Kubernetes SA as identity and provision temporary AWS keys and exposes them over http on localhost.

Thanos is now able to consume that http endpoint and use the temporary credentials provisioned by the sidecar. These credentials can be rotated as often as you want, 15 minutes, etc. without any disruption.

**Pull request merged**
