### PR TITLE
Added Shield in adopters

### PR DESCRIPTION
**Pull request by suhas-chikkanna**
Added Shield in adopters

### CODE REVIEW

**Review by yeya24 — DISMISSED** [review]
Thanks!

**Review by saswatamcode — DISMISSED** [review]
Thanks! Would you have a logo of your company, supported for light backgrounds?
Otherwise would show up as so on our website
Screenshot 2024-04-03 at 14 01 43

**Comment by suhas-chikkanna** [comment]
> Thanks! Would you have a logo of your company, supported for light backgrounds? Otherwise would show up as so on our website Screenshot 2024-04-03 at 14 01 43

shield_image

Thank you for Checking this., would the attached image here work well ?

**Comment by suhas-chikkanna** [comment]
> Yup it would!

Thank you so much! I uploaded the new image now :)

**Pull request merged**
