### PR TITLE
Updates minio-go to v7.0.37 from v7.0.32

### PR DESCRIPTION
**Pull request by davinci26**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

fixes https://github.com/thanos-io/thanos/issues/5701

Changelog: https://github.com/minio/minio-go/compare/v7.0.32...v7.0.37

Signed-off-by: Sotiris Nanopoulos <sotiris.nanopoulos@reddit.com>

## Verification

Unit/integration tests

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
LGTM

**Review by yeya24 — APPROVED** [review]
LGTM. @davinci26 For the minio issue you mentioned, how did you find it in Thanos? Are you just seeing goroutine leaks on the store gateway?

**Comment by SuperQ** [comment]
We're seeing `panic: send on closed channel`, which causes our Thanos Stores to crash.

**Comment by davinci26** [comment]
It surfaces as:

```
panic: send on closed channel

goroutine 10097536 [running]:
github.com/minio/minio-go/v7.(*Object).doGetRequest(_, {{0x0, 0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, 0x1, 0x1, ...})
  /go/pkg/mod/github.com/minio/minio-go/v7@v7.0.32-0.20220706200439-ef3e45ed9cdb/api-get-object.go:319 +0xdc
github.com/minio/minio-go/v7.(*Object).Read(0xc0b91441c0, {0x0?, 0x0?, 0x0?})
  /go/pkg/mod/github.com/minio/minio-go/v7@v7.0.32-0.20220706200439-ef3e45ed9cdb/api-get-object.go:399 +0x248
github.com/thanos-io/objstore/providers/s3.(*Bucket).getRange(0xc0004cbf90, {0x2586188, 0xc3d0ed7880}, {0xc015a4c870, 0x28}, 0x65900, 0x32c80)
  /go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20220715165016-ce338803bc1e/providers/s3/s3.go:428 +0x20e
github.com/thanos-io/objstore/providers/s3.(*Bucket).GetRange(0x7f97aa2f30d8?, {0x2586188?, 0xc3d0ed7880?}, {0xc015a4c870?, 0x0?}, 0x10000c00009cf00?, 0xc0b3934c68?)
  /go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20220715165016-ce338803bc1e/providers/s3/s3.go:445 +0x28
github.com/thanos-io/objstore.(*metricBucket).GetRange(0xc000b54540, {0x2586188, 0xc3d0ed7880}, {0xc015a4c870, 0x28}, 0x0?, 0x0?)
  /go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20220715165016-ce338803bc1e/objstore.go:526 +0xbd
github.com/thanos-io/objstore.TracingBucket.GetRange({{0x2596cf0?, 0xc000b54540?}}, {0x2586188?, 0xc3d0ed7880?}, {0xc015a4c870, 0x28}, 0x0?, 0x0?)
  /go/pkg/mod/github.com/thanos-io/objstore@v0.0.0-20220715165016-ce338803bc1e/tracing.go:50 +0x22c
github.com/thanos-io/thanos/pkg/store/cache.(*CachingBucket).fetchMissingSubranges.func1()
  /app/pkg/store/cache/caching_bucket.go:424 +0x103
golang.org/x/sync/errgroup.(*Group).Go.func1()
  /go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
  /go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errgroup/errgroup.go:72 +0xa5
```

Which I pattern match with https://github.com/minio/mc/issues/4202 but I also see goroutines spike to 2k as well.

image

**Review by squat — APPROVED** [review]
Nice find

**Comment by yeya24** [comment]
It is probably a little bit late. Do we still want to have a `v0.28.1` release for this fix?

**Comment by diranged** [comment]
We're seeing this fairly regularly... can we get a `v0.28.1` release with it?

**Comment by yeya24** [comment]
@diranged New release is out. Let me know if it works or not.

**Pull request merged**
