### PR TITLE
Updated readme link to prepend tip to fix Page Not Found; Disabled Liche temporarily. 

### PR DESCRIPTION
**Pull request by mllu**
* [ ] I added CHANGELOG entry for this change. (not sure which section to put under `Fixed` or `Changed`?)
* [ ] Change is not relevant to the end user.

## Changes

trying to fix the incorrect readme links that showing `Page Not Found` which were changed by this PR https://github.com/thanos-io/thanos/pull/2802/files#diff-6b3df26d750e09528185b365bbd99a76R72-R77 as shown below

Screen Shot 2020-08-24 at 10 18 05 PM

## Verification

click links from github readme

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Thank you!

**Comment by bwplotka** [comment]
CI is still failing though, do you mind running `make docs` and committing changes
?

**Comment by bwplotka** [comment]
I will do that for you if you don't mind (:

**Comment by mllu** [comment]
Ahh, thx, please help me, make docs acting weird to me, it delete t character at the end of each word.

**Comment by mllu** [comment]
Ahh, thx, please help me, make docs acting weird to me, it delete t character at the end of each word.

**Comment by mllu** [comment]
@bwplotka do you by any chance know what happen for failed CI checks? seems besides docs one, linter and end-to-end tests also failed.

**Comment by bwplotka** [comment]
Yea I am on it - unlucky day for CI ;p

**Comment by bwplotka** [comment]
Ok let's disable Liche we need long term fix now :/ Let's do this in separate PR and merge this on green. At least README links will be working

**Comment by mllu** [comment]
hope google will crawl the latest webpages update pagerank soon since they link to the old ones

**Pull request merged**
