### PR TITLE
Adding warning boxes in target

### LINKED ISSUE #6876: Show error if targets page is not fully loaded
Sometimes the targets page doesn't fully load because it takes too long to load targets from leaf nodes. In such cases, no error is shown and then the user doesn't know anything about this leading to confusion. Add a box with an error in such case.

### PR DESCRIPTION
**Pull request by harsh-ps-2003**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Fixes #6876 
by showing the [warnings](https://prometheus.io/docs/prometheus/latest/querying/api/#format-overview) available through Prometheus API response in form of error boxes in Target UI

## Verification

They are tested through unit tests! It is not possible to get fake warnings in the Prometheus API response, as warnings are only included in the response if there were warnings while executing the request. So programmatic tests are the only option!

### CODE REVIEW

**Comment by harsh-ps-2003** [comment]
Hey! @GiedriusS 
I tried to find a way to make a query so that the Prometheus API's response has warning in it, but unfortunately I am unable to do so, thus the PR is untested!! Sorry.

**Review by GiedriusS — COMMENTED** [review]
Have you seen https://github.com/thanos-io/thanos/pull/7036/files? Maybe you want to collaborate with them on tests?

**Comment by harsh-ps-2003** [comment]
> Have you seen https://github.com/thanos-io/thanos/pull/7036/files? Maybe you want to collaborate with them on tests?

We collaborated on the API code instead of the tests (I wrote the tests myself). Can you review please @GiedriusS

**Comment by kartikaysaxena** [comment]
But the API code was totally mine though 🤔

**Comment by harsh-ps-2003** [comment]
> But the API code was totally mine though 🤔

Absolutely! I wrote it in the message! Now I have also tagged you in the comment to give you sincere credit of your work! Thanks

**Comment by harsh-ps-2003** [comment]
Closed the PR as I was not able to manually test the UI.

**Pull request closed without merging**
