### PR TITLE
UI: fix error in graph panel component

### PR DESCRIPTION
**Pull request by Aman-Codes**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

- Fixed error in graph panel component. `ul` tag should have only `li` tag as child.

### Before:
image

### After:
image

### CODE REVIEW

**Comment by ianbillett** [comment]
Hey @Aman-Codes - thanks for this contribution :pray: To help us move this along, if this PR fixes an outstanding issue please can you link it? With UI changes it is helpful to provide actual screenshots of the UI rather than just the DOM, that way reviewers can see what the effect will be for end users :+1:

**Comment by Aman-Codes** [comment]
Hi @ianbillett  thanks for the review

Currently there is no open issue for this but if you want then I can create one for this.
In this fix there is no change on the UI which the end user could directly observe but it will improve the screen reader experience. 
HTML syntax errors are not reported in the console but could be check through Lighthouse Report.

**Steps to test this PR:** 
- Go to the Thanos query page
- Run any query and select the graph tag.
- Run the Lighthouse Report from the developer tools of the browser
- In the accessibility section this error is reported
image

Though we have **Eslint** and **Prettier** checks which could report html syntax error 
but **this is a case where the code looks like valid JSX syntax but the generated html from it is not valid.**

**Comment by ianbillett** [comment]
Ok cool - this sounds like a sensible change to make to improve accessibility.

@onprem I think it makes sense to merge this PR, but could you confirm?

**Comment by ianbillett** [comment]
still relevant

**Pull request closed without merging**
