### PR TITLE
Querier UI: Updating enable/disable metric automcomplete with upstream

### PR DESCRIPTION
**Pull request by ipstatic**
Bringing in changes suggested by Prometheus developers to keep in sync.
Also updated CHANGELOG.

Signed-off-by: Jarod Watkins <jarod@42lines.net>

### CODE REVIEW

**Comment by ipstatic** [comment]
FYI I attempted a `make assets` but it appears there was no change.

**Comment by prmsrswt** [comment]
> FYI I attempted a `make assets` but it appears there was no change.

Yeah, this happens sometimes, when `make` thinks that everything is already latest. Try running `scripts/build-react-app.sh` directly and then `make assets`.

**Comment by ipstatic** [comment]
That did it, thanks!

**Review by GiedriusS — APPROVED** [review]
Thanks!

**Comment by GiedriusS** [comment]
CircleCI does not want to cooperate today and simply returns 400 when trying to resubmit the payload for this pull request. The tests pass and everything looks good, thank you!

**Pull request merged**
