### PR TITLE
Expose store gateway query stats in series response hints

### PR DESCRIPTION
**Pull request by yeya24**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Fixes https://github.com/thanos-io/thanos/issues/6344.

Basically just add query stats in protobuf and expose it in Series API response.

### CODE REVIEW

**Review by SuperQ — DISMISSED** [review]
Very nice, Is this stuff that can be surfaced in Grafana?

**Comment by yeya24** [comment]
Grafana maybe not, but I think we can put those info to thanos UI.

**Review by GiedriusS — DISMISSED** [review]
I was wondering if it makes sense to move this functionality into the same `hintspb.QueryStats` but history shows (protobuf migration) that it is better to have some code duplication instead of hooking more stuff into generated structs :smile:

**Comment by yeya24** [comment]
@GiedriusS I am thinking about what kind of information should we expose here... https://github.com/thanos-io/thanos/pull/6340/files#diff-3e2896fafa6ff73509c77df2c4389b68828e02575bb4fb78b6c34bcfb922a7ceL1329 Removed the `cachedPostingsCompressionTimeSeconds` stats. I am thinking should we just expose stats like count, bytes size first?
I will exclude all time duration metrics as I feel they are not that useful as they are wall time basically https://cloud-native.slack.com/archives/CL25937SP/p1683868858845329

**Comment by GiedriusS** [comment]
:+1: I thought the requirements could be laxer on this part of the gRPC API. Maybe we could add a comment that this could change at any time? Also, how Cortex will use this functionality? Or is it for something else?

**Comment by yeya24** [comment]
> Also, how Cortex will use this functionality? Or is it for something else?

I am thinking about having this in Cortex but mainly for analysis purpose. It is also useful to understand how to set the downloaded bytes limit.

**Comment by yeya24** [comment]
PTAL again, I included query stats like size, count for now and excluded metrics like `duration`.

**Review by fpetkovski — APPROVED** [review]
lgtm

**Comment by yeya24** [comment]
Merging this now.

**Review by bwplotka — COMMENTED** [review]
Nice, thanks!

**Pull request merged**
