### PR TITLE
Makefile: Add missing linebreak

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

Fix below error:
```
$ make examples
/bin/sh: 2: Syntax error: end of file unexpected (expecting ")")
Makefile:365: recipe for target 'jsonnet-format' failed
make: *** [jsonnet-format] Error 2
```

### CODE REVIEW

**Comment by daixiang0** [comment]
sorry for my mistake :(

**Comment by daixiang0** [comment]
@squat how about putting it into `lint` target? Now our test does not include all target i think.

**Comment by bwplotka** [comment]
Yes I think @daixiang0 that would be nice (:

**Comment by daixiang0** [comment]
Add `examples` and `example-rules-lint` to `lint` target. It would re-generate examples and do check.

**Comment by daixiang0** [comment]
There is a confused issue about run `examples-in-container` in CircleCI since it works fine at local, need some time to fix it.

**Comment by daixiang0** [comment]
Fix by #2132

**Comment by kakkoyun** [comment]
@daixiang0 I hadn't realized that you already fixed this. Oops.

**Pull request closed without merging**
