### PR TITLE
Moved CI to dockerhub.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by bwplotka** [comment]
We will need to live with broken cross-build step: https://github.com/prometheus/promu/issues/182

**Comment by metalmatze** [comment]
Rather than changing everything over to another registry, I would say we should give some more time and the problem will resolve itself on its own (at least from our point of view).
We don't migrate off of GitHub just because it has issue (I know it's not really a good metaphor, but I hope it gets my point across).

**Comment by bwplotka** [comment]
It's was 5minute job, so why we cannot do it?

**Comment by bwplotka** [comment]
I am pretty sure it will come back soon, just as a project we don't care much

**Comment by metalmatze** [comment]
If you feel like it. Go ahead. Don't want to block. Just stated that it feels a bit rushed to me (although that might be my personal opinion). 😉

**Comment by bwplotka** [comment]
Looks like we are back, but let's keep this PR handy. It's not a such huge pain to more registries as it does not matter for this project. The only problem would be release, that's it.

**Pull request closed without merging**
