### PR TITLE
Changed fetcher and syncer Histogram metric to Observer

### PR DESCRIPTION
**Pull request by alexqyle**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Changed fetcher and syncer Histogram metric to Observer. So that depending project (ie. Cortex) could plug in HistogramVec with customized labels

### CODE REVIEW

**Review by yeya24 — APPROVED** [review]
LGTM

**Review by saswatamcode — APPROVED** [review]
LGTM!

**Review by matej-g — APPROVED** [review]

**Comment by fpetkovski** [comment]
The e2e test seems to be consistently failing. Could it be related to this change?

**Comment by matej-g** [comment]
I _think_ it's unrelated and because of the infamous https://github.com/thanos-io/thanos/issues/4866 😢 , not sure why it's popping up again so often

**Review by SuperQ — APPROVED** [review]

**Pull request merged**
