### PR TITLE
cmd/thanos/receive: fix close chan panic

### PR DESCRIPTION
**Pull request by squat**
This commit fixes a panic caused by sending on the chan which is closed
too early. This chan was closed when the setup func returned, rather
than when the group's goroutine returned.

Fixes: #1594
Signed-off-by: Lucas Servén Marín <lserven@gmail.com>

### CODE REVIEW

**Comment by dtrejod** [comment]
You also close the `uploadC` channel twice.

https://github.com/thanos-io/thanos/blob/6abe080c99dbf45a7e826565b5eb17d727a494ab/cmd/thanos/receive.go#L207
https://github.com/thanos-io/thanos/blob/6abe080c99dbf45a7e826565b5eb17d727a494ab/cmd/thanos/receive.go#L413

**Comment by squat** [comment]
Yes you’re totally right. This is an unrelated issue but a bug nonetheless. I’ll address this in the same pr

**Comment by dtrejod** [comment]
Confirmed these changes resolved the panics. However hit another issue where the TSDB doesn't start back up after a flush event. Looks to me this cancel call closes the `upload on demand` function prematurely --

https://github.com/thanos-io/thanos/blob/e7d8707c4e94ae10758980cd2de174fb5bab473e/cmd/thanos/receive.go#L422

**Comment by squat** [comment]
Yeah you’re right. That cancel is leftover from a previous iteration where the upload used a cancellable context and `cancel()` needed to be called after the upload to clean up.

**Pull request merged**
