### PR TITLE
*: Using native histograms for grpc middleware metrics

### PR DESCRIPTION
**Pull request by pedro-stanaka**
Since we updated the middleware library, we can now use native histograms to keep track of latencies in grpc calls.
This is a semi-breaking change if people enabled native histogram collection on their Prometheus monitoring Thanos instances.

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

* Update grpc middleware library to latest version
* Using native histograms for grpc middleware metrics (both server and client side).

## Verification

image

### CODE REVIEW

**Review by fpetkovski — DISMISSED** [review]

**Comment by fpetkovski** [comment]
Looks like the docs failure is legit.

**Comment by MichaHoffmann** [comment]
Can we still scrape classic histograms?

**Comment by pedro-stanaka** [comment]
> Can we still scrape classic histograms?

Yes, if someone either did not enable native histogram feature flag or has `scrape_classic_histograms: true` for the scrape job, the classic histogram will still be scraped.

**Review by MichaHoffmann — DISMISSED** [review]
lgtm

**Comment by MichaHoffmann** [comment]
If this breaking for some people then we should add the breaking emoji to the changelog probably

**Review by fpetkovski — APPROVED** [review]
Native histograms are opt-in, so there should be no breaking changes.

**Comment by MichaHoffmann** [comment]
> Native histograms are opt-in, so there should be no breaking changes.

Was just noting because the PR description mentioned that its semi-breaking

**Review by MichaHoffmann — APPROVED** [review]
lgtm

**Pull request merged**
