### PR TITLE
Adding Remote Write Capability to Thanos Ruler

### PR DESCRIPTION
**Pull request by sharadgaur**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes
This pull request will allow Thanos ruler to remote write recorded series and alert to the Cortex or any other remote TSDB. Added the following flags.

`--storage.remote.flush-deadline=1m`  #How long to wait flushing sample on shutdown or config reload.

`--storage.remote.config-file=<file-path>` # Path to YAML file that contains remote write configuration. 

`--storage.remote.config=<content>` Alternative to 'storage.remote.config-file' flag (lower priority). Content of YAML file that contains remote write configuration.

I would be very grateful for any feedback or suggestions.

### CODE REVIEW

**Review by kakkoyun — COMMENTED** [review]
Hey @sharadgaur, thanks a lot for the PR. 

There's another ongoing PR on this have you seen it? https://github.com/thanos-io/thanos/pull/3743 cc @metalmatze 

Also, we have a design document about the overall goal for the ruler. Have check it out? https://github.com/thanos-io/thanos/blob/main/docs/proposals/202005_scalable-rule-storage.md 
I wonder where your PR stands concerning it.

**Comment by sharadgaur** [comment]
@kakkoyun thank you for the quick reply. 
Sorry I was not aware of both. I should have researched before making the PR :). 
I am going to close this PR.

Do you have ETA on #3743?

**Comment by hooten** [comment]
@sharadgaur since https://github.com/thanos-io/thanos/pull/3743 was closed, can you resubmit this PR?

**Comment by yeya24** [comment]
Is this pr still valid?

**Comment by GiedriusS** [comment]
With stateless ruler in place, I think we can close this one.

**Comment by m-messiah** [comment]
yes, https://thanos.io/tip/components/rule.md/#stateless-ruler-via-remote-write sounds what we need.
Just one question - it says ruler becomes stateless with this flag - is it possible to keep it stateful with all data present, but use remote-write as an additional functionality?

**Comment by yeya24** [comment]
> 

This is not possible with the agent mode for now. It will remove data from the wal once the data is sent to the remote targets. 
Sounds like you need a prometheus with remote write configurable, but use Thanos Query as your query data source. I guess it is not possible right now.

**Pull request closed without merging**
