### PR TITLE
sidecar: fix limit mintime

### PR DESCRIPTION
**Pull request by MichaHoffmann**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Review by pedro-stanaka — APPROVED** [review]

**Comment by fpetkovski** [comment]
Can you add some description how this fixes the issue?

**Comment by MichaHoffmann** [comment]
> Can you add some description how this fixes the issue?

It was just a bug, the limit is supposed to be lower bound and I treated it as upper bound

**Review by fpetkovski — APPROVED** [review]

**Review by yeya24 — APPROVED** [review]
Should we cut a new release?

**Comment by MichaHoffmann** [comment]
> Should we cut a new release?

i think yes, its not a great bug

**Review by saswatamcode — APPROVED** [review]

**Pull request merged**
