### PR TITLE
Fixed Page Not Found Error

### PR DESCRIPTION
**Pull request by sennatitcomb**
Signed-off-by: Senna Titcomb sennatitcomb@gmail.com

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Comment by saswatamcode** [comment]
Hi! This looks good to me! Can you just sign the DCO so that this can be merged?

**Review by bwplotka — APPROVED** [review]

**Comment by bwplotka** [comment]
We need DCO fix, yes. Thanks!

**Comment by sennatitcomb** [comment]
Signed-off-by: Senna Titcomb sennatitcomb@gmail.com

**Comment by sennatitcomb** [comment]
Closing request in favor of #4647

**Pull request closed without merging**
