### PR TITLE
Website: fixed linking issue for v016 docs on website

### PR DESCRIPTION
**Pull request by thisisobate**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes
fixed linking issue for v016 docs on website.

### CODE REVIEW

**Comment by thisisobate** [comment]
PTAL: @bwplotka @squat @prmsrswt

**Review by squat — APPROVED** [review]

**Comment by squat** [comment]
Is this a dupe of #3258? Do we need this in the 0.15 docs too? Maybe we can rather merge this into the release branch. and then merge the release branch into master as part of our regular release flow

**Comment by thisisobate** [comment]
This is beneficial for only future releases. #3258 was made specifically for release-0.16 docs because it has already been cut from master so `aliases` frontmatter settings can't be found in release-0.16 docs.

**Comment by thisisobate** [comment]
I think we should consider merging #3258 to master before we could consider this PR since #3258 promises to solve the problem at hand.

Also, couldn't view netlify preview in checks so I don't know if it's right to merge #3258

**Review by bwplotka — CHANGES_REQUESTED** [review]
This is bit tedious. What's wrong with the approach on hugo.yaml?

**Comment by thisisobate** [comment]
I tried the approach on hugo.yaml but it wasn't working. 

This was what I did: 
```
v0.16: "/:section /:filename.md" 

```

**Review by bwplotka — APPROVED** [review]

**Comment by bwplotka** [comment]
This is it! Good for quick short term fix :+1:

**Pull request merged**
