### PR TITLE
.*: Remove duplicate log.level arg in quickstart.sh

### PR DESCRIPTION
**Pull request by richardpoole**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

- Remove duplicate log.level arg in quickstart.sh

## Verification

- Not tested

### CODE REVIEW

**Comment by GiedriusS** [comment]
Why is this a draft? The CI failure seems unrelated. Add the DCO please and I think this should be good to go. Thanks for your contribution and welcome to Thanos! (:

**Comment by richardpoole** [comment]
Sorry, was going to make subsequent changelog update but got distracted with work. I’ll unmark as draft if that’s not necessary.

**Comment by richardpoole** [comment]
@GiedriusS Done :)

**Comment by squat** [comment]
Looks good :) please sign the DCO (`git commit --amend --signoff`) and then we can merge

**Comment by richardpoole** [comment]
@squat DCO signed :)

**Comment by squat** [comment]
It looks like your signature and commit are using two different identities. The check is failing with:

```
Commit sha: 619d13a, Author: Richard Poole, Committer: Richard Poole; Expected "Richard Poole richard.poole@cudoventures.com", but got "Richard Poole richard@sycora.com".
```

**Pull request merged**
