### PR TITLE
Stepping back from Thanos maintainers

### PR DESCRIPTION
**Pull request by pracucci**
I'm stepping back from Thanos maintainers. Unfortunately I don't have time to follow Thanos dev and community, and I think it's just unfair keep wearing this hat.

Let me just say I ❤️  Thanos community and project! Vibrant, active, nice people. I learned a lot from all of you, thanks!

### CODE REVIEW

**Review by GiedriusS — COMMENTED** [review]
j2UBgn1K_400x400
Could you add yourself to the "Previous Maintainers" list as well? :cry:

**Review by bwplotka — DISMISSED** [review]
Thanks, Marco for all your work and all the best for the future! 💪🏽 

Do you want to add yourself to the Previous Maintainers list? 🤗 https://github.com/thanos-io/thanos/blob/07447b917cc628411995aada3969b1bfa6fc78fa/MAINTAINERS.md#previous-maintainers

**Comment by pracucci** [comment]
> Do you want to add yourself to the Previous Maintainers list?

Yep, done!

**Review by GiedriusS — APPROVED** [review]
Thanks for all of your hard work! It is really appreciated. Good luck in the future :cry: :muscle:

**Review by bwplotka — APPROVED** [review]

**Review by metalmatze — APPROVED** [review]
Sad to approve this. Thanks for all you amazing contributions!

**Comment by kakkoyun** [comment]
Nooo, it's unfortunate to see that you're leaving. Thanks for everything you have done!

**Review by squat — APPROVED** [review]
:(

**Pull request merged**
