### PR TITLE
Add query-frontend.max-body-size to correctly parse query response body

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <yb532204897@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

Fixes https://github.com/thanos-io/thanos/issues/3113

This pr bumps Cortex dependency. 

Prometheus is updated to commit https://github.com/prometheus/prometheus/commits/master?before=daf382e4a9f5ca380b2b662c8e60755a56675f14+35&branch=master.

### CODE REVIEW

**Comment by GiedriusS** [comment]
I'm thinking maybe we need to provide more guidance on this parameter, in the docs somewhere? It will be probably unclear from the help message to our users. When should this value be changed? If it shouldn't then maybe it shouldn't be tunable at all?

**Comment by yeya24** [comment]
@GiedriusS Thanks! This makes sense. 

Based on the original [pr](https://github.com/cortexproject/cortex/commit/747d5950481b859c80c1d6727a2066a5f1e2f02c#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR51), now query frontend reads every request and this flag is used to control the max request body size to read.

This will be useful when a POST request body exceeds 10MB. Umm, do you think it is good to be tunable? Maybe I should make it not tunable since 10MB is a very large number for the request body I think.

**Comment by yeya24** [comment]
I updated the pr and removed that flag. PTAL again, thanks!

**Review by bwplotka — APPROVED** [review]
Thanks! :+1: 

e2e tests fails only.

**Comment by yeya24** [comment]
That e2e test case seems flaky. Will take a look later.

**Comment by bwplotka** [comment]
LGTM!

**Pull request merged**
