### PR TITLE
Enabled index-header under experimental flag.

### PR DESCRIPTION
**Pull request by bwplotka**
Depends on: https://github.com/thanos-io/thanos/pull/1952

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by bwplotka** [comment]
FYI @squat  This is chained PR, chained against https://github.com/thanos-io/thanos/pull/1952 which has to be reviewed first to be merged (: 

I think for the experimental flag it's fine to not have CHANGELOG. Doc was added to https://github.com/thanos-io/thanos/pull/1952, let me know there if something is missing...

**Comment by squat** [comment]
Yes but I mean the generated document for the cli flags. That has to be merged simultaneously with this change, no?

**Comment by bwplotka** [comment]
.. or after.

It's hidden flag, so CI is not crying for lack of generated docs.

**Comment by bwplotka** [comment]
But still, some integration tests are failing, need to investigate after holidays (in week time) (:

Anyway, the https://github.com/thanos-io/thanos/pull/1952 should be ready for review.

**Comment by bwplotka** [comment]
Actually let's merge one into another, will be easier to merge and see integration tests results.

**Pull request merged**
