### PR TITLE
Bump cm-promql to v0.15.0

### PR DESCRIPTION
**Pull request by Nexucis**
* upgrade `codemirror-promql` to [v0.15.0](https://github.com/prometheus-community/codemirror-promql/releases/tag/0.15.0)
* inject the `metricNames` in the `PromQLExtension`
* update the import paths accordingly to the changes provided by this new release.
* I also took the opportunity to move the `@types` packages from the dependencies list to the dev-dependencies. I hope you don't mind that I did it.
the `@types/` packages are only used for the development, and not used to run the webapp. So these should move to the dev-dependencies part.

This PR synchronizes the changes performed on Prometheus side through the PRs https://github.com/prometheus/prometheus/pull/8706 and https://github.com/prometheus/prometheus/pull/8719

### CODE REVIEW

**Review by bwplotka — APPROVED** [review]
Thank you so much for this work. We really appreciate this work 🤗 

At one point... would like to help us maintaining Thanos on UI side?

**Comment by Nexucis** [comment]
Oh cool thanks @bwplotka. 

> At one point... would like to help us maintaining Thanos on UI side?

Maybe it could be nice at some point, but maybe before saying a definitive yes, it would be nice to know what is the expectations and what does it mean to do that :D.

**Comment by bwplotka** [comment]
You can always chat with us about those things on our CNCF Slack with @onprem (`@Prem Saraswat` on Slack, maintainer currently the most familiar of frontend part) and me (`@bwplotka` on Slack) 🤗 

Also: https://thanos.io/tip/thanos/maintainers.md/#how-to-be-maintainer

**Comment by bwplotka** [comment]
> You can always chat with us about those things on our CNCF Slack with @onprem (`@Prem Saraswat` on Slack, maintainer currently the most familiar of frontend part) and me (`@bwplotka` on Slack) 🤗 

And anyone else interested to help in any part of Thanos project!

**Pull request merged**
