### PR TITLE
Updated agent tutorial with important meme and beta tag.

### PR DESCRIPTION
**Pull request by bwplotka**
image

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

### CODE REVIEW

**Review by GiedriusS — COMMENTED** [review]
There's a typo: it should be "running", not "runnig" :smile:

**Comment by bwplotka** [comment]
Thx! I am waiting for beta tag to be available today.

**Review by moadz — APPROVED** [review]
LGTM

**Review by matej-g — APPROVED** [review]
So glad this important meme finally lands in the code base :bat:

**Pull request merged**
