### PR TITLE
e2e tests: Move to `efficientgo/e2e`

### PR DESCRIPTION
**Pull request by matej-g**
* [ ] I added CHANGELOG entry for this change.
* [X] Change is not relevant to the end user.

## Changes

This PR moves Thanos e2e test suite to https://github.com/efficientgo/e2e, in line with the aims set out in https://github.com/thanos-io/thanos/issues/3832#issuecomment-785823600 and https://github.com/thanos-io/thanos/issues/4579

This is a relatively large changeset, but keep in mind most of this is 'mechanical' replacement. Most crucial changes are done to the `e2ethanos` package, rest of the tests then follow these changes. Other notable changes:
- Reverse proxies from the host for receive multitenancy test have been replaced by Docker services (more robust, host is not available from container on `172.17.0.1` on every setup)
- I included a custom function to instantiate Minio, which is a workaround for issue https://github.com/efficientgo/e2e/issues/11 (should be removed after this is resolved)

## Verification

Running E2E tests locally.

### CODE REVIEW

**Comment by yeya24** [comment]
@matej-g Is this ready for review now 😄

**Comment by matej-g** [comment]
> @matej-g Is this ready for review now

Hey @yeya24, please see my comment in https://github.com/thanos-io/thanos/issues/4579#issuecomment-907289744 and the subsequent comment. The summary - this is open to review / feedback, but I did not wanted to undraft this until I fully understand the issue and to be sure the tests will not be flaking.

**Review by yeya24 — APPROVED** [review]
LGTM! Thanks for the great work!

**Review by bwplotka — APPROVED** [review]
Amazing work 🤗 

Must have been been tedious, but we get this done, thanks!

**Pull request merged**
