### PR TITLE
unify and tidy objstore setup for azure, bos and oss

### PR DESCRIPTION
**Pull request by Nicholaswang**
Signed-off-by: Nicholaswang <wzhever@gmail.com>

 Change is not relevant to the end user.

## Changes
1, add NewBucketWithConfig func for azure, bos and oss to keep updated with cos and s3
2, add config validate func for loss

### CODE REVIEW

**Comment by yeya24** [comment]
cc @hanjm, can you please help review this one?

**Comment by hanjm** [comment]
LGTM

ci tests flaky, just retrigger it.

**Comment by Nicholaswang** [comment]
@yeya24 @hanjm Any ideas to retrigger the ci?

**Comment by hanjm** [comment]
> @yeya24 @hanjm Any ideas to retrigger the ci?

git rebase -i main && git push -f

**Comment by Nicholaswang** [comment]
企业微信截图_1646135115731

seems like this is reproducible. Is anything wrong with the ci running environment?

**Comment by hanjm** [comment]
hi @Nicholaswang, you can run `make go-lint` in local . and see what change about `oss.go`. :)

**Pull request closed without merging**
