### PR TITLE
add external url

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

* [x] Change is not relevant to the end user.

## Changes

Add exteral url for prometheus instance to support all links work.
For now, many link in prometheus UI return 523(can not reach).

### CODE REVIEW

**Comment by daixiang0** [comment]
Not sure need to add init changlog or not, but it is a good feature for beginners.

**Comment by bwplotka** [comment]
Nice! Can you show the preview for this? You can hook your repo following this: https://github.com/thanos-io/thanos/pull/1803

**Comment by daixiang0** [comment]
please look at https://katacoda.com/daixiang/courses/thanos/1-globalview.
For now, you can view all metircs in target page.

**Comment by bwplotka** [comment]
Nice! Do you mind bumping Thanos image to v0.9.0-rc.0 (:

**Comment by daixiang0** [comment]
@bwplotka done.

**Comment by daixiang0** [comment]
Need to update changelog?

**Comment by daixiang0** [comment]
I wanted to change it but find it is under thanos repo, is it also mirrored with official version?

**Comment by bwplotka** [comment]
Yes, we should switch to official `quay.io/prometheus/prometheus` (:

**Comment by daixiang0** [comment]
done.

**Comment by bwplotka** [comment]
Thanks!

**Comment by bwplotka** [comment]
Now is time to add new tutorials.

**Comment by daixiang0** [comment]
> Now is time to add new tutorials.

happy to wait!

**Pull request merged**
