### PR TITLE
query: Added tests for compatiblity for old components without InfoAPI.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by bwplotka** [comment]
Blocks release,

**Comment by bwplotka** [comment]
cc @hitanshu-mehta , working on fix now, should be easy.

**Comment by bwplotka** [comment]
Added tests that confirms... all is good XD

**Comment by bwplotka** [comment]
Just extra tests if we want them to ensure compatibility (:

**Review by GiedriusS — APPROVED** [review]
:+1:

**Review by yeya24 — APPROVED** [review]
LGTM

**Pull request merged**
