### PR TITLE
Vulnerability in external dependencies

### PR DESCRIPTION
**Pull request by Akshit42-hue**
Signed-off-by: Akshit42-hue <patelakshit2025@gmail.com>

## Changes
There are vulnerabilities in external dependency while using govulncheck.
I have updated that dependency

Screenshot
Thanos_vul

### CODE REVIEW

**Comment by Akshit42-hue** [comment]
cc @saswatamcode

**Comment by squat** [comment]
Hi Axit, please check CI, there's a diff with the go.sum causing the
failure.

-Lucas

Axit Patel ***@***.***> schrieb am Di., 20. Dez. 2022, 10:04:

**Comment by saswatamcode** [comment]
+1 to @squat's comment. Also, this is downgrading a lot of deps. Is that intended?

**Comment by Akshit42-hue** [comment]
> +1 to @squat's comment. Also, this is downgrading a lot of deps. Is that intended?

I have updated only two dependencies I think those are inter-dependencies :)

**Comment by yeya24** [comment]
I believe we don't want to downgrade `prometheus/exporter-toolkit` to v0.7.0. We should upgrade to v0.8.2 instead.

**Comment by Akshit42-hue** [comment]
My bad I haven't rebased the branch and have checked the Vulnerability. There is no such Vulnerability in the external dependencies as of now.

**Pull request closed without merging**
