### PR TITLE
Add `@douglascamata` to triagers

### PR DESCRIPTION
**Pull request by douglascamata**
I've been recently offered to be part of the triage team in the project. I'm happy to accept it. 

This adds me to the triagers list.

### CODE REVIEW

**Review by saswatamcode — APPROVED** [review]
Welcome! 🎉

**Review by fpetkovski — APPROVED** [review]
Yay!

**Review by MichaHoffmann — APPROVED** [review]
:tada:

**Comment by douglascamata** [comment]
Thanks, everyone 🙇

I'm very happy to be able to help more. o/

**Review by bwplotka — COMMENTED** [review]
👍🏽 💪🏽

**Pull request merged**
