### PR TITLE
cmd: make bucket upload command take lset from flags

### PR DESCRIPTION
**Pull request by MichaHoffmann**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

* `tools bucket upload-blocks` should get lset from flags ( which is nicely in-line with ruler and receiver then too )
* fixed deadlock because of missing actor function on the command
* is changlog needed here since the original command was not yet released?

### CODE REVIEW

**Comment by nicolastakashi** [comment]
Just a note On docs would be nice show how to pass multiple label values.

Besides that LGTM 🙌

**Comment by yeya24** [comment]
Umm, why we don't keep the previous functionality as well? Taking lset from flag can be an additional flag.

**Comment by MichaHoffmann** [comment]
> Umm, why we don't keep the previous functionality as well? Taking lset from flag can be an additional flag. But I am fine to merge this change.

I think it might be redundant, if we have prometheus around its arguable that we know its ext labels; we can just read prometheus config and put the labels here

**Comment by yeya24** [comment]
Since @nicolastakashi 's usecase is in Prometheus operator, I think it would be nice to get this value dynamically rather than specifying ext labels manually, considering multi cluster scenario.

But I am fine if he is ok with it

**Review by yeya24 — DISMISSED** [review]

**Comment by MichaHoffmann** [comment]
One second, during tests i found there is a deadlock somewhere, ill try to debug and include fix here to!

**Comment by yeya24** [comment]
What's the deadlock?
It is hard to figure it out from your changes as it is in a single commit.
Let's try to use multiple commits since we always squash at the end.

**Comment by MichaHoffmann** [comment]
> What's the fix for deadlock? It is hard to figure it out from your changes as it is in a single commit. Let's try to use multiple commits since we always squash at the end.

No actor on g, it would hang in main on g.Run() when I debugged it in dlv

**Review by yeya24 — APPROVED** [review]
Thanks

**Pull request merged**
