### PR TITLE
Add Alert ThanosQueryOverload to Mixin

### PR DESCRIPTION
**Pull request by raptorsun**
* [ ] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

This PR adds an alert ThanosQueryOverload to the mixins.

This alert warns the user when Thanos' query API is saturated by concurrent queries so that the user can take measurements before functionalities relying on Thanos stops working.

### CODE REVIEW

**Comment by fpetkovski** [comment]
Having this on a dashboard would also be great 👍

**Comment by raptorsun** [comment]
> Having this on a dashboard would also be great +1

Good idea, I'm going to add a "Thanos Query Concurrent Capacity" dashboard with formula `max_over_time(thanos_query_concurrent_gate_queries_max[5m]) - avg_over_time(thanos_query_concurrent_gate_queries_in_flight[5m])`

**Review by bwplotka — APPROVED** [review]
Thanks!

**Review by kakkoyun — DISMISSED** [review]

**Comment by raptorsun** [comment]
A [PR](https://github.com/thanos-io/thanos/pull/5542) is created to add the dashboard showing available capacity to serve concurrent queries.

**Comment by douglascamata** [comment]
Hey @raptorsun, can you have a look at failed checks so that we can proceed with merging your contribution, please? 🙏

**Comment by douglascamata** [comment]
This seems to be breaking some tests and I don't understand why. 🤔 

Does someone have ideas? cc @bwplotka, @kakkoyun, @fpetkovski

**Comment by raptorsun** [comment]
> This seems to be breaking some tests and I don't understand why. 🤔
> 
> Does someone have ideas? cc @bwplotka, @kakkoyun, @fpetkovski

The broken test has been fixed, just need to[ add a stub rule in the testing code](https://github.com/thanos-io/thanos/pull/5439/files#diff-c970ac88b7bc7ebbba9baf19501dae0a28dd37253af838f0f2e01c83eb2f0914R62).

**Review by douglascamata — APPROVED** [review]
LGTM :shipit:

**Review by kakkoyun — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
