### PR TITLE
Add docker compose setup for local development, demo

### PR DESCRIPTION
**Pull request by darshanime**
Signed-off-by: darshanime <deathbullet@gmail.com>

Closes https://github.com/thanos-io/thanos/issues/2249

Add a docker-compose setup for local dev environment, demos etc. 

* [ ] I added CHANGELOG entry for this change.
* [ ] I added documentation for this new flow
* [X] Change is not relevant to the end user.

### CODE REVIEW

**Comment by darshanime** [comment]
@bwplotka the PR is not yet done, but wanted some early feedback on the idea

**Comment by brancz** [comment]
I agree this seems to be best done in a separate project.

**Comment by bwplotka** [comment]
Happy to set up the project for https://github.com/thanos-community/ if you want.

**Comment by darshanime** [comment]
sure, that sounds good @bwplotka 👍

**Comment by bwplotka** [comment]
I mean, this also mean we need longer term maintainer for  such project. Also my worry is that such project will be super small.

Maybe something like deployments would do better :thinking:

**Comment by prmsrswt** [comment]
I think having a sample `docker-compose.yml` would be of great help. Maybe we can add the example to the documentation.

**Comment by darshanime** [comment]
As disussed in community call, this is not required currently. 
Can I close this?

**Pull request closed without merging**
