### PR TITLE
Add Vestiaire Collective to adopters

### PR DESCRIPTION
**Pull request by Ebaneck**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

- Add Vestiaire Collective  to adopters.yml
- Add Vestiaire Collective logo

### CODE REVIEW

**Review by squat — DISMISSED** [review]
Thanks a lot @Ebaneck

**Comment by squat** [comment]
Ah, can you please sign your commit with the DCO? (hint: `git commit --amend --signoff`)

**Comment by Ebaneck** [comment]
Hello @squat 

It is signed, please see [here](https://github.com/thanos-io/thanos/pull/5289/commits/4b53affd46715fb6412e323b07f94e794cbea1ed)

**Comment by squat** [comment]
Hmm for some reason the DCO check is failing

https://github.com/thanos-io/thanos/pull/5289/checks?check_run_id=6061352452

**Comment by squat** [comment]
Hmm for some reason the DCO check is failing

https://github.com/thanos-io/thanos/pull/5289/checks?check_run_id=6061352452

**Comment by Ebaneck** [comment]
Thanks @squat 

It seems to look good now.

**Review by squat — APPROVED** [review]

**Comment by squat** [comment]
docs failing because of #5285
I think we should override some things for now

**Review by yeya24 — APPROVED** [review]
Thanks! Merge now

**Pull request merged**
